### ISSUE TITLE
Further changes to the release process

### ISSUE THREAD

**Issue by hsorby** [cellml/libcellml#1019]
Three more changes for the release process, two are required the other is a nice to have:
1. Install `twine` into the virtual environment to enable upload of Python wheels to Pypi.org [required].
2. Fix upload of binaries to release [required].
3. Remove previous release candidates/development release change logs that have the same major, minor, and patch version.

**Comment by nickerso** [comment]
Does that nice to have need to be split into a separate issue? looks like #1020 resolves the required part of this one.

**Comment by hsorby** [comment]
The nice to have part is actually on the side of the CI. I have already put this in place. Yes, #1020 is actually all that is needed to complete the release process as it is currently intended to work. (Hopefully anyway.)

**Comment by hsorby** [comment]
Actually just found that the binaries did not upload to the release properly, will need to fix that as well.
