### ISSUE TITLE
Latest version 0.3.101 not available for MacOS via pip

### ISSUE THREAD

**Issue by matthiaskoenig** [cellml/libcellml#1033]
Hi all,

the latest version is not available for MacOS, only for linux and windows. Please make releases for all platforms at the same time.
Otherwise CI will fail for the respective platforms. See for instance here:
https://github.com/combine-org/combine-notebooks/runs/8301256207?check_suite_focus=true#step:5:40

Best Matthias

**Comment by hsorby** [comment]
We only have python 3.9 and 3.10 available for macOS.  But, those don't seem to be available either even though they are present on [pypi.org](https://pypi.org/project/libcellml/#files), probably because of the minimum system version being macOS 11.

**Comment by matthiaskoenig** [comment]
This is strange because we test with `macos-latest` and it reports
```
 macOS
  11.6.8
  20G730
```
in the CI run. So this should install? Having py38 support would be great which makes it easy to use it in a test matrix, i.e.
```
matrix:
  os: [ubuntu-latest, macos-latest, windows-latest]
  python-version: ["3.8", "3.9", "3.10"]
```
All other COMBINE libraries support ["3.8", "3.9", "3.10"] on the various platforms.

**Comment by hsorby** [comment]
I would have to suspect that the minimum OSX deployment target is set lower than 11.  Something I think is hinted at when you look at `python_libsedml-2.0.32-cp39-cp39-macosx_10_9_x86_64.whl` the tag of python_libsedml.  Here the minimum deployment target is 10.9. We will have to look at changing the build matrix for cibuildwheel to get support for deployment targets lower than 11.  From memory I don't think it is possible to create an arm64 wheel with deployment targets set lower than 11 hence the bottom line that libCellML has used.

**Comment by hsorby** [comment]
So support has now been added for Python 3.8 (only for x86_64 not arm64) this is in addition to Python 3.9 and 3.10.  Now while you can install these libraries you cannot use them. I will save you the effort of opening a new issue for this as I have already done it here: #1036.
