### ISSUE TITLE
Fix Linux, macOS wheels

### ISSUE THREAD

**Issue by hsorby** [cellml/libcellml#1039]
The Linux and macOS wheels that we are currently creating are not correct. We need to use `-undefined dynamic_lookup` to link the Python library. This allows undefined symbols to be resolved at run time and not link time, this is crucial for distributing C extension binaries.  With this in place, the undefined symbols will be found in the environment that the process/application is running in.  Well that's the theory, now for the practical part.

**Comment by hsorby** [comment]
@matthiaskoenig I finally found the bit of information I was missing that libsbml has that libCellML doesn't. Hopefully, with this implemented we should have full support for Windows, Linux, and macOS over Python 3.8, 3.9, and 3.10.

**Comment by matthiaskoenig** [comment]
@hsorby This is great news.

**Comment by hsorby** [comment]
Okay, the fix is in place, `pip install -U pip` to get the latest. The wheels "works for me"<sup>tm</sup>, over to you @matthiaskoenig.

**Comment by matthiaskoenig** [comment]
Thanks. This works on mac, linux and win with py38.py39, py310 ;)
