### ISSUE TITLE
Modify use-cases step (2)

### ISSUE THREAD

**Issue by dladd** [cellml/libcellml#104]
This issue covers the Modify step as outlined in the [use-cases doc](http://libcellml.readthedocs.io/en/latest/usecases.html). This includes:
- [x] Updates to the object model
- [x] Tests and implementation to modify models from the Create step (1).
  - [x] add {components, units, maths, variables, connections}
  - [x] remove {components, units, maths, variables, connections}
  - [x] update {components, units, maths, model attributes, variables, connections}

**Comment by dladd** [comment]
I think we've already covered the "add" task with the current API. 

For the "remove" task, I believe we'll also need the methods (edited per comment below):
- `Units::removeUnit(std::string): void`
- `Variable::removeEquivalence(VariablePtr, VariablePtr): void`
- `Component::removeVariable(VariablePtr): void`
- `ComponentEntity::removeUnits(UnitsPtr)`

We could also add `removeAll...()` methods to reset collective attributes if that would be useful for a user.

For the "update" task, some more input would be helpful. The only thing that I think might have needed an explicit `update...()` method is a connection. However, connections are currently constructed at-need and not persistently stored. So I think they (and the other elements) should already be in an 'updated' state?

**Comment by jonc125** [comment]
Indeed, I think "update" is implicit in allowing set, remove & add. The `set*` methods probably do what was envisaged here (e.g. update model attributes, i.e. `setName`). Some remove functionality is there already too.

I don't think you need an argument to `Variable::removeUnits` as a variable can only have one set of units associated. You would need the argument for places that stored multiple different units (models, components) but it seems these are handled implicitly in the current object model?

`Component::removeVariable` could do with a variant passing a `VariablePtr` perhaps.

Presumably the `set*` methods on `Variable` would have equivalent behaviour to remove if passed an empty string/pointer? Which suggests that `removeUnits` might be redundant here (or adding for clarity, in which case the same argument applies to initial value and interface type)?

**Comment by dladd** [comment]
Good points, @jonc125. 

> You would need the argument for places that stored multiple different units (models, components) but it seems these are handled implicitly in the current object model?

It looks like we missed `ComponentEntity::addUnits(UnitsPtr)` in the current object model diagram (I'll add it as part of this changeset). So we'll need a corresponding `ComponentEntity::removeUnits(UnitsPtr)`. Then `remove...()` methods will correspond with `add...()` methods. 

An exception to this is `Component::appendMath()/removeMath()`. I wonder if it might be worth replacing `removeMath()` with `setMath(std::string)`, which would allow a user to replace the math string or remove it with `c->setMath("")`. We could still keep `appendMath()` for convenience.

As you pointed out, we can similarly remove/reset the non-vector variable attributes with:
`v->setUnits(nullptr)`
`v->setInitialValue("")`
`v->setInterfaceType("")`

**Comment by jonc125** [comment]
A general principle of API design is to be consistent, so `set` should always parallel `get` and `add` vs `remove` in my opinion. The `Math` case is unusual at present partly because it is an interim design, but given we have `getMath` we probably should have `setMath` rather than `removeMath`, yes. Having the `appendMath` for convenience too is fine.
