### ISSUE TITLE
Support for python3.11

### ISSUE THREAD

**Issue by matthiaskoenig** [cellml/libcellml#1048]
Hi all,

python3.11 has been released lately.
Most of the COMBINE python libraries have now python3.11 support. I would require also python3.11 bindings for libcellml, e.g. for running the combine-notebooks.
Python 3.11 has some amazing speedups of ~10-40%. It would be great to have also libcellml in python3.11 to be able to profit from this speedups.

Best Matthias

**Comment by hsorby** [comment]
Hopefully this will be a simple matter of enabling this version with an addition to our py versions for matrix for cibuildwheel.
