### ISSUE TITLE
Code clean-up items before 'Modify' step

### ISSUE THREAD

**Issue by dladd** [cellml/libcellml#105]
This issue picks up general items for clean-up before we move on to Modify use-cases. Feel free to comment with anything else you would like to see addressed.
- [x] Change variable interface type handling to be consistent with unit prefixes from #103 
  - Would allow us to get rid of the remaining EXPORT_FOR_TESTING instance
  - If we store the interface type as a string internally, we could:
    - allow the user to specify the interface type by string.
    - allow the user to serialise out `interface_type=none` if they choose to do so.
- [x] Swap out plain `enum`s for `enum class`es where possible
  - More strongly typed and generally preferred in C++11
  - Example usage:

``` c++
libcellml::Prefixes prefix = libcellml::Prefixes::MICRO;
libcellml::Variable::InterfaceTypes interfaceType1 = libcellml::Variable::InterfaceTypes::NONE;
```

vs. the current style:

``` c++
libcellml::PREFIXES prefix = libcellml::PREFIX_MICRO;
libcellml::Variable::INTERFACE_TYPES interfaceType1 = libcellml::Variable::INTERFACE_TYPE_NONE;
```

**Comment by jonc125** [comment]
I haven't looked through the code, but the aims look good to me.

**Comment by agarny** [comment]
Same as @jonc125.
