### ISSUE TITLE
Improve branch coverage as reported by LLVM

### ISSUE THREAD

**Issue by hsorby** [cellml/libcellml#1055]
The next frontier in coverage is branch coverage.
I would like to see the CI incorporate in a measure for the branch coverage given by llvm coverage.
I would also like to see the CI set a minimum bound for the branch coverage so we can only increase branch coverage, until we reach 100% coverage for branches.

**Comment by agarny** [comment]
@hsorby, has this not been done?

**Comment by hsorby** [comment]
Yes it has, someone clearly has not closed it our linked it to a PR>
