### ISSUE TITLE
Code clean-up items before 'Load' step

### ISSUE THREAD

**Issue by dladd** [cellml/libcellml#110]
Proposed cleanup items are:
- [x] **(A)** Change `enum class` names from plural to singular. For example, `libcellml::Prefixes::MICRO` would become `libcellml::Prefix::MICRO` (from comments in #107).
- [x] **(B)** ~~Change Doxygen documentation to remove space above `@overload`~~ (_Edit_) Change Doxygen documentation handling of whitespace (TBD below) [Example of current style](https://github.com/cellml/libcellml/blob/develop/src/api/libcellml/units.h#L150) 
- [x] **(C)** Further tests and implementation for C++11 copy/move

**Comment by dladd** [comment]
If I get a vote, I am for (A) but against (B). I think it is useful to have the visual cue of the extra space to indicate that you are looking at a block of overloaded methods when scrolling through a header file.

**Comment by agarny** [comment]
I currently vote for A only. Indeed, regarding B, your example actually highlights a couple of issues for me:
- I don't know the rules when it comes to mentioning `@overload`, but why isn't `@overload` mentioned for the first `addUnit()` method? Imagine if, for some reason or another, you were to re-order the different `addUnit()` methods, then you might accidentally end up with the first `addUnit()` method mentioning `@overload` and one of the subsequent `addUnit()` methods not mentioning it. So, if anything, I would like to have `@overload` mentioned for all `addUnit()` methods.
- I agree that to have a blank line before `@overload` makes it stand out, but I wonder whether we couldn't have a blank line before `@param` too (only if it's not an overloaded method). It would make the parameters stand out and if it was to be an overloaded method, then `@overload` would still stand out.

**Comment by jonc125** [comment]
I almost never say no to extra blank lines :)

**Comment by nickerso** [comment]
Whitespace

good

:)

**Comment by dladd** [comment]
Re:

> I don't know the rules when it comes to mentioning `@overload`, but why isn't `@overload` mentioned for the first addUnit() method?

If you have a look in the [generated Doxygen](http://autotest.bioeng.auckland.ac.nz/libcellml-buildbot/cf1c987e74bfe9efc35ec7811686c8fe719b7410/dox/code/classlibcellml_1_1Units.html#a95299aac24939e24a6a9e8cf4dcfc960), mentioning `@overload` triggers the following note:

_This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts._

So it should probably only be used in overloaded methods following the first instance.

<br />
Re:

> I wonder whether we couldn't have a blank line before `@param` too (only if it's not an overloaded method).

I suppose if we change this we should probably be explicit about our whitespace handling of all [Doxygen keywords](https://www.stack.nl/~dimitri/doxygen/manual/commands.html) (e.g., `@brief`, `@return`). To give some options with examples: (below will look very wordy- probably best to just look at aesthetics and view on GitHub for syntax highlighting :) )

**(1)** Current style: space preceding `@overload` only:

``` c++
    /**
     * @brief Add a unit to this Units.
     * Add a unit as a child of this Units.  This method takes optional arguments
     * exponent, multiplier and offset.
     * @param name The name of the unit to add.
     * @param prefix The string prefix for the unit.
     * @param exponent The exponent.
     * @param multiplier The multiplier.
     * @param offset The offset.
     */
    void addUnit(const std::string &name, const std::string &prefix, double exponent=1.0,
                 double multiplier=1.0, double offset=0.0);

    /**
     * @brief Add a unit to this Units.
     * Add a unit as a child of this Units.  This method takes optional arguments
     * exponent, multiplier and offset.
     *
     * @overload
     * @param name The name of the unit to add.
     * @param prefix The prefix for the unit, one of Prefixes.
     * @param exponent The exponent.
     * @param multiplier The multiplier.
     * @param offset The offset.
     */
    void addUnit(const std::string &name, Prefixes prefix, double exponent=1.0,
                 double multiplier=1.0, double offset=0.0);
```

**(2)** One space preceding all Doxygen keywords following the description:

``` c++
    /**
     * @brief Add a unit to this Units.
     * Add a unit as a child of this Units.  This method takes optional arguments
     * exponent, multiplier and offset.
     *
     * @param name The name of the unit to add.
     * @param prefix The string prefix for the unit.
     * @param exponent The exponent.
     * @param multiplier The multiplier.
     * @param offset The offset.
     */
    void addUnit(const std::string &name, const std::string &prefix, double exponent=1.0,
                 double multiplier=1.0, double offset=0.0);

    /**
     * @brief Add a unit to this Units.
     * Add a unit as a child of this Units.  This method takes optional arguments
     * exponent, multiplier and offset.
     *
     * @overload
     * @param name The name of the unit to add.
     * @param prefix The prefix for the unit, one of Prefixes.
     * @param exponent The exponent.
     * @param multiplier The multiplier.
     * @param offset The offset.
     */
    void addUnit(const std::string &name, Prefixes prefix, double exponent=1.0,
                 double multiplier=1.0, double offset=0.0);
```

**(3)** A space preceding each new Doxygen keyword type following the description:

``` c++
    /**
     * @brief Add a unit to this Units.
     * Add a unit as a child of this Units.  This method takes optional arguments
     * exponent, multiplier and offset.
     *
     * @param name The name of the unit to add.
     * @param prefix The string prefix for the unit.
     * @param exponent The exponent.
     * @param multiplier The multiplier.
     * @param offset The offset.
     */
    void addUnit(const std::string &name, const std::string &prefix, double exponent=1.0,
                 double multiplier=1.0, double offset=0.0);

    /**
     * @brief Add a unit to this Units.
     * Add a unit as a child of this Units.  This method takes optional arguments
     * exponent, multiplier and offset.
     *
     * @overload
     *
     * @param name The name of the unit to add.
     * @param prefix The prefix for the unit, one of Prefixes.
     * @param exponent The exponent.
     * @param multiplier The multiplier.
     * @param offset The offset.
     */
    void addUnit(const std::string &name, Prefixes prefix, double exponent=1.0,
                 double multiplier=1.0, double offset=0.0);
```

**(3.1)** A space preceding each new Doxygen keyword type following the description and a space following `@brief`:

``` c++
    /**
     * @brief Add a unit to this Units.
     *
     * Add a unit as a child of this Units.  This method takes optional arguments
     * exponent, multiplier and offset.
     *
     * @overload
     *
     * @param name The name of the unit to add.
     * @param prefix The prefix for the unit, one of Prefixes.
     * @param exponent The exponent.
     * @param multiplier The multiplier.
     * @param offset The offset.
     */
    void addUnit(const std::string &name, Prefixes prefix, double exponent=1.0,
                 double multiplier=1.0, double offset=0.0);
```

I think I am personally in favour of (3)

**Comment by dladd** [comment]
I've added item **(C)** to this: "Further tests and implementation for C++11 copy/move". @hsorby pointed out that I missed a few variable attributes in the copy/move constructors so I've added those, along with tests for this functionality (see https://github.com/cellml/libcellml/pull/112/commits/c74de4bfd55f045426769d83cc631180c65daa34).

**Comment by agarny** [comment]
> So it should probably only be used in overloaded methods following the first instance.

Ok, it makes sense indeed.

Otherwise, I am in favour of (3.1), but I guess I would be fine with (3) too.
