### ISSUE TITLE
Code clean-up items

### ISSUE THREAD

**Issue by dladd** [cellml/libcellml#116]
Proposed items for clean-up after the next set of pulls:
- [x] Convert inline "if"s to multiline (issue #117 )
- [x] Namechange from CellML 1.2 to 2.0
- [x] Update copyright statement
- [x] Standardise visual formatting of XML strings in tests with indentation
- [x] Tidy-up less efficient multiline methods where appropriate.

Please comment if there is anything else you would like to see addressed.

**Comment by agarny** [comment]
Regarding the copyright statement, do we absolutely have to provide the year? Also, does it mean that all libCellML files must have their copyright updated every year? If so, it would then mean that we lose the year at which the project started? In the end, couldn't we simply have:

```
Copyright libCellML Contributors
```

**Comment by dladd** [comment]
That works for me- I'm happy to take out the year altogether as it likely [isn't necessary](http://www.contentious.com/2007/01/07/copyright-notice-is-the-year-really-necessary/). Git is a better method to actually track when a file was modified than a bit of stub header text that we are likely to forget to update each year.

I do think we are required to give attribution to University of Auckland. And maybe VPR or University of Michigan for further support?

**Comment by jonc125** [comment]
The Chaste notice uses "Copyright (c) 2005-2016, University of Oxford" and we update the end date each year. I would be inclined to include an initial year, but the end year could I think be omitted.

Attributing various funders/organisations should probably be done in separate documentation rather than the copyright notice, or it gets too long. If we're going to be formal about it we probably need a contributor licence agreement etc...

**Comment by agarny** [comment]
FWIW, whatever solution we go with, it shouldn't mean updating all files every year.

**Comment by dladd** [comment]
Regarding the copyright issue, it sounds like there is agreement to keep 2015 in all template text as the start year of the project (rather than going with the year a particular file was added). That just leaves whether or  not to change the template text copyright holder from "University of Auckland" to "libCellML Contributors" (attribution of all funders/organisations will be left for the full license/documentation). I.e., options:
- **(A)**/remain: `Copyright 2015 University of Auckland`
- **(B)**/change: `Copyright 2015 libCellML Contributors`

~~I'll add a +1 for **A**.~~

**Comment by agarny** [comment]
Did I agree to keep 2015 in the copyright? Anyway, for me to have the starting year without the current/ending year gives me the impression that the project started and ended in 2015, hence my preference would be for:
- **(C)**: `Copyright University of Auckland`

**Comment by dladd** [comment]
Apologies- fair point, @agarny

**Comment by nickerso** [comment]
I think the copyright statement should be `Copyright libCellML Contributors` and we add a contributors page in the docs which lists University of Auckland, VPR, (Oxford?) and the individual contributors as per the git logs to the project. That page would also indicate that all contributors agree to contribute under the Apache 2 license. We could look at a more github-based CLA system in the future if the number of contributors takes off - as it no doubt will soon.

**Comment by hsorby** [comment]
No doubt, none at all.

**Comment by agarny** [comment]
> I think the copyright statement should be `Copyright libCellML Contributors` and we add a contributors page in the docs which lists University of Auckland, VPR, (Oxford?) and the individual contributors as per the git logs to the project. That page would also indicate that all contributors agree to contribute under the Apache 2 license. We could look at a more github-based CLA system in the future if the number of contributors takes off - as it no doubt will soon.

Hmm, if we think that it's fine to have this for libCellML, then I think I am going to do the same for OpenCOR...

**Comment by nickerso** [comment]
While I personally don't mind, there is probably a difference between a library which we encourage the community to contribute to and an application paid for predominantly by a single institution... :)

**Comment by agarny** [comment]
> While I personally don't mind, there is probably a difference between a library which we encourage the community to contribute to and an application paid for predominantly by a single institution... :)

Hmm, fair point. Ok, I will leave it as is (less 'work' that way too... :)).

**Comment by dladd** [comment]
Regarding: Standardise visual formatting of XML strings in tests with indentation,

it was suggested that we might prefer to use two-space indentation over the four-space otherwise used in the tests. I think aesthetic arguments can be made either way but I have a preference for keeping the indentation consistent as four-space since mixed styles may confuse auto-indent in some IDEs.

**Comment by hsorby** [comment]
I can no longer find any inline "if" statements in the codebase.  This item can be checked off in the list.

**Comment by hsorby** [comment]
What are we trying to achieve with the standardisation of the XML strings in tests or rather what would an XML string look like if it conformed to the standard?

**Comment by hsorby** [comment]
Also is there an example of where a less efficient multiline method is, I'm not sure what this checkbox list item refers to.

**Comment by dladd** [comment]
re: XML strings, it was suggested that it would be good to have the test strings nicely indented for readability. For example, from `component.replaceComponentMethods` we might change

``` XML
const std::string e_orig = "<component name=\"parent\"/><component/><component name=\"child2\"/><encapsulation><component_ref component=\"parent\"><component_ref/><component_ref component=\"child2\"/></component_ref></encapsulation>";
```

to 

``` XML
const std::string e_orig = 
    "<component name=\"parent\"/>"
    "<component/>"
    "<component name=\"child2\"/>"
    "<encapsulation>"
        "<component_ref component=\"parent\">"
            "<component_ref/>"
            "<component_ref component=\"child2\"/>"
        "</component_ref>"
    "</encapsulation>";
```

re: multiline methods, please see [discussion here](https://github.com/cellml/libcellml/pull/114#discussion-diff-68508154R224). Basically, we have standardised a few places (I think mainly around `find`s) where we have temporary variables that probably aren't necessary.

**Comment by hsorby** [comment]
Still (possibly) need to address the crazy find methods that return an iterator as [mentioned here](https://github.com/cellml/libcellml/pull/114#discussion-diff-68508154R224).  One option is to leave it alone as these methods are only available from the implementation and not through the API.  Another option is to rename the methods so the name relates more to what the method actually does. (Some deep thinking has gone into that.)  And one more option is to implement the methods as the method name suggests.

**Comment by nickerso** [comment]
I think for those internal methods it is fine to follow the STL pattern and have `find` methods return iterators.

**Comment by agarny** [comment]
Ideally, we would "implement the methods as the method name suggests", but I would probably agree with @nickerso that it's fine for internal methods, which means that we might want to "rename the methods so the name relates more to what the method actually does".

**Comment by hsorby** [comment]
I do find it odd but that is what the stl find_if returns.  I'm going with what is good enough for them is good enough for me.

**Comment by jonc125** [comment]
To clarify: I didn't think it odd that find returns an iterator - that is normal and expected. What was odd was then using this iterator to compute an offset into the vector to return the found units, when we could just dereference (after a check that it doesn't point to end).

**Comment by agarny** [comment]
Hmm, good point @jonc125!

**Comment by hsorby** [comment]
If no-one has anything else pending this issue can be closed I think.

**Comment by agarny** [comment]
Fine by me.
