### ISSUE TITLE
Code style exception - inline if's

### ISSUE THREAD

**Issue by hsorby** [cellml/libcellml#117]
The base style guide allows for inline if statements e.g.

`
if (!mapVariablesNode) throw std::invalid_argument("Connection only contains a map_components (no map_variables).");
`

Unfortunately this hides a line from the coverage testing.  This issue is for adding an exception to the libCellML code style to **not** allow the use of inline if's.

**Comment by mirams** [comment]
Good idea! Always find them hard to read anyway.

**Comment by dladd** [comment]
Fair enough- I've just added this to the clean-up action items in #116
