### ISSUE TITLE
Set minimum OSX deployment target to 10.15

### ISSUE THREAD

**Issue by hsorby** [cellml/libcellml#1180]
Setting the minimum OSX deployment target to 11 would simplify or maintenance slightly.
According to [wikipedia](https://en.wikipedia.org/wiki/MacOS_version_history) macOS 11 is the oldest currently supported software version, it seems reasonable to set this version as the minimum deployment target for libCellML.

**Comment by nickerso** [comment]
Our CI currently uses an intel-based Mac that is not able to be updated to support the change to target 11. 10.15 is newest that it can support, which fortunately is sufficient for the julia requirements. (as per discussion with @hsorby)

**Comment by agarny** [comment]
Ok, that's what I thought. I was just being "stubborn" and commenting based on the original GitHub issue. :)

**Comment by agarny** [comment]
For the record, this means that our macOS-based CI runs on a version of macOS which is not supported by Apple anymore. Yeah, one more reason I would just go with GitHub actions...
