### ISSUE TITLE
Separate serialisation from entities into a Logger class

### ISSUE THREAD

**Issue by dladd** [cellml/libcellml#120]
Eventually we will want to separate our serialisation routines into a separate `Printer` class inheriting from `Logger` to flag errors, as done for the  `Parser` and planned for the `Validator`. This isn't an immediate priority since serialisation as currently implemented is meeting our needs.

_(edited for clarity per Hugh's comment below)_

**Comment by hsorby** [comment]
Into a separate `Printer` class inheriting from `Logger` as is done for the `Parser` class.
