### ISSUE TITLE
Generator: `computeComputedConstants()` may not generate some dependencies in the right place

### ISSUE THREAD

**Issue by WeiweiAi** [cellml/libcellml#1216]
Hi team,

I tried to solve the attached models using the Python package Scipy ode solver
[GLUT1_BG.zip](https://github.com/cellml/libcellml/files/14737258/GLUT1_BG.zip).
I had to call _compute computed constants(variables)_ twice in my initialization code, otherwise, some variables/constants are nan.
For many other models, I only needed to call compute computed constants(variables) once.

It would be great if the team could provide some guidance on how to initialize and solve the system (generated Python), in particular the call orders of the _compute_variables(), compute_rates(),compute_computed_constants()_, etc.

Thanks. 

Weiwei.

**Comment by agarny** [comment]
Hi @WeiweiAi, I haven't checked your model, but to fully initialise a model, you need to call all the methods, i.e.

- For an ODE/DAE model:
```python
initialise_variables(states, rates, variables)
compute_computed_constants(variables)
compute_rates(voi, states, rates, variables)
compute_variables(voi, states, rates, variables)
```
- For an algebraic/NLA model:
```python
initialise_variables(variables)
compute_computed_constants(variables)
compute_variables(variables)
```

**Comment by WeiweiAi** [comment]
Hi @agarny, thanks for the instructions. For the model that I attached here, I need to repeat "compute_computed_constants(variables)" one more time.

**Comment by agarny** [comment]
Ok, I guess I will need to have a proper look at your model then.

**Comment by agarny** [comment]
FWIW, I can indeed confirm the issue and I can see where, in the Python code, it's doing that. Now, I need to understand why `b`, which is needed by `K_1`, doesn't get computed before `K_1`...

**Comment by agarny** [comment]
If I manually put the calculation for `b` before `K_1` then, as expected, everything is fine.

**Comment by agarny** [comment]
FTR, the analyser reports that `K_1` has rightly a dependency on `K_3`, `K_6`, `a`, and... `b`. So, the issue is somewhere else...

**Comment by agarny** [comment]
@WeiweiAi, thanks again for the report! This has now been [fixed](https://github.com/cellml/libcellml/pull/1217) and awaiting review.
