### ISSUE TITLE
Python coverage: (wrongly?) report a memory leak of type 'std::vector< std::shared_ptr< libcellml::AnalyserEquation > > *'

### ISSUE THREAD

**Issue by agarny** [cellml/libcellml#1222]
If we look at the [latest Python coverage](https://autotest.bioeng.auckland.ac.nz/buildbot/libcellml/#/builders/10/builds/1070), we can see that it has 100% coverage, but `swig/python detected a memory leak of type 'std::vector< std::shared_ptr< libcellml::AnalyserEquation > > *', no destructor found.`

We don't have any memory leaks for our C++ codebase, so is that a false positive or a real issue with our Python bindings?

**Comment by nickerso** [comment]
Duplicate of #1129?

**Comment by hsorby** [comment]
Yes dupe.
