### ISSUE TITLE
Introducing XML Document Identifiers ('id' attributes)

### ISSUE THREAD

**Issue by dladd** [cellml/libcellml#123]
The cellml1to2 tests that have now been added in #114 have pointed out that we have not yet implemented XML Document Identifiers. This is item 2.5 in the [Specification](https://docs.google.com/document/d/1MleZJF6DYp4FO4vxslAHInrRFMqrSpARa1s_dPhwYU0/edit?usp=sharing):

> Any element information item in the CellML namespace MAY contain an attribute information item with local name id, in the CellML namespace. This attribute information item SHALL be treated as having attribute type ID, as defined in section 3.3.1 of XML 1.1.

We can support this by adding a `mId` string attribute on the Entity class, with associated `get/set()` methods. This will also require changes to our serialisation and parsing routines. Since I've merged the cellml1to2 tests into the pull for #114, the easiest way to move forward is probably to tack implementation and tests for IDs on to #114 . However, since that pull is already somewhat large and unwieldy, I can try reverting the cellml1to2 merge and setting this up as a separate pull if that is preferred.

**Comment by nickerso** [comment]
Might be worth adding implementation and tests for IDs in creation and serialisation as a separate pull request which will presumably be fairly quick to review and then that can be pulled into #114 in terms of loading/parsing.

**Comment by dladd** [comment]
Thanks @nickerso that sounds reasonable. 

However, I'm beginning to realise this might be less trivial than I expected. My read of the above Spec snippet is that we need to be able to track IDs for **every** element information item (EII). This includes EIIs that are outside of our current Entity hierarchy like connections, encapsulations, and component_refs. Is this the correct interpretation of the Spec?

**Comment by jonc125** [comment]
Hmm, good point. Yes, that is the correct interpretation - any CellML element may have an id. They are mainly used as a reference point for metadata annotations, and in practice it'll be variables & models that carry them most often I expect, though I can see that one might want to annotate connections or encapsulations with justifications. My inclination at this point would be to defer that problem for another day - create a separate issue for annotation of CellML elements that don't have a specific representation in the libCellML object model.
