### ISSUE TITLE
Can't install libcellml in Python3.12

### ISSUE THREAD

**Issue by FinbarArgus** [cellml/libcellml#1248]
When using Python3.12, which is now used with OpenCOR, we can't install libcellml. This problem arose from this issue https://github.com/opencor/opencor/issues/2800 for more information. 

From the /OpenCOR-2024-08-23-linux/ directory

```
./pip install libcellml
ERROR: Could not find a version that satisfies the requirement libcellml (from versions: none)
ERROR: No matching distribution found for libcellml
farg967:~/software/OpenCOR-2024-08-23-Linux$ ./pip install libcellml==0.3.102
ERROR: Could not find a version that satisfies the requirement libcellml==0.3.102 (from versions: none)
ERROR: No matching distribution found for libcellml==0.3.102
```

I'm using Ubuntu22, but I assume this is an issue with Python3.12. As installing libcellml on Ubuntu22 with the python version shipped with OpenCOR-0-7-1 (Python3.7) worked fine.

**Comment by agarny** [comment]
Indeed, this is an issue with us not providing a wheel for Python 3.12 rather than Ubuntu 22.04 LTS. We can see that [here](https://pypi.org/project/libcellml/0.5.0/#files) where Python 3.11 is indeed the most recent version of Python that we support.

**Comment by nickerso** [comment]
Seems that following #1206 we probably just need to make a release to get the python 3.12 packages released?

**Comment by agarny** [comment]
> Seems that following #1206 we probably just need to make a release to get the python 3.12 packages released?

Maybe with #1246 and #1247? I spent the last couple of days on OpenCOR, so will have #1247 ready next week. (#1220 is clearly for later, not least since it currently doesn't work from Python.)

**Comment by hsorby** [comment]
With the release of 0.6.0 you should now be able to install libCellML into Python 3.12 environments (also Python 3.13).

**Comment by FinbarArgus** [comment]
This works great now!
