### ISSUE TITLE
Update deployment GitHub action script.

### ISSUE THREAD

**Issue by hsorby** [cellml/libcellml#1263]
Some aspects of the deployment GitHub actions script are out-of-date:
* some actions are old and about to be removed,
* some runners are old,
* some scripts are old.

**Comment by hsorby** [comment]
Decision (pending):

LibXml2 has been up-to its old tricks again, deprecating and removing functionality between patch releases.  Relevant to us is the no-op-ing of `xmlCleanupGlobals`.

There is nothing in the changelog but I believe it first happened with [v2.10.4](https://gitlab.gnome.org/GNOME/libxml2/-/releases/v2.10.4) after [v2.10.3](https://gitlab.gnome.org/GNOME/libxml2/-/releases/v2.10.3) and subsequently with [v2.11.0 etc.](https://gitlab.gnome.org/GNOME/libxml2/-/releases/v2.11.0).

For our use of `cibuildwheel` we either need to remove the calls to `xmlCleanupGlobals` or allow warnings when building the library.

Possible investigation required to determine if removing the `xmlCleanupGlobals` causes memory leaks. If it doesn't then this is the solution I would prefer.

**Comment by hsorby** [comment]
Decision (pending):

With the latest `cibuildwheel` we will drop Python support for version 3.7 on GNU/Linux. We do not have to drop support for this case but the workaround would be large, specific, and a pain to maintain.

**Comment by agarny** [comment]
> Decision (pending):
> 
> LibXml2 has been up-to its old tricks again, deprecating and removing functionality between patch releases. Relevant to us is the no-op-ing of `xmlCleanupGlobals`.
> 
> There is nothing in the changelog but I believe it first happened with [v2.10.4](https://gitlab.gnome.org/GNOME/libxml2/-/releases/v2.10.4) after [v2.10.3](https://gitlab.gnome.org/GNOME/libxml2/-/releases/v2.10.3) and subsequently with [v2.11.0 etc.](https://gitlab.gnome.org/GNOME/libxml2/-/releases/v2.11.0).
> 
> For our use of `cibuildwheel` we either need to remove the calls to `xmlCleanupGlobals` or allow warnings when building the library.
> 
> Possible investigation required to determine if removing the `xmlCleanupGlobals` causes memory leaks. If it doesn't then this is the solution I would prefer.

Let's hope that removing `xmlCleanupGlobals()` won't leak indeed. I really don't like to see warnings when building a library.

libxml2 is regularly causing us problems and to use its latest version is not as straightforward (from what I remember when I tried in libOpenCOR). This makes me wonder whether we shouldn't try to look for an alternative to libxml2...?

> With the latest `cibuildwheel` we will drop Python support for version 3.7 on GNU/Linux. We do not have to drop support for this case but the workaround would be large, specific, and a pain to maintain.

I think this should be fine. How many minor versions of Python did we say we wanted to support? Python is at 3.13 now, so to support the last 5 minor versions should be fine? That would require supporting Python 3.9 and later.

**Comment by hsorby** [comment]
For me we would like to support the last 5 minor versions, keeping support for older versions until they start causing problems.
