### ISSUE TITLE
Use #pragma once rather than include guards

### ISSUE THREAD

**Issue by agarny** [cellml/libcellml#129]
Right now, we use include guards, but this can be a bit tedious and has some disadvantages (e.g. longer building time). So, instead, we might want to use `#pragma once`. Sure, it's not part of the C++ standard, but it is implemented by many compilers, so maybe worth giving it a try? ( FWIW, Qt Creator uses `#pragma once` in its codebase.)

**Note:** we might want to take advantage of https://github.com/cgmb/guardonce.

**Comment by nickerso** [comment]
seems like a good idea next time someone has a "rainy day" ;-)

**Comment by hsorby** [comment]
As far as I can tell `#pragma once` is faster only for VS.  GCC optimises include guards to the same effect as `#pragma once`.  I'm not sure what clang does.  The main advantage that `#pragma once` gives is stopping bugs from copy and pasting header guards.

As long as all the tests pass I'm not against using `#pragma once`.
