### ISSUE TITLE
Stop returning const references to smart pointers

### ISSUE THREAD

**Issue by hsorby** [cellml/libcellml#139]
Whilst investigating some other issues I came across this:

http://stackoverflow.com/questions/10643563/how-to-return-smart-pointers-shared-ptr-by-reference-or-by-value

I think we should follow this advice and stop returning const references to smart pointers in our codebase.

**Comment by nickerso** [comment]
+1

**Comment by agarny** [comment]
+1

**Comment by dladd** [comment]
+1 

Returning smart pointers by value rather than const reference should also address #126.

**Comment by hsorby** [comment]
Resolved.
