### ISSUE TITLE
Exceptions (again)

### ISSUE THREAD

**Issue by hsorby** [cellml/libcellml#140]
In light of issue #139 the main reason for throwing exceptions is now gone.  Do we still want to throw exceptions in libCellML?  Is it Exceptable to throw an exception when a user wants to remove a component in a model by an index that is not valid for instance?

`if (model.componentCount() == 3) {
    model.removeComponent(5);
}`

**Comment by nickerso** [comment]
I have no problem with exceptions. I'm also happy if all those `void` functions returned a success/failure instead of throwing an exception.

Either way, as long as the documentation matches the implementation, I'd be happy :)

**Comment by hsorby** [comment]
I guess then we are not necessarily talking about exceptions but about how the user is notified if things didn't go to plan.  I can think of three scenarios:
1. Exception is thrown.
2. A status is returned (true, false, nullptr).
3. Nothing happens, methods silently fail.

We should probably decide on one of these approaches and be consistent across the codebase.

**Comment by nickerso** [comment]
I'm ok with 1 or 2, but wouldn't like 3 at all. Users can treat 2 as 3 by ignoring the return code if they want to use the API in that way.

**Comment by hsorby** [comment]
For consistency reasons I would prefer 2.  Currently we are returning nullptr if a component is not found instead of throwing an exception.  I think we should extend this so that all methods return a status in some form.

**Comment by agarny** [comment]
Definitely option 2 for me.

**Comment by jonc125** [comment]
I actually prefer to throw exceptions if the code user has done something 'wrong', and trying to remove/retrieve a non-existent component would fall in this category for me. Null return values are often not checked (original programmer "I know this can't be null here", 2 months later...). Null returns feels much more like a C API as well, exceptions seem to be the norm in the STL.

We can have separate methods to test for existence.

**Comment by mtcooling** [comment]
I've been asked to comment since things seem split.

3 is an abomination.

I lean much more to 2 than 1. A better summary of why than I can write off the top of my head can be found here in Joel Spolsky's blog:

http://www.joelonsoftware.com/items/2003/10/13.html

As a 'user', I wouldn't mind as long as it was consistent.
