### ISSUE TITLE
Printer class with overload methods

### ISSUE THREAD

**Issue by hsorby** [cellml/libcellml#147]
Should the methods in the Printer class be overloaded methods or explicit about what is being printed.

**Comment by nickerso** [comment]
I think consistency with the parser method names is sufficient reason to stick with the current names and not overload.

**Comment by agarny** [comment]
I hadn't thought of the parser method names, but being in favour of consistency, I am now 'happy' with the current printer method names.

**Comment by hsorby** [comment]
Closing this issue as we are going with what we currently have.
