### ISSUE TITLE
Agree on the initial scope of libCellML

### ISSUE THREAD

**Issue by nickerso** [cellml/libcellml#15]
It would be good to document the intended scope of libCellML and this issue is to ensure there is agreement on the scope of the library. Obviously the scope may change over time, but this initial scope will guide the development of the project to address the initial set of use-cases.

The initial proposal is that the purpose of libCellML is to create, manipulate, serialise, deserialise, validate and instantiate CellML models. In the first instance, all serialising and deserialising will be to and from standard strings and using the CellML XML format. 

The library should be lightweight and focused purely in dealing with CellML models. In achieving this, some of the convenience methods/objects that we might expect will not be part of libCellML. For example, in our current thoughts, libCellML would not be concerned with the actual mechanics of resolving and retrieving external resources - calling applications would be required to resolve and retrieve import URL's and provide the serialised documents to libCellML in the form of strings for instantiation as part of the CellML 1.1/1.2 hierarchical model description. 

Example code would be provided which demonstrates how such tasks can be achieved using standard tools, i.e., libcurl for C/C++ and maybe whatever PMR2 uses in Python to resolve and retrieve imported models.

**Comment by agarny** [comment]
I am happy with that initial scope.

**Comment by jonc125** [comment]
I guess we can go with just example code initially, but I think this is a fairly useful feature to have in the core library eventually!
