### ISSUE TITLE
Update codebase to May 2017 draft CellML 2.0 Specification

### ISSUE THREAD

**Issue by hsorby** [cellml/libcellml#150]
The codebase needs to be updated to match the current draft specification May 2017.  The changes needed are (in no particular order):

- [x] Remove base_unit designation
- [x] Base on XML version 1.1
- [x] Remove ability to define units locally to a component
- [x] Remove offsets attribute from units -> This removes Celsius from the list of base units
- [x] Simplify connections by removing the map_components element

These items are for cleaning up the codebase where the current implementation is no longer part of the specification.  For other items, like reset rules, where there is no implementation in the codebase these will be left to be implemented in separate unlinked issues.

**Comment by nickerso** [comment]
I believe this is all done now, closing.
