### ISSUE TITLE
Adding initial Python bindings

### ISSUE THREAD

**Issue by MichaelClerx** [cellml/libcellml#161]
From Andre/Hugh:

> The idea is to have a "bindings/python" folder which would contain the SWIG config/interface files for generating python bindings for the libCellML API. This would also need to be added to the CMake build system so that the bindings can be built. Hugh has found some issues previous with other projects where CMake won't "notice" changes in the API header files and trigger the bindings to be remade when the API changes, but there are ways to work around that on the CI system and still a chance the CMake community will respond to his issues there.

- [x] Add infra + CMake scripts to generate bindings
- [x] Add infra + CMake scripts to generate tests
- [x] Add CMake scripts to generate Python bindings

Swig interfaces (and Python tests):
- [x] Entity (See #193)
- [x] NamedEntity
- [x] ImportedEntity (See #188)
- [x] Import(Source) (See #189, #194)
- [x] ComponentEntity (See #195, #198)
- [x] Component
- [x] Model
- [x] Units (See #203, #204)
- [x] Variable (See #202)
- [x] Error
- [x] Logger
- [x] Printer
- [x] Parser
- [x] Validator
- [x] version
- [x] enumerations
- [x] specification rule

Useful links:
- https://www.softwariness.com/articles/api-design-for-swig/

**Comment by hsorby** [comment]
To clarify what we are looking for directory structure wise is:

```
src/
     - bindings/
                - interface/
                - python/
```

the interface directory holds the interface files used by swig. The python directory holds just the CMake code required for generating Python bindings.  It is desired to support other scripting languages so the interface files will (hopefully) be common to all.

**Comment by hsorby** [comment]
We could possibly break this issue down into 

- [x]  Adding SWIG interface files
- [x]  Adding CMake Python bindings generation script

As getting started on Python bindings isn't really an issue.

**Comment by jonc125** [comment]
I've just seen a presentation by the Fenics team at a conference, and they're moving from Swig to [pybind11](https://github.com/pybind/pybind11) - might be worth a look?

Just chatted to Chris Richardson after the session. He says it's really easy to use, and well worth spending a couple of hours playing with - we'll "never look back"! So definitely worth some experimentation @MichaelClerx.

**Comment by MichaelClerx** [comment]
Does it support other languages @jonc125 ?

**Comment by jonc125** [comment]
I don't think so, just Python. But it therefore does Python very well! And at the moment we don't have anyone asking for bindings other than Python AFAIK.

**Comment by nickerso** [comment]
The current roadmap for libCellML based on community input (http://libcellml.readthedocs.io/en/latest/roadmap.html) lists the following languages in Milestone 1: C++, Python, Java, MATLAB. Milestone 5 then adds in JS, C#/.NET, C, Fortran[77|90|20XX].

I currently have to maintain my own C# bindings for integration into the SED-ML Web Tools, so I'd be happy to have "native" C# support from libCellML. JS is the other obvious one to help make it easier for the various web interfaces that we're working on.

I'd guess we're better off having a single solution that works "ok" for multiple target bindings than a collection of "perfect" language specific bindings? But we also want to make sure the Python bindings are good enough for python developers to use...

**Comment by jonc125** [comment]
I don't think SWIG can do all those languages in any case, can it? Pretty sure Fortran isn't supported, although the SWIG website does mention JS, C# and Octave, remarkably! Though how it can manage to do a runs-in-browser wrapper without cross-compiling the C++ to JS I'm not sure. SWIG does tend to produce less 'natural' wrappers, but is a decent starting point so you at least have something. But if we can do nicer wrappers for key languages without much effort (on the order of a few days) then I think it's worth doing.

**Comment by agarny** [comment]
I am also in favour of trying to get the best binding possible for any given language (or people might simply not bother using it, or very reluctantly; see libSBML with Java people).

**Comment by hsorby** [comment]
I think in the case of Python the bindings can be massaged to a desired outcome.  I think SWIG is the way forward for this project as it can be used to target different languages, I think @nickerso would like to use C# bindings at some point but he can answer that for himself.  I don't believe we need to focus on performance for the bindings so a slightly fatter interface between languages won't be much of a concern.

**Comment by hsorby** [comment]
I think we should have a fairly 1-1 relationship with the C++ header files for the binding and then use the package init file to make it possible to do things like:

```
import libcellml
u = libcellml.Units()
```

I have no problem with doing:

```
from libcellml.units import Units
u = Units()
```

I don't personally find anything wrong with this.  But both ways can be accomodated with maniputlation of the init file (much like what requests does, which is a very good Python library).  So in this case I think we can have the best of both worlds.

**Comment by MichaelClerx** [comment]
Agreed that the Python case is definitely solvable :-)

**Comment by hsorby** [comment]
As to the camelCase vs. snake_case argument I'm easy.  The guidelines do mention that if the project is from a C++ background camelCase is acceptable.  Having said that I'm not against working on a way that will convert the C++ camelCase to snake_case, I don't think this will be a big task.

I'm from a C++ background so tend to revert to camelCase naturally.

**Comment by MichaelClerx** [comment]
> As to the camelCase vs. snake_case argument I'm easy. 

Same here!

If it can be done automatically then sure, but as you say, camelCase is acceptable for a package that's obviously a wrapper around C++ (like PyQt).

**Comment by hsorby** [comment]
I think we should go for the option that we think will get the best take up and make libcellml easy to use, I just don't know which this is! 

I think I would lean towards snake_case if I could generate the change from the C++ header files and avoid having to manually manipulate the change.  But as the API should be fairly small I think this could be manually done without causing stomach ulcers.

**Comment by MichaelClerx** [comment]
Minor detail, but we'd have to trigger the change from the Python-specific SWIG files (or with a switch in the generic SWIG files) right?  Because the Java bindings for example would be camelCased.

Thinking about the other languages, does the current directory structure `src/bindings/language` make sense for all languages? I'm finding it a bit odd to look for my Python files in `build/src/bindings/python` (but not very familiar with the cmake/swig combo so happy to accept that's just me!)

**Comment by hsorby** [comment]
My intention with the layout is to get all the SWIG interface files into one location which is nice and reusable.  Don't forget that you can do conditional includes on target language so doing something just for Python isn't a problem.

http://www.swig.org/Doc1.3/Preprocessor.html#Preprocessor_condition_compilation

**Comment by MichaelClerx** [comment]
PR is ready!

**Comment by MichaelClerx** [comment]
Pfffft. Tests runs fine on my machine (Fedora), but fail for the PR. Anyone here running OS/X, Windows or Ubuntu 14?

**Comment by MichaelClerx** [comment]
@hsorby @nickerso et al., how do I go about finding the SWIG versions etc. installed on each of these machines?

I've been using SWIG `3.0.12` and GCC `7.1.1` to compile

**Comment by agarny** [comment]
I am running macOS 10.12, Windows 10 and Ubuntu 16.04. Let me know if you would like me to test anything specific.

**Comment by nickerso** [comment]
I've just been trying to build your branch @MichaelClerx and its not even trying to build the bindings. I have SWIG available, and the only thing I can see that is obviously missing is the `PYTHON_LIBRARY_DEBUG` and I'm trying to build a debug version of libCellML. Is that something I need to have or just an indication that something else has gone wrong with the configuration?

**Comment by hsorby** [comment]
@MichaelClerx if you go to the waterfall page on the Buildbot (which you can get to from the details link from the failed test notification):

http://autotest.bioeng.auckland.ac.nz/libcellml-buildbot/waterfall

you can look at the `stdio` log of the configure step.  The information that you are looking for is in there.

**Comment by MichaelClerx** [comment]
@agarny could you have a look and see if the branch compiles and the tests run on your ubuntu machine?

**Comment by MichaelClerx** [comment]
@nickerso I've no idea what you mean, sorry!
Is `PYTHON_LIBRARY_DEBUG` a CMAKE thing?

**Comment by agarny** [comment]
> @agarny could you have a look and see if the branch compiles and the tests run on your ubuntu machine?

It's all working fine for me. Here is what I did:
 - Clone https://github.com/MichaelClerx/libcellml.git;
 - Check out your issue161 branch;
 - Configure libCellML using the default settings;
 - Build libCellML; and
 - Run the tests.

**Comment by MichaelClerx** [comment]
Thanks! Seems it's only 14.04 with issues then... How do I go about finding out which SWIG version etc. is uses?

**Comment by agarny** [comment]
I guess you could temporarily tweak the main `CMakeLists.txt` file to show the SWIG version on Ubuntu 14.04?...

**Comment by MichaelClerx** [comment]
https://packages.ubuntu.com/trusty/swig

Says here it's 2.0.11, which is a shame as we're up to 3.0.12 now. I suppose it's a requirement that the code can be compiled on Ubuntu 14.04 without updates?

**Comment by agarny** [comment]
Personally, I would support the latest LTS (i.e. 16.04 at the moment) and that is it, which means that I would indeed update 14.04. I don't have access to that machine myself, but hopefully @hsorby does and he can update the version of SWIG on that machine.

**Comment by MichaelClerx** [comment]
One of the key elements of Swig 3.0.0 is that it adds C++11 support, so it might not be possible at all to do the bindings on 2.0 (since it won't be able to analyse the C++ code, regardless of how we write the interface).

**Comment by MichaelClerx** [comment]
Ok, can now confirm that if we leave the offending bits out of the interface files, swig instead starts complaining about the C++ header files themselves (it doesn't understand the syntax).

**Comment by MichaelClerx** [comment]
From the Ubuntu machine's cmake logs:

    -- Found SWIG: /usr/bin/swig2.0 (found version "2.0.11") 

OS/X:

    -- Found SWIG: /usr/local/bin/swig (found version "3.0.12")

Windows:

    -- Found SWIG: C:/swigwin-3.0.12/swig.exe (found version "3.0.12")

So we know why the Ubuntu build fails so quickly, but still a mystery about the windows one!

**Comment by MichaelClerx** [comment]
Fixed the windows warnings, now trying to find out what these guys mean:

    "D:\ALL_BUILD.vcxproj" (default target) (1) ->
    "D:\src\bindings\python\_variable.vcxproj" (default target) (20) ->
      variablePYTHON_wrap.obj : error LNK2019: unresolved external symbol __imp__invalid_parameter_noinfo_noreturn referenced in function "public: char const & __cdecl std::_String_const_iterator<class std::_String_val<struct std::_Simple_types<char> > >::operator*(void)const " (??D?$_String_const_iterator@V?$_String_val@U?$_Simple_types@D@std@@@std@@@std@@QEBAAEBDXZ) [D:\src\bindings\python\_variable.vcxproj]
      D:\src\bindings\python\Debug\_variable.pyd : fatal error LNK1120: 1 unresolved externals [D:\src\bindings\python\_variable.vcxproj]

where I replaced `D:\buildslave_libcellml\Unit_Tests_Builder_Windows_8_64_Bit\libcellml-build` with `D:` for clarity

**Comment by MichaelClerx** [comment]
Something to do with the linked python binaries?

http://swig.10945.n7.nabble.com/link-error-in-debug-mode-td1247.html

**Comment by agarny** [comment]
Yes, it looks like you might not be linking some Python library. @dbrnz?

**Comment by MichaelClerx** [comment]
There are some lines in CMakeLists for the bindings for this, which @hsorby added originally:

https://github.com/cellml/libcellml/pull/205/commits/bb08e2fb50f06bf1bd605b84f708b81c7fa13453

I added a check (see above) and it seems that the windows machine definitely  doesn't have the Python debug libraries (+ the detection works). However, the fix doesn't work! Maybe the machine has no Python libraries at all?

**Comment by agarny** [comment]
Something for @hsorby to confirm and for @dbrnz to give us more insight, if needed.

**Comment by MichaelClerx** [comment]
On Ubuntu 14, it should be possible to install swig 3.0 with just `sudo apt-get install swig3.0`

**Comment by hsorby** [comment]
I have updated the SWIG on Ubuntu 14.04.  If this version fails I will shift the libcellml build to the Ubuntu 16.04 machine.

**Comment by hsorby** [comment]
I have tested on my own windows 10 machine and have found that:

With Python 2.7 without debug python libraries

- everything builds fine with no errors or warnings.
- one test fails (python_test_units) due to attempt to dereference a map/set iterator.

With Python 3.5 with debug python libraries

- everything builds fine with no errors or warnings.
- all the python tests fail because a dll load failed.

**Comment by hsorby** [comment]
It turns out that the CMake FindPythonInterp module does not find the debug python executable on windows (or on any platform actually).  This means the python tests linked to the debug python libraries will never run when they try to use the release version of the python interpreter.

**Comment by MichaelClerx** [comment]
When would you use a special debug executable for Python?

Is this related? https://cmake.org/cmake/help/v3.0/module/FindPythonLibs.html (see deprecation notice for DEBUG_LIBS)

**Comment by MichaelClerx** [comment]
The Ubuntu machine can compile now, but the tests all fail due to a change between SWIG versions 3.0.2 (used on our machine) and 3.0.3 (released in december 2014).

I can think of a workaround, or we can just set the minimum version to 3.0.3 and update the machine... @hsorby ?

**Comment by hsorby** [comment]
You use the debug version of the executable when you want to debug :).  In our case you would use it when you want to debug through the bindings.

No this is nothing to do with the Python libraries, those are found and used correctly it is the Python interpreter that is not working for us.

I think the workaround is to move the libcellml build to Ubuntu 16.04 and set that as the minimum version required for building libcellml.  It is generally not easy to install packages that are not in the database and certainly not helpful for us to tell users that they need this particular package from an external source.  Better just to upgrade the minimum version of Ubuntu I think.

**Comment by hsorby** [comment]
Sadly Ubuntu 14.04 is due to be supported right up until April 2019 which is a bit of a bummer, but oh well can't win them all.

https://www.ubuntu.com/info/release-end-of-life

**Comment by MichaelClerx** [comment]
Well, SWIG 3.0.2 converts enums such as `enumerations.Format.XML` to `enumerations.XML`, while later versions (starting at 3.0.3 I think) use `enumerations.Format_XML`. I can work around this by checking in the Python `__init__` which constants exist and then renaming accordingly (I already do this to convert `Format_XML` to `Format.XML` for consistency with the C++ code and neater namespacing).

It wouldn't be perfect, because we still couldn't have A.X and B.X (since they'd both become X), but it would _probably_ be ok.

Another option would be to stop using `class enums` altogether because they create more issues for the bindings elsewhere... (I'm usually a big fan of enums, esp. the way Java has them, but they're a feature that vary a lot from language to language, so...)

**Comment by hsorby** [comment]
If we do follow up the idea of removing the enumerations.h header and pushing enumerations elsewhere this wouldn't then apply to us? All enumerations would be namespaced.

**Comment by MichaelClerx** [comment]
No as long as they're `class enums` SWIGs behaviour will differ between version 3.0.2 and version 3.0.3 in the way described above.

For example `Units.StandardUnit.AMPERE` (C++) would become `Units.AMPERE` (Python, SWIG 3.0.2) and `Units.StandardUnit_AMPERE` (Python, SWIG 3.0.3+)

**Comment by MichaelClerx** [comment]
And the problems with languages that don't have typed enums will also persist as long as we use them

(Python can't distinguish an enum from an int, so if you have an overloaded method x(StandardUnit) and x(int) we can only make one of those methods available to the Python users)

**Comment by hsorby** [comment]
There has been some discussion around this `int` for `enum` or rather `std::string` for `enum`.  It could well be that if we are using enumerations then that is the only option available through the API this would tidy up the conversion a little.

We can write some tests and see what it looks like then decide which style is preferred.  I don't think there would be an issues around moving to a strictly no overloaded enumeration API.

**Comment by MichaelClerx** [comment]
I came across this yesterday: https://www.softwariness.com/articles/api-design-for-swig/

Seems like we're on the right track

**Comment by MichaelClerx** [comment]
Ok, workaround for SWIG 3.0.2 seems to work, but now there's a segfault in there somewhere! Possibly still because of the lack of enum class support? Ran tests plenty of time locally and never had a segfault...

@hsorby Any luck on the windows front?

**Comment by MichaelClerx** [comment]
Need to move this forward!

I can try finding an Ubuntu 14.04 machine and seeing if I get the same segfault as our test machine. If so I can start debugging. (Since it's a segfault, I'm guessing its a C++ issue or a C++/Python issue that, for whatever reason, reliably surfaces on Ubuntu 14.04. Could also just be a swig bug though, in which case we'll just need to update to Ubuntu 16).

But not sure I could find a windows machine, install VB and debug it!

Thoughts? @hsorby @agarny @nickerso @jonc125 ?

If people want to review this PR they can start before we fix the final bugs :-)

**Comment by hsorby** [comment]
I'll try and get around to looking at this later today.

**Comment by agarny** [comment]
My take on this: I would simply upgrade to Ubuntu 16.04 LTS.

**Comment by MichaelClerx** [comment]
Just tested on another machine to double check: It compiles and passes all tests on Ubuntu 16.04 LTS!

**Comment by MichaelClerx** [comment]
And tested on a virtual machine with Ubuntu 14.04 LTS --> Get the same SEGFAULT! An update definitely seems in order!

**Comment by MichaelClerx** [comment]
Thanks to @hsorby 's work the segfaults are fixed (I also discovered you could create them on Fedora, but those are fixed too!).

Now it's only the windows linking issue that's stopping this from passing all tests!

**Comment by MichaelClerx** [comment]
@agarny @nickerso Anyone good at fixing windows issues?

**Comment by hsorby** [comment]
I can have a look at this I have a windows machine somewhere.

**Comment by agarny** [comment]
A couple of links (which I hope are correct) to help those who want/need to know more about the issues at hand (it would be nice if such links were always provided: makes it easier to check things, if needed/wanted):

> Thanks to @hsorby 's work the segfaults are fixed (I also discovered you could create them on Fedora, but those are fixed too!).

Does this refer to commit 4b9a7b5?

> @agarny @nickerso Anyone good at fixing windows issues?

I imagine you are talking about 
http://autotest.bioeng.auckland.ac.nz/libcellml-buildbot/builders/Unit%20Tests%20Builder%20Windows%208%2064%20Bit/builds/546/steps/compile/logs/stdio?

Regarding the Windows build, I tried to build libCellML on my Windows machine, but among the required libraries, I was missing `libxml2`. From http://xmlsoft.org/, I thought I could get some from https://www.zlatkovic.com/libxml.en.html, but unless I am mistaken they are for MinGW. So, I ended up using the version provided by the libSBML guys (a copy of which can be found [here](https://github.com/opencor/libsbml/releases/tag/v5.15.0)), but to no avail since when building the `develop` branch of libCellML, I am getting loads of `unresolved external symbol` errors at link time.

Still, a quick search for `__imp__invalid_parameter_noinfo_noreturn` gave me [this ](https://github.com/commontk/PythonQt/issues/9#issuecomment-18503576), which might be worth investigating. I mean, I get the feeling that it might be somewhat related to @hsorby's work in commit 4b9a7b5?

Otherwise, with regards to my `libxml2` issue, I checked http://libcellml.readthedocs.io/en/latest/dev_building.html and that made me think that I wish we had a section on prerequisites to build libCellML. That section would mention where we can get those prerequisites. This would potentially save people time...

**Comment by hsorby** [comment]
I have used the libxml2 library available from:

https://github.com/OpenCMISS-Dependencies/libxml2/

using the `develop` branch.  Thinking about it now I must have some changes pending from my Windows machine to make integration with libCellML easier.  I spoke with @nickerso about this and thought we should probably provide binaries so that people may use them easily.

You are correct we should have some notes on pre-requisites like this time for another issue!

**Comment by MichaelClerx** [comment]
@agarny yes https://github.com/cellml/libcellml/pull/205/commits/2b8b02041f184d8a1a1f2359ee053cdecae6ceed but also https://github.com/cellml/libcellml/pull/205/commits/c3066d03b0458b1850b1c422a53ce1af23bb5e13 which solves the same issue but for the other enums.

And yes it was the windows build for this ticket's PR I was talking about. I completely agree a `requirements` file is a good idea!

**Comment by MichaelClerx** [comment]
*bump*

**Comment by hsorby** [comment]
I have had a look at the Windows non-linking issue and when I tested on the machine it linked fine.  I might look at moving the build slave to use Visual Studio 2015 it is currently using Visual Studio 2013.  This will hopefully resolve this issue.

**Comment by MichaelClerx** [comment]
Brilliant, thanks!

**Comment by hsorby** [comment]
I think the reason for the non-linking issue is due to a mismatch between building debug libCellML libraries and release Python libraries.  This on Windows has previously been a problem but was addressed with the release of the universal C runtime libraries.  My thinking is that this was done post-Visual Studio 2013 (I have absolutely no evidence of this) and thus VS 2103 is using the old C runtime libraries which had to be matched.  Changing to VS 2015 which links through the UCRT is probably the reason why upgrading fixes this linking issue.

**Comment by MichaelClerx** [comment]
Sounds plausible! Microsoft has done a lot of Python work recently. Is there a way to manually restart the buildbot tests. or should we do a trivial commit?

**Comment by hsorby** [comment]
You can re-trigger a message by re-sending a webhook, but don't do it just yet I'm still testing.  I'll let you know when I'm done.

**Comment by hsorby** [comment]
I have updated the build slave to use VS 2015 so if someone with the power would like to resend the appropriate payload we can see if I have fixed the linking issue or created a new one.

**Comment by MichaelClerx** [comment]
Great! It compiles without warnings or errors now! Thanks!

It doesn't pass any of the tests though, because `Test command: NOT_AVAILABLE`. Any idea what that is? Python executable not on the path or something?

**Comment by MichaelClerx** [comment]
Some related issues I'm finding online suggest it could be because we need to specify a release or debug mode? "You should run "ctest -C Debug -V -R itkBMKTestIOTest5" if you compiled in Debug mode and "ctest -C Release -V -R itkBMKTestIOTest5" if you compiled in Release mode." ?

**Comment by MichaelClerx** [comment]
Someone else had an issue with `CMAKE_CONFIGURATION_TYPES`; https://github.com/osmcode/libosmium/issues/77

**Comment by MichaelClerx** [comment]
Here's another one pointing towards build types: https://issues.slicer.org/view.php?id=2347

**Comment by MichaelClerx** [comment]
I don't know enough about cmake for this! @hsorby ? @agarny ?

**Comment by agarny** [comment]
I have never used CTest, so not quite sure what to suggest here. Will have a quick look though...

**Comment by hsorby** [comment]
I know what this is I need to make more changes to the Buildbot configuration files.  I'll let you know when this is done so that it can be tested.

**Comment by hsorby** [comment]
No I was wrong the fix for this should come from the CMake files in libCellML.  I will try and address this through #217.

**Comment by hsorby** [comment]
I think we should remove the \_\_init__.i file as this is specific to Python and have a \_\_init__.py file that can be configured over to the correct build location instead.

**Comment by MichaelClerx** [comment]
It's already specific to Python --> It's placed in the `bindings/python` dir and only used when generating python bindings!

**Comment by MichaelClerx** [comment]
Any news on this or #217 ?

**Comment by MichaelClerx** [comment]
Any updates on this or #217 ?

**Comment by nickerso** [comment]
ping @hsorby

**Comment by MichaelClerx** [comment]
Hi all! I think it's best to wait till the libxml updates are merged with master, and then rebase this branch (so that it benefits from the new code).

Happy to do that if noone objects.
