### ISSUE TITLE
Does componentCount() include imported components?

### ISSUE THREAD

**Issue by nickerso** [cellml/libcellml#162]
The documentation seems to indicate that the `componentCount()` method for the `ComponenentEntity` class will not include imported components. I'm not sure why not and the implementation seems to not match that behaviour.

I'll add some tests to see if we agree on what should be happening.

**Comment by hsorby** [comment]
I think the documentation is incorrect here we should be counting all components in the model.

**Comment by nickerso** [comment]
That is what the current implementation is doing. #163 adds some tests to demonstrate this.
