### ISSUE TITLE
Have a way to uninstall libCellML

### ISSUE THREAD

**Issue by agarny** [cellml/libcellml#181]
I can build and install libCellML just fine, but in some cases it would be nice to also be able to uninstall it. So, it would be nice to be able to do something like `make uninstall` in the same way that we can do `make install`.

**Comment by hsorby** [comment]
I think it is quite easy to do with CMake there is already a manifest of what was installed so I think you can just read this manifest and remove the files recorded there.

**Comment by agarny** [comment]
Ok, I will have a quick look at it and see whether I can get anywhere with it.

**Comment by hsorby** [comment]
I think all you need to do is follow the instructions here:

https://cmake.org/Wiki/CMake_FAQ#Can_I_do_.22make_uninstall.22_with_CMake.3F

**Comment by agarny** [comment]
Yes, I was just about to look for something like this, so thanks a lot for the head start.
