### ISSUE TITLE
Unexpected CMake variable override

### ISSUE THREAD

**Issue by agarny** [cellml/libcellml#182]
If I first configure CMake, I get:

```
 LIBCELLML_BUILD_SHARED          *ON                                                                                                                                                                  
 LIBCELLML_BUILD_TYPE            *Debug                                                                                                                                                               
 LIBCELLML_COVERAGE              *ON                                                                                                                                                                  
 LIBCELLML_INSTALL_PREFIX        */usr/local                                                                                                                                                          
 LIBCELLML_TREAT_WARNINGS_AS_ER  *ON                                                                                                                                                                  
 LIBCELLML_UNIT_TESTS            *ON                                                                                                                                                                  
```

Now, if I change the value of `LIBCELLML_BUILD_TYPE` to `Release` and configure again, I now get:

```
 LIBCELLML_BUILD_SHARED           ON                                                                                                                                                                  
 LIBCELLML_BUILD_TYPE             Debug                                                                                                                                                               
 LIBCELLML_COVERAGE               ON                                                                                                                                                                  
 LIBCELLML_INSTALL_PREFIX         /usr/local                                                                                                                                                          
 LIBCELLML_TREAT_WARNINGS_AS_ER   ON                                                                                                                                                                  
 LIBCELLML_UNIT_TESTS             ON                                                                                                                                                                  
```

In other words, `LIBCELLML_BUILD_TYPE` gets automatically reset to `Debug`, which is not what I expected.

Looking at the [main `CMakeLists.txt`](https://github.com/cellml/libcellml/blob/07120c31dd6622fc442c505aa95510148df78498/CMakeLists.txt), I can see that both `LIBCELLML_UNIT_TESTS` and `LIBCELLML_BUILD_TYPE` get overridden if either `LIBCELLML_COVERAGE` or `LIBCELLML_MEMCHECK` is `ON` (see [here](https://github.com/cellml/libcellml/blob/07120c31dd6622fc442c505aa95510148df78498/CMakeLists.txt#L59) and [here](https://github.com/cellml/libcellml/blob/07120c31dd6622fc442c505aa95510148df78498/CMakeLists.txt#L76), respectively).

Why does unit testing depend on the value of coverage or memory check? When it comes to the build type, I imagine that coverage and memory check require the build type to be debug? If so, I would rather check the value of `LIBCELLML_BUILD_TYPE` and if it is set to `Release` then set `LIBCELLML_UNIT_TESTS`, `LIBCELLML_COVERAGE` and `LIBCELLML_MEMCHECK` to `OFF`, if anything.

**Note:** why isn't `LIBCELLML_MEMCHECK` listed in the CMake configuration?

**Comment by hsorby** [comment]
This is a decision between who stomps who.

As for the unit testing depending on coverage or memory check it is the other way around you cannot have coverage or memory checking without the unit tests being available.

You will only see `LIBCELLML_MEMCHECK` if you have valgrind available.

**Comment by hsorby** [comment]
We should probably issue a configuration error when this situation happens rather than forcing the change?

**Comment by agarny** [comment]
> This is a decision between who stomps who.

Sure, but when it comes to `LIBCELLML_BUILD_TYPE`, I would expect it to have precedence over `LIBCELLML_COVERAGE` and `LIBCELLML_MEMCHECK`.

> As for the unit testing depending on coverage or memory check it is the other way around you cannot have coverage or memory checking without the unit tests being available.

Ok.

> You will only see `LIBCELLML_MEMCHECK` if you have valgrind available.

Oops, of course!

> We should probably issue a configuration error when this situation happens rather than forcing the change?

I would probably have a mix of our suggestions:
 - If `LIBCELLML_BUILD_TYPE` is set to `Release` then both `LIBCELLML_COVERAGE` and `LIBCELLML_MEMCHECK` get set to `OFF` and a message is displayed to the user.
 - If `LIBCELLML_UNIT_TESTS` is set to `OFF`, but `LIBCELLML_COVERAGE` and/or `LIBCELLML_MEMCHECK` are set to `ON`, then force `LIBCELLML_UNIT_TESTS` to `ON` and display a message to the user.

**Comment by nickerso** [comment]
In my experience messages are ignored unless the developer is forced to look at them :) And I don't think we should be changing settings automagickly. I'd suggest raising an error if conflicting settings are detected - as long as a suitable error message is presented to the developer (essentially as described by @agarny above) then it should be a quick fix to get a non-conflicting build configured.
