### ISSUE TITLE
Is the `ImportedEntity` really an `ImportableEntity` ?

### ISSUE THREAD

**Issue by MichaelClerx** [cellml/libcellml#187]
Should we rename it?

**Comment by agarny** [comment]
I would personally leave it as it is, although I agree that a component/unit is effectively an importable entity. However, if you think of `NamedEntity`, then it makes sense to have `ImportedEntity` since the latter class defines what you need to be importable (in the same way that `NamedEntity` defines what you need to have an entity with a name). Am I making sense? :)

**Comment by MichaelClerx** [comment]
Would it not make more sense if an ImportedEntity was an entity that was imported?

Not sure about NamedEntity, is that guaranteed to have a name (or only valid if it does)?

**Comment by nickerso** [comment]
+1 to keeping current names.

**Comment by MichaelClerx** [comment]
Great! But give us a why though.

The last cellml lasted ten years. Refactoring is twenty minutes max. Let's do this right.

**Comment by hsorby** [comment]
I think it should stay as ImportedEntity it is what it is, it is not an action or event that the object does.

**Comment by nickerso** [comment]
Agree its good to make sure we have the best API we can :) I agree with @hsorby's comment above - an ImportedEntity is an entity that can be imported, as a NamedEntity is an entity which can be named. Whether a NamedEntity *must* have a name (or an ImportedEntity must be imported) is a validation task based on the specification.

**Comment by MichaelClerx** [comment]
A PaintedCar is a car that may or may not have been painted? Really struggling to see how this makes sense.

The doc string says: "Base class for all importable entities"
https://github.com/cellml/libcellml/blob/develop/src/api/libcellml/importedentity.h#L30

Then the method `isImport` has the docstring: "Test if this entity is an imported entity." --> So we need to ask the `ImportedEntity` if it is an imported `Entity`.

There's also a class `Import`, which is **not** what `isImport` checks for

`getImport`, according to the docs, return an "import set", whatever that is, while `setImport` "sets the import"

We really need to make this clearer with better naming and documentation. It's not at all obvious from the header & docstrings what is going on here.

I really think this should be the number 1 priority for libcellml right now. Any issues with implementation (bugs) or performance can still be handled after the first release, the API & docs are fixed, and are the first thing (and ideally the only thing) that users will see of this project.

**Comment by hsorby** [comment]
Yes we do ask if an object that has the ability to be imported is actually imported I don't have any problems with this.

I think a better car analogy is an ImportedCar a car that may have been imported.  Which we can test with isImport().

**Comment by hsorby** [comment]
Yes I agree with the setImport and getImport which could be much clearer.  That would probably be my documentation style, it makes sense in my head.

**Comment by MichaelClerx** [comment]
Alright 3-1 vote will close this for now
