### ISSUE TITLE
`import` is a keyword in Python

### ISSUE THREAD

**Issue by MichaelClerx** [cellml/libcellml#189]
Hi all!

We have a class `Import` that encapsulates imported models (or at least models of which a component or unit is imported, is that right?).

With the current swig implmentation this means creating a module `import` for the class `Import` to live in, which is not allowed as `import` is a keyword.

Three questions for discussion:

1. Does anyone have a strong opinion on what I should call the `import` module instead?
2. Should this fix be restricted to the Python bindings?
3. What will be our general strategy for these problems. Try to choose the C++-classes so that we never have this problem OR create small differences in the generated wrappers to work around these issues?

**Comment by hsorby** [comment]
Off the top of my head I can't think of any other class names that would clash with a keyword or reserved word in another language.

I would prefer to rename the `Import` class.  We are going to have to rename it for Python so if the new name is good enough for Python could it not also be good enough for C++.

**Comment by MichaelClerx** [comment]
Any ideas @agarny @nickerso ?

**Comment by MichaelClerx** [comment]
External model? Source?

A good choice would also fix #188, I suppose :-)

**Comment by nickerso** [comment]
This is now reminding me why the CellML API has a mix of `CellML*` objects and non-`CellML*` objects :)

I agree that it would be best to rename `Import`. Some alternatives off the top of my head in order of my preference: `ImportSource`, `ModelReference`, `ModelSource`, `_I__mp_Or_t____`

**Comment by MichaelClerx** [comment]
I like `_I__mp_Or_t____` but only if we rename the library `libce1lm1`

**Comment by hsorby** [comment]
Sorry I can't have that I already have a project called `l1bcellml`, `libce1lm1` is too close I would have to call in the trademark lawyers.

**Comment by hsorby** [comment]
`ImportSource` for me.

**Comment by agarny** [comment]
`ImportSource` for me too.

**Comment by MichaelClerx** [comment]
+1

**Comment by MichaelClerx** [comment]
I could do a pull request but might easier for someone with a nice C++ IDE :-D

**Comment by agarny** [comment]
A PR would still be required, but I am happy to do it.
