### ISSUE TITLE
CMake option `LIBCELLML_UNIT_TESTS` can't be switched off

### ISSUE THREAD

**Issue by MichaelClerx** [cellml/libcellml#192]
If I go into ccmake, toggle `LIBCELLML_UNIT_TESTS` to `OFF` and hit `c` for configure, the option gets turned on again!

**Comment by agarny** [comment]
I haven't checked it, but I would guess that it is related to issue #182, which needs to be addressed.

**Comment by MichaelClerx** [comment]
Ah. Switching off `COVERAGE` and `MEMCHECK` lets me disable it! (Although then make has errors)

**Comment by MichaelClerx** [comment]
Marking as duplicate of #182

**Comment by MichaelClerx** [comment]
Duplicate of #182
