### ISSUE TITLE
How do we know what `Entity --> void *getParent()` returns?

### ISSUE THREAD

**Issue by MichaelClerx** [cellml/libcellml#193]
Hi all!

Trying to wrap this method. What's the proposed mechanism for knowing what type is actually returned here? Should I just know from the context? Or use dynamic casts and try-catch? Why is it a `void*` anyway and not an `Entity*` or `ComponentEntity*` ?

**Comment by hsorby** [comment]
It  does make me wonder now why it is that way.  I can't remember what the reason was, if there was one.  

If changing to `ComponentEntity *` works, i.e. all the tests still pass I can give no reason against making the change.

**Comment by MichaelClerx** [comment]
It seems that in the Python bindings I'll need to add some wrapper code that checks if it's a model or a component and returns the appropriate type. How would I go about that, from the C++ point of view?

**Comment by agarny** [comment]
If I understood you right, you could do something like:

```
MyExpectedType *myExpectedObject = dynamic_cast<MyExpectedType *>(myOriginalObject);

if (myExpectedObject) {
    // Do whatever...
}
```

**Comment by MichaelClerx** [comment]
It's more that, from Entity, I don't know what to expect! This is an issue since SWIG needs to convert the `void*` to whatever's appropriate in the language (so in Python either a Model or a Component object).

One option would be to hide the Entity.getParent() method in Python and instead have separate methods `Model.getParent()` --> NoneType` and `Component.getParent() --> Model` and `Variable.getParent() --> Component` ?

**Comment by nickerso** [comment]
just a quick note that `Component::getParent` could return either a model or a component - which I'd guess is why @hsorby suggested you want to return a `ComponentEntity`, which would also work for variables...

**Comment by MichaelClerx** [comment]
Yup! But I need to find out which one so I can convert it to a Python (or java etc.) object :-)

It could just be a raw `ComponentEntity`, that would pass all the tests but usually I guess you'd want to hide these underlying types from the users and just use them to avoid duplicate implementation?

**Comment by agarny** [comment]
I just had a quick look and, personally, I would probably remove the `setParent()`, `getParent()`, `clearParent()` and `hasParent()` methods from the `Entity` class, and have those methods in both the `Component` and `Variable` classes. To have anything else would probably result in the C++ and Python bindings having to be different, and I don't think we want that (e.g. I don't think we want to hide `Entity::getParent()` and have separate `Component::getParent()` and `Variable::getParent()`.

**Comment by MichaelClerx** [comment]
+1

**Comment by MichaelClerx** [comment]
*bump*

**Comment by kerimoyle** [comment]
Resolved by https://github.com/cellml/libcellml/pull/322 ?

**Comment by MichaelClerx** [comment]
Looks like it!

**Comment by agarny** [comment]
Looks like it to me too. Happy for @MichaelClerx to close this issue then.
