### ISSUE TITLE
Bindings: Empty strings as arguments and return types

### ISSUE THREAD

**Issue by MichaelClerx** [cellml/libcellml#194]
A few methods, such as `Import.getSource() --> String` or `Import.setSource(String source)` take string arguments or return strings.

At the moment, calling `getImport()` on an `Import` without a source set returns an empty string. Similarly, a null ptr can't be passed to `setImport` to clear it, you need to pass an empty string.

This is creating a (small) issue for the bindings. For example, in Python you'd treat an empty string as distinct from no value at all (represented by `None`). In javascript you can use both `null` and `undefined`, depending on who you ask. In Java you might return `null`.

Two questions:

1. What's the modern hip C++11 way of indicating a string value isn't set?
2. If the answer is "empty string", should we keep this behavior in the bindings? Or write little conversions around these methods?

**Comment by nickerso** [comment]
not sure how hip it is, but I'm happy with using empty strings across all language interfaces to indicate an "unset" property. Not sure that we ever need to deal with a distinction between empty and unset.

**Comment by MichaelClerx** [comment]
I've been reading up about the C++ debate about this! It's quite interesting for such a small problem.

I think the general consensus for C++ is that you return `null` if the return type is a pointer (like we do with `getParent()` for example), but a special value if it's a simple type (empty string, -1 for something that cannot be negative, etc.). Not sure what you do when returning a float that can be any value!

In Python, everything is a reference, so this rule doesn't work. An int in Python is a reference to an int object, so it can always be None instead. An advantage here is that you have 1 way and 1 way only to return "no value", and this method doesn't depend on the context (object / primitive-with-special-value / primitive-without-special-value).

So I think the empty string works naturally for C++ but not "across all language interfaces"

(All of this matters because of what @agarny said about the SBML java interface. Checking for an empty string (or perhaps a -1 int) doesn't feel right in Python (or java or javascript), for me (have checked with some other devs too))

**Comment by agarny** [comment]
I guess I must have missed something. I mean what is 'wrong' with using an empty string to indicate that something is not set? I appreciate that it's not the 'correct' way of doing it in Python, but it still ought to work, no?

**Comment by MichaelClerx** [comment]
Definitely works yeah. Just not what Python users would expect. So now I'm wondering whether to

1. just leave it and document it
2. add Python-specific code to convert None to '' and '' to None
3. only add Python-specific code to convert None to '' on input
4. do something better that will also fix this for Java etc.?

All of these work but I'm not 100% sure what's best, that's why I'm bringing it up.

**Comment by agarny** [comment]
Ok, then I guess it's really something for other Python users to comment on. @metatoaster, @jonc125, @hsorby?

**Comment by jonc125** [comment]
I'd agree with using `None` for the null pointer case. For the unset import, I think we picked empty string because it fit semantically - if you don't have a URL for the import that shouldn't be treated differently from having an empty URL. So using an empty string for the Python bindings too is fine by me.

**Comment by hsorby** [comment]
I would expect all of the following to work from Python:

```
import.setImport()
import.setImport(None)
import.setImport('')
```
If that means we have to do a bit of work in the interface then that is what we will do.

I don't mind what it returns either `''` or 'None' both result in False when tested we just need to be consistent throughout.  I would be prefer receiving an empty string from the get methods.

I agree with @jonc125 we decided that the empty string in C++ was the best fit, I did argue this point in the early part of this project and I don't see anything that changes the outcome of this argument.

**Comment by metatoaster** [comment]
If it is a null pointing, map it to `None`, as that can be tested (using `is None`). If it is truly an empty string then return an empty string.  Honestly though, I very much dislike get/set methods because they can be abstracted away using properties in Python (never mind that they are not idiomatic in Python), so getting the value is simply reading the property attribute which would access the getter, and setting it will simply call the setter.

In this case, I don't mind setting it to an empty string to clear the import, though a helper that translates None to empty string will help, and vice versa when accessing the getter.  Though keeping everything as a consistent type and document it (i.e. only strings are accepted, empty strings means no imports) it will result in a more straightforward API that is less prone to errors.  As mentioned, a higher level API implemented within the language that uses libcellml as the underlying layer will probably be more useful, and this was something I've done already for the CellML API already.

**Comment by MichaelClerx** [comment]
Null pointers are already automatically mapped to `None` by SWIG, and vice versa. I'll look into converting `None` to ` '' ` for Python specifically.

(For the record, I'm not a fan of APIs pretending get/set methods are properties. If properties are sufficient, use properties, if the methods need to do more make it explicit to the user by writing them as methods.)

@metatoaster can you add a link to your previous stuff? Very interested to see what you did

(Although I'm a bit anxious about having a wrapper around a wrapper that talks to generated proxies to access a shared library, just to read an xml file :-D  )

**Comment by jonc125** [comment]
While I agree about wrapping get/set by properties for pure Python code, when wrapping a C++ library it does make the interface look more like Python if you do so. How easy it is depends on how naturally the library's memory management matches Python's reference counting approach... Also I think most of our get/set methods are getting an object from a collection by name, or setting by name, so map more to the dict interface than anything else! But given you can get/set/take different kinds of objects from the collections, it's probably least confusion to stick with the C++ method names.

**Comment by metatoaster** [comment]
It is at https://github.com/PMR2/cellml.api.pmr2.  There are certain things that I had to workaround such as loading of http(s) imports, amongst other things.

**Comment by MichaelClerx** [comment]
Empty strings it is
