### ISSUE TITLE
Equality checks on entities?

### ISSUE THREAD

**Issue by MichaelClerx** [cellml/libcellml#196]
At the moment, there don't seem to be any equality checks defined for the basic entities.

So if I do:

```
x = Component()
y =  Component()
x.addComponent(y)
z = x.getComponent(y)
```

I have no way of checking if `y` and `z` are the same (esp. in the bindings, where `z` is a proxy of a shared_ptr to the object, so no way to check if the memory address is the same)

**Comment by MichaelClerx** [comment]
*bump*! This would make our data model more usable, I think

**Comment by agarny** [comment]
I agree that it would be nice to have.

**Comment by nickerso** [comment]
I can't think of a reason not to have that, just need the tests to be written and the code to be implemented :)

**Comment by MichaelClerx** [comment]
Ok, I'm trying to gather these kinds of issues under a useful label. Please help me find a better name for it :D

**Comment by agarny** [comment]
> Ok, I'm trying to gather these kinds of issues under a useful label. Please help me find a better name for it :D 

I would simply use `Feature` or `Improvement`.

**Comment by hsorby** [comment]
We now have a method `equals` that will compare the equality of two entities.  Smart pointer comparison is also still an option.
