### ISSUE TITLE
Replace `bool removeComponent()` and `Component takeComponent()` with `Component removeComponent`?

### ISSUE THREAD

**Issue by MichaelClerx** [cellml/libcellml#197]
At the moment, `ComponentEntity` defines both:

    bool removeComponent(size_t index);
    bool removeComponent(const std::string &name, bool searchEncapsulated=true);
    bool removeComponent(const ComponentPtr &component, bool searchEncapsulated=true);

and

    ComponentPtr takeComponent(size_t index);
    ComponentPtr takeComponent(const std::string &name, bool searchEncapsulated=true);

Do we really need two different ways of removing components? Would it not be better just to go with `ComponentPtr removeComponent(...)` ? Been looking at standard libraries and such, but don't see other examples of `takeX` methods

**Comment by hsorby** [comment]
There is clearly a difference between these two sets of methods.  An example of removing and taking can be seen in the Qt codebase.

**Comment by nickerso** [comment]
This looks like its resolved, can be reopened if needed.
