### ISSUE TITLE
Missing method `ComponentEntity.replaceComponent(ComponentPtr, ComponentPtr)`

### ISSUE THREAD

**Issue by MichaelClerx** [cellml/libcellml#198]
We've currently got these two methods:

    bool replaceComponent(size_t index, const ComponentPtr &c);
    bool replaceComponent(const std::string &name, const ComponentPtr &component, bool searchEncapsulated=true);

but no

    bool replaceComponent(const ComponentPtr &component1, const ComponentPtr &component2, bool searchEncapsulated=true);

**Comment by hsorby** [comment]
If you want this method to be added write a test!  It looks like something a library user would want to do.

**Comment by MichaelClerx** [comment]
Have added a pr plus one for another method, would be grateful if someone could take a look and merge!
