### ISSUE TITLE
Add docstrings to the Python bindings

### ISSUE THREAD

**Issue by MichaelClerx** [cellml/libcellml#208]
~~Once we have docstrings (see #207) we could generate Sphinx documentation without too much hassle, and stick it online somewhere.~~

~~Thoughts? @jonc125 @hsorby @agarny @nickerso~~

There doesn't seem to be a way to do this automatically

www.swig.org/Doc1.3/Python.html#Python_nn65

Interfaces to check:

- [x] \_\_init__.py
- [x] Entity
- [x] NamedEntity
- [x] ImportedEntity
- [x] ImportSource
- [x] ComponentEntity
- [x] Component
- [x] Model
- [x] Units
- [x] Variable
- [x] Error
- [x] Logger
- [x] Printer
- [x] Parser
- [x] Validator
- [x] version

**Comment by agarny** [comment]
Yes, it would be nice to be able to do that.

**Comment by nickerso** [comment]
I know with OpenCMISS the doxygen comments from the source (C/C++/Fortran?) somehow end up as docstrings in the python bindings. I'm guessing if this doesn't happen automatically with SWIG then it is probably something extra in the python script that is used to generate the bindings (https://github.com/OpenCMISS/iron/tree/develop/bindings/generate_bindings)....

~~Actually now I'm thinking the above comment really belongs on #207 :)~~

As for this actual issue, I'm not sure how this differs to the current doxygen-generated API documentation? See #41 for where this is currently at. I'm guessing its going to be python specific and in addition to the current C++-derived API docs...which would definitely be good to have.

**Comment by hsorby** [comment]
I came across this:

https://github.com/m7thon/doxy2swig

and thought it might be something we could make use of.

**Comment by MichaelClerx** [comment]
I think it might be a good tactic to start with the script @hsorby linked, run that once and then do the rest by hand. Because there will be some differences between the Python & C++ docstrings @nickerso! For example the C++ signature

    void Units::getAttributes(size_t index, string& a1, string& a2, double& a3, double& a4)

becomes

    list[string, string, double, double] Units::getAttributes(int index)

in Python

**Comment by MichaelClerx** [comment]
Running it once would also remove the complications of having it as a dependency (when most users/developers won't need it)

**Comment by MichaelClerx** [comment]
Since this whole discussion became about docstrings, instead of the docs generated from them, I just switched the topics and first posts around :D :D :D

**Comment by agarny** [comment]
Just wondering: why has this been closed since it has yet to be merged?

**Comment by MichaelClerx** [comment]
@agarny it'll be fixed as soon as the whole binding pr gets merged. But I'll just leave it open if that's the done thing :)

**Comment by agarny** [comment]
Indeed, an issue should remain opened until its corresponding PR has been merged in.

**Comment by MichaelClerx** [comment]
I'm closing this since it's causing confusion
