### ISSUE TITLE
Remove XML format option.

### ISSUE THREAD

**Issue by hsorby** [cellml/libcellml#209]
Adding in the single option of the XML format was a bad idea.  This should be removed.  It was done with the hope that other formats would be possible but that hope was forlorn.  The CellML specification is tied to the XML format so there is no other format possible.

On the plus side it will make using libcellml a little easier, always a silver lining.

**Comment by MichaelClerx** [comment]
https://github.com/cellml/libcellml/pull/210

**Comment by MichaelClerx** [comment]
Do we need a second reviewer for this or can I just merge it in? @hsorby @nickerso ?

**Comment by agarny** [comment]
In theory, we indeed need a first reviewer to agree with a given PR and a second reviewer to also agree with it and then merge it. Neither of those reviewers can, obviously, be the person behind the PR. Now, that's the theory... and maybe we could make exceptions in cases like this one? @hsorby, @nickerso, @jonc125?

**Comment by nickerso** [comment]
Best practice is two reviewers (they don't need to have permission to merge) approve the PR and then it can be merged. But I think its fine for "trivial" PRs to be merged after a singe review. The main thing is that the PR author(s) shouldn't be the reviewers just to make sure that more than one developer eyeballs the changes.

**Comment by agarny** [comment]
Ok, merged then. :)
