### ISSUE TITLE
Naming: hasVariable vs containsComponent

### ISSUE THREAD

**Issue by MichaelClerx** [cellml/libcellml#211]
Is there a semantic difference we're indicating, or is this just an inconsistency?

@agarny @hsorby @nickerso

**Comment by nickerso** [comment]
Semantic difference, I think...maybe. `containsComponent` is searching the encapsulation hierarchy to determine if one component is encapsulated by the other (potentially searching many generations of the hierarchy). Whereas `hasVariable` will only ever check the variables in the given component.

**Comment by MichaelClerx** [comment]
We're using hasParent() for deep-checking the other way round though (and here 'contains' wouldn't make any sense). (Possible alternative would be hasAncestor())

**Comment by hsorby** [comment]
I think it was derived from the notion of aggregation and composition.  I don't think it is very clear here where one applies or the other (at least to me).  I think the aggregation was linked with has* and composition linked with contains*.

**Comment by agarny** [comment]
I seem to remember something along those lines too (wrt to @hsorby's comment). @dladd might be able to confirm.

**Comment by MichaelClerx** [comment]
Would be good to have the reason written here for future ref, but issue solved, as far as I'm concerned! Cheers
