### ISSUE TITLE
ComponentEntity docstring issues

### ISSUE THREAD

**Issue by MichaelClerx** [cellml/libcellml#212]
https://github.com/cellml/libcellml/blob/develop/src/api/libcellml/componententity.h#L68

There's a few of these

**Comment by hsorby** [comment]
I'm not clear on what the issue is you are pointing out here could you please explain a bit more.

**Comment by MichaelClerx** [comment]
Oh, sorry! I highlighted a line. It says "True if the units were replaced, false otherwise" where its actually _components_ being _removed_. There's a few similar ones in that file. I'm in the middle of adding Python docstrings so just had to write it down!

**Comment by hsorby** [comment]
I have noticed a few of these also I try and fix them and commit them as part of my current work.

**Comment by hsorby** [comment]
It seems copy and paste has struck again!
