### ISSUE TITLE
Entity.clearParent, why not setParent(null)

### ISSUE THREAD

**Issue by MichaelClerx** [cellml/libcellml#213]
For other things that can be set/unset (for example importSource, name) we use set(null) or set(""). Is there a rationale for having a different paradigm here?

@agarny @hsorby @nickerso

**Comment by agarny** [comment]
I can't recall the details, but looking at `entity.cpp`, there seems to be a need for `clearParent()`:

```
void Entity::setParent(Component *parent) {
    mPimpl->mParentComponent = parent;
}

void Entity::setParent(Model *parent) {
    mPimpl->mParentModel = parent;
}

void Entity::clearParent() {
    mPimpl->mParentComponent = nullptr;
    mPimpl->mParentModel = nullptr;
}
```

**Comment by MichaelClerx** [comment]
That would disappear if we move the methods to model and component, like @agarny proposed in #193

**Comment by agarny** [comment]
Fair point. Two weeks (since my comment in issue #193) seem like a lifetime to me! :)

**Comment by MichaelClerx** [comment]
*bump*

**Comment by hsorby** [comment]
I think it is fine to remove the clearParent and use null setParent() variant instead.  I have a feeling, but no concrete evidence, that we thought more entities would need knowledge of their parents.  That is why it was stuck in the Entity class.  We clearly don't need it currently so I don't have  a problem with moving it.

**Comment by hsorby** [comment]
`setParent` has now been removed from the API making this moot.
