### ISSUE TITLE
Missing method `Model.hasUnits(UnitsPtr units)`

### ISSUE THREAD

**Issue by MichaelClerx** [cellml/libcellml#215]
UPDATE: Title changed from `Variable.hasUnits` to `Model.hasUnits`

We only have a `hasUnits(string name)`. Other `hasX()` and `containsX()` methods accept either a name or an object.

**Comment by hsorby** [comment]
Units are tricky I have to constantly argue with @nickerso to make sure I get it right.

**Comment by agarny** [comment]
Units can indeed be a pain, still... I would be interested to know what is, here, the argument for not having a version of `hasUnits()` with an object as an argument...

**Comment by nickerso** [comment]
Just to be clear, this is actually talking about `Model::hasVariable()`, right? I'm not sure there is any reason to not have the matching object argument method...probably just an oversight in the initial implementation.

**Comment by MichaelClerx** [comment]
You're right! I did mean `Model::`, not `Variable::` 

as for the rest of the correction... :D

**Comment by agarny** [comment]
Closing as a result of PR #235.
