### ISSUE TITLE
The API uses lots of overloads, these cause trouble for the Python bindings

### ISSUE THREAD

**Issue by MichaelClerx** [cellml/libcellml#216]
The best example is `Units.addUnit()`. This can be called in 10 different ways.

For the Python bindings, this means that

- There is a single method `addUnit(*args)` (created by SWIG)
- This has to do lots of type checking, to find out which underlying method to call
- This isn't always possible (because of enums and type conversions!)

But a much bigger issue is that the Python user sees a _single method_ with variable arguments. So you can't quickly see what the method can take by looking at parameter names. Instead, you need to check the documentation. And then you'll find out there's 10 different ways of calling this function! I imagine this won't make it easy to debug either...

Very curious to hear everyone's thoughts on this.

Just to emphasise, this is a usability / design question, I'm sure we can build something that passes tests. But I don't think the current design will translate in bindings that are easy to use/learn/debug/understand

**Comment by MichaelClerx** [comment]
(and when I say 10 overloads that doesn't mean 10 signatures, because a lot of them have default argument values too...)

**Comment by MichaelClerx** [comment]
For this particular case, it can be simplified to:

    addUnit(reference, prefix, exponent=1, multiplier=1)
    addUnit(reference, exponent)
    addUnit(reference)

where `reference` is a string or StandardUnit
and `prefix` is a string, Prefix, or double

except... when `prefix` is a double `exponent` is no longer optional

and languages without enums can't tell StandardUnit/Prefix from ints (which can be converted to doubles)

**Comment by hsorby** [comment]
We did just drop some of these when we removed offset (which meant we had even more overloads), well worth a review!

We can remove some methods in the interface files to simplify the choices down.  In C++ we need the overloads for convenience.

**Comment by nickerso** [comment]
We now have functional Python bindings for libCellML, so is this still an issue that needs addressing?

**Comment by MichaelClerx** [comment]
Well yes. They're functional but not necessarily pretty! You'd get the same if you (somehow) did javascript bindings, or bindings to any other language that doesn't use explicit typing (matlab, R).

If everyone's fine with this, then close this. I personally don't like it, and would try to write the class and function signatures in such a way that is uses as little C-specific stuff as possible, i.e. try to limit ourselves to a subset of language constructs that works nicely in lots of languages...

**Comment by agarny** [comment]
I agree that the API should look as good/native as possible in C++ and Python (and Java, at some point).

**Comment by nickerso** [comment]
Just to summarise my (limited) understanding of this issue - feel free to correct me!

We currently have a C++ API for libCellML which does look good in C++ and functions just as most C++ developers would expect. This, however, results in generated Python bindings which are not as pythonic as a python developer would expect them to be, although they do work and enable complete access to the libCellML API. We could make the API less C++'ish which would then allow us to generate bindings that are more compatible with standard Python (and potentially other bindings in future). 

I can see the benefit to keeping things as native as possible across the target languages, but suspect that will result in a library that is mediocre for all languages.

We could also, presumably, do a lot more hand-crafting of the bindings interface to get a Python API that is more pythonic while keeping the C++ API as is? But that would obviously require more resource to maintain and develop...

**Comment by agarny** [comment]
I agree that, ideally, we would have hand-craft each bindings, but this would indeed require resources that we just don't have. Does anyone know what other projects (libSBML, libSEDML, etc.) do when it comes to bindings (besides relying on `SWIG`)? Do they hand-craft them?

In the end, we probably just ought to carry on as we have so far and then rely on the community to hand-craft the bindings they want to use?

**Comment by MichaelClerx** [comment]
@nickerso it's not that the bindings aren't stylish, it's that the overloaded functions cause real issues! 

1. If you have several overloaded C++ functions, they become 1 function in python/matlab/javascript/R, with the signature `addUnit(everything)`. This is not an issue for code, which SWIG nicely generates for us, but it is a massive issue for the users, who get presented with 1 monolithic python function that calls 1 of 10 C++ functions depending on what you fill in for `everything`.
2. If you overload types that other languages can't distinguish (e.g. enum and int for python), you lose functionality completely, because SWIG has no way to guess if the int you gave it was a number or a code for an enum

I'll have another look at the bindings this week to see how much the recent changes cleared up!

**Comment by agarny** [comment]
Ok, I now understand (remember?) better the implications of C++ overloaded functions and enums on the Python bindings. Not great at all, I agree.

Now, C++ overloading and enums are very handy (I use them all the time). So, I would like to keep them in the C++ version of `libCellML`, if possible.

Regarding C++ overloaded functions, couldn't we make use of conditional compilation? For example:

```
class MyClass
{
public:
#ifdef ENABLE_OVERLOADED
    void myFunction(int);
    void myFunction(double);
#else
    void myIntFunction(int);
    void myDoubleFunction(double);
#endif
};
```

As for enums, it is supported as of Python 3.4 (see [here](https://docs.python.org/3/library/enum.html)), which makes me wonder which version of Python we want to support? Otherwise, I am not quite sure how we could get rid of them.

**Comment by nickerso** [comment]
libSBML I believe just uses SWIG generated bindings, same for libSEDML. This is why JSBML was created, to provide a native Java implementation (same with JSEDML, although that one isn't so active anymore).

Talking to others here in Seattle, I think the way to go is to try and make the SWIG generated bindings as good as possible, but leave it up to the "users" to contribute higher level API suggestions for specific binding languages.

**Comment by agarny** [comment]
I guess an alternative might have been to write `libCellML` in pure C and then have a C++ version on top of it, and use the C version to generate bindings. Isn't it what is done for `OpenCMISS-Zinc`?

**Comment by MichaelClerx** [comment]
How about we just close this issue for now and deal with it later? Maybe in a version 2 once we know exactly how this version will work? Goal was always C++, I think...

**Comment by agarny** [comment]
Your call @MichaelClerx, you are the one who created this issue.
