### ISSUE TITLE
LibXml2 library for Windows.

### ISSUE THREAD

**Issue by hsorby** [cellml/libcellml#217]
We need to provide direction on how to get libXml2 suitable for libCellML available on Windows.

**Comment by agarny** [comment]
I would make this issue more general, i.e. provide directions on how to get all the dependencies needed to build libCellML on all our supported platforms.

**Comment by agarny** [comment]
From https://github.com/cellml/libcellml/issues/161#issuecomment-334882908:

> I spoke with @nickerso about this and thought we should probably provide binaries so that people may use them easily.

Binaries would be nice (this is indeed what the libSBML guys do on Windows), but it might be even better to do this transparently, as well as make it possible to build a dependency from scratch, if needed. This is what we did with @dbrnz in OpenCOR. For example, for `zlib`, [this](https://github.com/opencor/opencor/blob/master/src/plugins/thirdParty/zlib/CMakeLists.txt) and [this](https://github.com/opencor/zlib/releases) are what we did. I can talk to @nickerso about it next week at COMBINE and/or you can talk about it with @dbrnz .

**Comment by nickerso** [comment]
My view is that setting up a build environment is a separate thing to building a particular piece of code - the problem with doing things transparently is that when they go wrong its often impossible to see why (a la the CellML API and its internal libxml). I agree that having directions on getting correct dependencies installed/available is a must have now that we have a dependency, but I would not like to see this as part of the libCellML configure/build process. As with @hsorby, I use the CMake'ified libXml2 from OpenCMISS (https://github.com/OpenCMISS-Dependencies/libxml2) and that has worked for me in other projects on windows, but I haven't tried libCellML on windows.

If things start getting complicated, we may want to provide a separate "tool" to help people configure their local build environments (and us on our CI systems), such as the [setup](https://github.com/OpenCMISS/setup) from OpenCMISS or my own [get-configured](https://github.com/nickerso/get-configured). But I don't think we are anywhere close to that requirement for libCellML yet.

**Comment by agarny** [comment]
If I am not mistaken, libxml in the CellML API had been modified. Nothing of the sort would happen here. It's just that what I am proposing would not only make end-users' life easier, but it would also ensure that people are using the right version of this or that library, which we know works fine with libCellML.

Now, it's true that `libxml2` is our only required dependency at the moment, so probably not worth going with such an involved solution at this stage.

**Comment by MichaelClerx** [comment]
> If I am not mistaken, libxml in the CellML API had been modified. Nothing of the sort would happen here. 

Just want to +1 this! I already have libxml installed for other projects and it worked fine automatically. Using a modified version would force me to compile, and probably create linking issues for this and other projects as they figure out which version to use...

**Comment by agarny** [comment]
FWIW, I can see that, in OpenCMISS, you guys are using a version of libxml2 that was released on 6 October... 2009!? Clearly, it would be good to ensure that libCellML works with the most recent version of libxml2...

**Comment by agarny** [comment]
FWIW, I quickly wanted to use `ExternalProject_Add()` to build `libxml2` (and `zlib` first), if it wasn't found. For this, I wanted to rely on https://github.com/madler/zlib for `zlib` and https://github.com/GNOME/libxml2 for `libxml2`. I managed to get `zlib` to build fine, but then noticed that `libxml2` relies on autotools (!!). So, I am giving up for now. Depending on how we actually want to proceed, we might want to have a look at https://github.com/martell/libxml2.cmake or https://github.com/OpenCMISS-Dependencies/libxml2, indeed, since both of them build `libxml2` using CMake.

Personally, I would really like things to be as transparent as possible when it comes to building `libCellML`, so I might have another look at it...

**Comment by hsorby** [comment]
I don't see that it is clear that libCellML should work with the most recent version of libXml2.  It must work with a version and that version must be easily accessible (the last only really applies in the case of Windows).

**Comment by hsorby** [comment]
I will look at updating the OpenCMISS libXml2 library with version 2.9.6.  I have the old version working nicely on my Windows machine.  This project https://github.com/martell/libxml2.cmake is clearly dead.

**Comment by agarny** [comment]
Yes, https://github.com/martell/libxml2.cmake definitely appears to be dead. I was merely mentioning it in regards with CMake.

Regarding libCellML and libxml2, it's just that some Windows users may have the latest version installed on their machine. Anyway, I am happy with whatever solution, as long as it works works transparently.

**Comment by nickerso** [comment]
I followed the build instructions on a new Windows 10 laptop and everything worked. This included making use of the linked OpenCMISS build of libxml2 which was trivial to download and install. So I think we can consider this closed and people can open new issues if there are specific problems building/using libCellML on Windows.
