### ISSUE TITLE
Link to zlib in cmake

### ISSUE THREAD

**Issue by maierbn** [cellml/libcellml#224]
I get the following error when compiling (with `LIBCELLML_BUILD_SHARED=Off`) on linux (Ubuntu 16.04.3):
```
...
[ 50%] Linking CXX executable test_validator
/store/software/opendihu/dependencies/libxml2/install/lib/libxml2.a(xmlIO.o): In function `xmlFreeZMemBuff':
/store/software/opendihu/dependencies/libxml2/src/libxml2-2.9.7/xmlIO.c:1465: undefined reference to `deflateEnd'
/store/software/opendihu/dependencies/libxml2/install/lib/libxml2.a(xmlIO.o): In function `xmlGzfileOpenW':
/store/software/opendihu/dependencies/libxml2/src/libxml2-2.9.7/xmlIO.c:1155: undefined reference to `gzdopen'
/store/software/opendihu/dependencies/libxml2/src/libxml2-2.9.7/xmlIO.c:1184: undefined reference to `gzopen64'
...
```
Obviously linking to zlib is missing. Should a `find_package(ZLIB REQUIRED)` be added to the CMakeLists.txt or did I setup libxml2 incorrectly?

**Comment by nickerso** [comment]
The dependency on zlib should come through from libxml. I suspect there are problems when building statically and I'm not sure how well testing that configuration is. @chrispbradley - do you do static builds with CellML enabled? Otherwise manually adding the zlib dependency directly to libcellml should get you around this problem.

**Comment by chrispbradley** [comment]
Static? I cant even get a full dynamic built ;-) I suspect it might be related to this

https://github.com/OpenCMISS/manage/issues/100

If you don’t have libxml2-dev installed it has to build it and there are problems finding it in config mode. You could try a work around by installing libxm2 (and dev) packages?

**Comment by nickerso** [comment]
Doesn't look like this is a problem with libCellML itself, so I'll close this for now - please reopen if this is still a problem.
