### ISSUE TITLE
Convention for variable naming

### ISSUE THREAD

**Issue by hsorby** [cellml/libcellml#23]
We should decide on what variable naming convention to follow, after some comments on pull request #22 it would appear we have different opinions.  This issue is to sort out the naming convention for variables and have the decision added to the libcellml coding standard documentation.

**Comment by hsorby** [comment]
My coding standard would be:
- Local variable: `myCellmlVariable`
- Function parameter: `myCellmlParameter`
- Class member: `mMyCellmlMember` ( or `_MyCellmlMember` but from comments it seems I am alone in this)

**Comment by nickerso** [comment]
I'm with @hsorby:
- Local variable: myCellmlVariable
- Function parameter: myCellmlParameter
- Class member: mMyCellmlMember

**Comment by agarny** [comment]
Just to confirmed that my personal preference is:
- Local variable: `myCellmlVariable`
- Function parameter: `pMyCellmlParameter`
- Class member: `mMyCellmlMember`

**Comment by jonc125** [comment]
I agree with the consensus on class members, and don't have a strong preference for parameters/local variables (provided functions are kept short!).

**Comment by mirams** [comment]
I am likely to get a bit confused if parameters start with p, since any pointers start with p in Chaste, but I can probably cope!

**Comment by hsorby** [comment]
To summarise, we have agreement on:
- Local variable: `myCellmlVariable`
- Class member: `mMyCellmlMember`

and contention on:
- Function parameter: `myCellmlVariable`   [1]

or
- Function parameter: `pMyCellmlVariable`  [2]

With (I guess) the voting as follows

option [1] has 2 votes for
option [2] has 1 vote for

and we have two ambivalent votes. So if the ambivalents don't wish to move off the fence we will go with option [1]

**Comment by agarny** [comment]
Seems reasonable to me.
