### ISSUE TITLE
Tests: treat warnings as errors

### ISSUE THREAD

**Issue by agarny** [cellml/libcellml#239]
Right now, warnings are not treated as errors for tests (unlike for the rest of the code). The indirect consequence of this is that the API may not be bullet proof.

Indeed, I have create an OpenCOR plugin for `libCellML` and I wanted to test it by having something like:

```
libcellml::Model *cellmlModel = new libcellml::Model();

static const std::string ModelName = "myModel";

cellmlModel->setName(ModelName);

QCOMPARE(cellmlModel->getName(), ModelName);

delete cellmlModel;
```

and it failed because I have warnings treated as errors, resulting in the following error message:

```
error: delete called on non-final 'libcellml::Model' that has virtual functions but non-virtual destructor [-Werror,-Wdelete-non-virtual-dtor]
```

This warning/error (and others) shows up when uncommenting

```
#  if(LIBCELLML_TREAT_WARNINGS_AS_ERRORS)
#    target_warnings_as_errors(${CURRENT_TEST})
#  endif()
```

in `tests/CMakeLists.txt`.

So, ideally, warnings would be treated as errors in all parts of the `libCellML` code.

**Comment by hsorby** [comment]
The reason we don't have treat warnings as errors on for the tests is that for some compilers gtest doesn't compile without warnings.
