### ISSUE TITLE
Windows: MSVC may define `PASCAL`, which conflicts with our `StandardUnit` enum

### ISSUE THREAD

**Issue by agarny** [cellml/libcellml#244]
Just got bitten by this on Windows using Qt/C++ with MSVC 2015.

At some point, OpenCOR indirectly includes `C:\Program Files (x86)\Windows Kits\8.1\Include\shared\minwindef.h`, which defines `PASCAL` as `__stdcall`, resulting in the following compilation errors:

```
C:\Users\Alan\Desktop\OpenCOR\src\plugins\thirdParty\libCellML\ext\debug\include\libcellml/units.h(75): error C2059: syntax error: '__cdecl'
C:\Users\Alan\Desktop\OpenCOR\src\plugins\thirdParty\libCellML\ext\debug\include\libcellml/units.h(75): error C3805: '__cdecl': unexpected token, expected either '}' or a ','
```

There is an easy way around it, which is to `#undef PASCAL` just before including `libcellml/units.h` (and `#define PASCAL __stdcall` just after, to be on the safe side).

Still, we might want to do something about it?...

**Comment by nickerso** [comment]
Looks like it can just be `#undef`'d and not brought back... https://stackoverflow.com/questions/2774171/what-is-far-pascal

**Comment by agarny** [comment]
Agreed, so we might want to `#undef PASCAL` in `libcellml/units.h`, so people don't come across the same issue and waste time figuring out why on earth `PASCAL` caused MSVC to complain.
