### ISSUE TITLE
Length of variable in a component and Length of component in a model

### ISSUE THREAD

**Issue by dewancse** [cellml/libcellml#259]
Hi all,

I have been using libcellml for a couple of weeks now. As a novice developer, I am very happy with libcellml's API and its documentation. 

I am wondering whether we have an API to calculate number of variables inside a component and number of components inside a model. Currently, I am doing in the following ways:

 i = 0
 while c.getVariable(i) != None:
     v = c.getVariable(i)
     # code ....
     i += 1

....... and I have heaps of code similar above. It would be efficient if I could have a way to call a length function of a component to compute number of variables of that component. Similar thing applies for number of components inside a model.

Thanks,
Dewan

**Comment by agarny** [comment]
@dewancse, I think you might after the [`Component::variableCount()`](https://github.com/cellml/libcellml/blob/38dda78d718147196ba73cf445537573618550ef/src/api/libcellml/component.h#L185) and [`ComponentEntity::componentCount()`](https://github.com/cellml/libcellml/blob/38dda78d718147196ba73cf445537573618550ef/src/api/libcellml/componententity.h#L264) (`Model` inherits from `ComponentEntity` (see [here](https://github.com/cellml/libcellml/blob/38dda78d718147196ba73cf445537573618550ef/src/api/libcellml/model.h#L32))...?

**Comment by dewancse** [comment]
Thanks very much @agarny. Got it now. Works fine for Python bindings!

**Comment by hsorby** [comment]
This issue looks to be resolved so closing.
