### ISSUE TITLE
Model validation

### ISSUE THREAD

**Issue by dewancse** [cellml/libcellml#260]
Hi all,

I have created a manuel model here (https://github.com/dewancse/model-assembly-service/blob/master/src/model-manuel.xml). Libcellml says that the model is valid although I have two instances of solute_concentrations component in the encapsulation hierarchy.

Thanks,
Dewan

**Comment by agarny** [comment]
I may be wrong, but nothing in CellML prevents you from having several instances of an imported component. So, not quite sure what the problem is here.

**Comment by dewancse** [comment]
Thanks @agarny. @nickerso told me that a component can not have multiple instances in the encapsulation hierarchy. And He asked me to make an issue here. I am not sure which is right!

**Comment by agarny** [comment]
Oops, sorry, my bad. I completely overlooked the encapsulation bit. So, yes, @nickerso is right here.

**Comment by hsorby** [comment]
Could you post your actual code to help fix this problem?  Thanks.

**Comment by dewancse** [comment]
Thanks @hsorby. I have tested with the following code:

import requests
from libcellml import *

href = "https://raw.githubusercontent.com/dewancse/model-assembly-service/master/src/model-manuel.xml"
r = requests.get(href)

p = Parser()
m = p.parseModel(r.text)

validator = Validator()
validator.validateModel(m)

print(validator.errorCount())

**Comment by dewancse** [comment]
Sorry, here is the new link: https://raw.githubusercontent.com/dewancse/model-assembly-service/master/src/model-manual.xml

**Comment by hsorby** [comment]
It appears that this is not currently invalid according to the current specification.  So unfortunately we will have to wait for a correction to the specification before we can actually fix this.
