### ISSUE TITLE
Parsing should be done on fully qualified element names

### ISSUE THREAD

**Issue by agarny** [cellml/libcellml#263]
This is related to issue #236 and PR #237. There were some discussions about validating a CellML file against a CellML 2.0 schema, but... we don't have one (and who knows when we might get one...). So, it might be faster (for now, if anything) to just parse a CellML file for fully qualified element names. As for attributes, we probably just ought to follow common practice, i.e. expect them to be in the null namespace. @hsorby, @jonc125, @MichaelClerx, @nickerso: does that sound reasonable to you guys? If so, I am happy to have a go at it (I just really need to be able to distinguish between CellML 1.0/1.1 and CellML 2.0 files.)

**Comment by nickerso** [comment]
I think this is the way to go, we want to keep validation separate from parsing but do want to make sure that we only parse CellML 2.0 documents rather than any random XML that happens to have matching local names (e.g., CellML 1.x).

**Comment by agarny** [comment]
FWIW, PR #264 implements what I described above. I have then tried it in OpenCOR and it's working as I expect, i.e. OpenCOR can now distinguish between CellML 1.0/1.1 and CellML 2.0 files.

**Comment by MichaelClerx** [comment]
Cool! Were there any major difficulties in creating a CellML 2 schema? Or just lack of time?

I'm helping @jonc125 teach XML next week, so might be a good time to work on that...

**Comment by nickerso** [comment]
I'm pretty sure its just a lack of time to create a schema, but also I do think the schema validation route is not appropriate for straight out parsing of models. Having a CellML 2.0 schema would definitely be a valuable resource if you are volunteering @MichaelClerx!
