### ISSUE TITLE
Build in ubuntu 18.04

### ISSUE THREAD

**Issue by dewancse** [cellml/libcellml#268]
Hello,

I am trying to build libcellml in ubuntu 18.04 and getting the following error:

-------
dewan@dewan-VirtualBox:~/libcellml-build$ cmake -DBUILD_TYPE=Release $LIBCELLML_SRC
-- Could NOT find Sphinx (missing: SPHINX_EXECUTABLE) 
-- Configuration confusion:
            Release build requested but memchecking or coverage has also been requested.
            This is not possible so forcing the build type to 'Debug' to make it possible.
            
CMake Error at /usr/local/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find LibXml2 (missing: LIBXML2_LIBRARY LIBXML2_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/local/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/share/cmake-3.13/Modules/FindLibXml2.cmake:91 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:149 (find_package)

Configuring incomplete, errors occurred!
See also "/home/dewan/libcellml/CMakeFiles/CMakeOutput.log".

-------

Looks like this is related to cmake issue!. Can anyone help me to solve this problem?

Thanks,
Dewan

**Comment by agarny** [comment]
It looks to me like neither [Sphinx](http://sphinx-doc.org/) nor [LibXml2](http://xmlsoft.org/) are installed on your computer. So, you need to install them. Something like ``sudo apt install python3-sphinx  libxml2-dev``?

**Comment by dewancse** [comment]
Thanks @agarny. In my humble opinion, we should update the LibXML2 section of the libCellML documentation: https://libcellml.readthedocs.io/en/latest/dev_setup.html#libxml2. It would be convenient for future users.

Thank you.

**Comment by agarny** [comment]
Agreed @dewancse, I am going to do it as part of issue #266.
