### ISSUE TITLE
Add some status information to README

### ISSUE THREAD

**Issue by MichaelClerx** [cellml/libcellml#270]
We should let people know the library isn't ready for use yet on the main page I think

@nickerso ?

**Comment by nickerso** [comment]
I keep telling people that for the things it is capable of, that it is definitely preferable to use libCellML than try to learn to use the CellML API (for example, @dewancse has been able to get some model composition code up and running in Python with minimal assistance and much quicker than if he had to start from scratch with the CellML API). And it is good to have non-core developers testing things out, I think.

But I agree that adding some status information prominently to the README would be useful. Perhaps a comment to make sure it is clear that libCellML should be considered alpha until we make a 1.0 release? And some kind of summary about what we know has not been implemented (links to tracker items?)?

**Comment by agarny** [comment]
> But I agree that adding some status information prominently to the README would be useful. Perhaps a comment to make sure it is clear that libCellML should be considered alpha until we make a 1.0 release? And some kind of summary about what we know has not been implemented (links to tracker items?)?

Will look into it.

**Comment by agarny** [comment]
FWIW, before we can deal with this issue, I think we will need to handle PR #267 first.
