### ISSUE TITLE
Off-topic: Can we have a github project where we post issues with cellml.org?

### ISSUE THREAD

**Issue by MichaelClerx** [cellml/libcellml#271]
Please @nickerso ?

Or does this already exist?

**Comment by agarny** [comment]
Are you talking about the cellml.org website in general and/or PMR2? Either way, what about https://github.com/PMR2/cellml.site and https://github.com/PMR2/pmr2.app?

**Comment by nickerso** [comment]
@metatoaster can confirm, but I'm pretty sure that https://github.com/PMR2/cellml.site is the repo for the cellml.org website and would be the appropriate place to post issues. We might want to look at "moving" that repo into the `cellml` organisation now that we have one.

**Comment by agarny** [comment]
Agreed with moving the site repo under the `cellml` organisation.

**Comment by nickerso** [comment]
not sure what impact that would have for things like backups and CI, so will let @metatoaster comment before we look to move it ;-)

**Comment by metatoaster** [comment]
The `cellml.site` repo predates any CI setup, and this move from the `PMR2` should have happened when the `cellml` organisation was created.  The deployment build script does reference the repo, but github does have internal redirects built in so it should be an issue (and I can update that script also).  I will still need full rights to the repo so I can update it after the move.

**Comment by nickerso** [comment]
thanks @metatoaster. Closing this one in favour of PMR2/cellml.site#1. The new repo under the CellML organisation will be the place to submit issues with the website.
