### ISSUE TITLE
Update list of contributors

### ISSUE THREAD

**Issue by MichaelClerx** [cellml/libcellml#272]
Besides organisations who've signed some sort of agreement, we could also have a list of people who worked on libcellml (presumably in their spare time)

**Comment by nickerso** [comment]
is there a way to generate this from Github?

**Comment by MichaelClerx** [comment]
There is just this I suppose: https://github.com/cellml/libcellml/graphs/contributors

So no need to write it out ourselves then :D

**Comment by nickerso** [comment]
just need to incorporate it into the docs :)

**Comment by agarny** [comment]
FWIW: https://developer.github.com/v3/repos/#list-contributors.
