### ISSUE TITLE
Update 'current thinking' document with new ideas for handling maths

### ISSUE THREAD

**Issue by MichaelClerx** [cellml/libcellml#273]
At the moment it says we won't be doing this, just returning strings, but I believe we've moved on :-)

**Comment by agarny** [comment]
Would it be worth making this "issue" more general and have it cover various improvements/updates to the documentation in general, rather than refer to a specific update?

**Comment by MichaelClerx** [comment]
I think there's a few documentation tickets open already
* #41 link documentation on readthedocs to current "develop" doxygen and coverage Documentation
* #149 Figures numbers not showing in documentation Documentation
* #207 Add docs for Python bindings, based on the docstrings Bindings
* #221 Improve development setup documentation. Documentation
* #258 Documentation: add information about SWIG and Python Bindings Documentation
* #269 Documentation: python bindings in ubuntu



Some that relate to this issue:
* #118 Current thinking on validation
* #232 Write a very minimal CAS
* #257 Code generation output

**Comment by nickerso** [comment]
closed by #331.
