### ISSUE TITLE
parseModel in windows and ubuntu

### ISSUE THREAD

**Issue by dewancse** [cellml/libcellml#276]
Hi all,

I have written a model assembly service in python which assembles components from various source models and produces a new CellML model. I executed the main.py (https://github.com/dewancse/model-assembly-service/blob/master/src/main.py) and miscellaneous.py (https://github.com/dewancse/model-assembly-service/blob/master/src/miscellaneous.py) in WINDOWS and it worked well. Here, main.py is the primary file and some of the helper functions have been defined in miscellaneous.py. And I run this command "python main.py" to run the service. 

Afterwards, I executed same files in alpine ubuntu, but got this error "NoneType object does not have attribute variableCount()". Note that I needed to run in alpine ubuntu because my end goal is to create a docker container which is linux based. 

To solve this problem, I did check with "if componentName != None" in the required code section. In this case, I could produce a new CellML model but without producing any variable. I am not sure what went wrong. Same code works in windows but not alpine ubuntu.

Do you have any suggestions? Thanks for your time and help.

Thanks,
Dewan

**Comment by MichaelClerx** [comment]
Hi @dewancse ! For starters, checks for None should be with `is`, so `if x is None` or `if x is not None`. Will try to have a detailed look later!

Also which Python versions are you using on these systems?

**Comment by dewancse** [comment]
Hi @MichaelClerx, 

Thank you. I am using python 3. I replaced with `if x is not None` but same result.

I rerun the same code in WINDOWS and printed `impComponent's` (https://github.com/dewancse/model-assembly-service/blob/master/src/miscellaneous.py#L628) value which was: `<libcellml.component.Component; proxy of <Swig Object of type 'std::shared_ptr< libcellml::Component > *' at 0x000000EBC8069840> >`.  Then I rerun the same code in ALPINE UBUNTU and printed the `impComponent` which was: `None`. This is strange to me as same variable is giving different output in WINDOWS and Ubuntu.

Could you please check this at your convenient time? I think I should also change the issue title!

Thanks,
Dewan

**Comment by MichaelClerx** [comment]
Hi Dewan!
I don't have Alpine Ubuntu at my disposal. Could you check the C++ version on there and see if that works OK, or if it's definitely a bindings issue?

**Comment by dewancse** [comment]
Hi Michael, 

Thanks! I am afraid I am not a C++programmer. But I did try to run `parser` (https://github.com/cellml/libcellml/blob/develop/tests/parser/parser.cpp) test in `Ubuntu 18.04`, but failed to do that.

My apologies to mention `alpine ubuntu` in the above conversation, however, this problem also exists in `ubuntu 18.04`, i.e. value of `impComponent` (https://github.com/dewancse/model-assembly-service/blob/master/src/miscellaneous.py#L628) is: `None`, whereas in `windows`, `impComponent` is: `<libcellml.component.Component; proxy of <Swig Object of type 'std::shared_ptr< libcellml::Component > *' at 0x000000EBC8069840> >`. I did also check the value of `r.text` (https://github.com/dewancse/model-assembly-service/blob/master/src/miscellaneous.py#L627) and `importedComponent.getName()` (next line of the previous link) in `windows` and `ubuntu 18.04`, both produced same output. Note that `importedComponent.getName()` gave `total_transepithelial_sodium_flux` which exists in the parsed model (impModel here https://github.com/dewancse/model-assembly-service/blob/master/src/miscellaneous.py#L627). `windows` can find `total_transepithelial_sodium_flux` in the parsed model (see prev link) but `ubuntu 18.04` could not find it, therefore, gave `None`. 

Hence, `parseModel` is making difference between `windows` and `ubuntu 18.04`, I think. My analysis might be wrong though :) 

Thanks, 
Dewan

**Comment by MichaelClerx** [comment]
Hmmm, probably still best to spend some time getting all C++ tests to pass first!

**Comment by dewancse** [comment]
Hi Michael, 

I tried to run a parser test separately (parser.cpp here https://github.com/cellml/libcellml/blob/develop/tests/parser/parser.cpp) but failed to do that as I  struggled to setup libcellml header file and other dependencies path setting issue, which is not relevant here.

However, when I installed libcellml I run ctest and 100% test passed. Hopefully, parser test is included in the 100% test pool.

Thanks,
Dewan

**Comment by nickerso** [comment]
Just to note that I now have things running on my Windows machine and I seem to be getting the same error that @dewancse has under Ubuntu. I'm taking a look to see if I can work out what is going wrong...

**Comment by nickerso** [comment]
OK, I'm starting to think this issue is caused by #264 - at least for me going with current develop from the prime repo. In @dewancse's code, we're trying to load a CellML 1.1 model into libCellML, which prior to #264 would have silently worked for the parts that are the same between 1.1 and 2.0, but now the parsing will fail as the it is not a 2.0 model.

@dewancse, if you update your source under windows and rebuild the library and python bindings you will probably see this behaviour. (You'll need to make sure you update the library that the python bindings are using on your machine.) You'll need to check that the parsing is successful prior to trying to use the imported model.

**Comment by dewancse** [comment]
Thanks @nickerso. In my windows 8 machine, installation of libcellml is not straight forward and @hsorby did some magic to make it running on my machine. I will better spend time on Ubuntu and will try to check parsing before using it. Thank you!

**Comment by MichaelClerx** [comment]
Thanks @nickerso ! If that is the case, we should probably create a new issue to provide better error messages in Python :)

**Comment by agarny** [comment]
Nice catch @nickerso and good thing that we worked on #264 now rather than later! :)

**Comment by nickerso** [comment]
I think the error messages are there in the parser, just need to check the state of the parsing and grab the error if needed. @dewancse - check #277 and see if that helps getting things to work for you under windows if that is an easier system to develop in as we try to get that code of yours working.

But I'll close this one for now, can revisit if there is still an underlying issue separate to the introduction of namespace matching in #264.

**Comment by nickerso** [comment]
Not sure the resolution was clear, but to summarise: @dewancse found that (python) code that had previously been working under windows failed to work under linux, giving what looked to be fairly unrelated error messages. However, the windows version of libcellml being used pre-dates the introduction of namespace aware parsing that landed a couple of days ago with #264. The linux build of the code is using the namespace aware parsing, which now fails to load our test models which happen to be CellML 1.1 models, which leads to some suggested improvements in our own code and means the error messages being obtained under linux make a lot more sense.
