### ISSUE TITLE
Using (under-development) Python bindings on Windows

### ISSUE THREAD

**Issue by nickerso** [cellml/libcellml#277]
[Note that this is more to help me remember how to do this, will eventually be replaced with standard installer and documentation "soon". This might be useful to others trying to use the still under development Python bindings for libcellml on a windows machine.]

Not sure this is the best place, but just wanted to document what I did to get the Python bindings working for me on a Windows 10 machine. I have a relatively vanilla Python 3.7.1 installed in my system and followed the standard prerequisites and build instructions to get libcellml to build with all the tests passing, including the Python bindings. I have the current `develop` branch checked out in `c:\path\to\libcellml` and built the library using Visual Studio (Debug mode) in `c:\path\to\libcellml-build`.

Not saying these are the best instructions, but this worked for me. Today.

In a standard DOS command prompt:

1. `pip install virtualenv`
2. `pip install  virtualenvwrapper-win` (provides windows version of `virtualenvwrapper` which provides some useful wrappers for the raw Python virtual environments)
3. `mkvirtualenv project-name` (to make a new virtual environment for my project, this will also activate the virtual environment; if you already have the virtual environment then `workon project-name` to activate it)
4. `add2virtualenv c:\path\to\libcellml-build\src\bindings\python` (still couldn't find the `libcellml` module to import...)
5. `add2virtualenv c:\path\to\libcellml-build\src\bindings\python\Debug` (or `Release` or whatever build type you built) (my Python code can now find the libcellml module to import, but fails to load the native code.)
6. `set PATH=%PATH%;c:\path\to\libcellml-build\src\Debug` (make sure to match the build type with the bindings)

And now I can run my Python code when that virtual environment is activated. I think there might be a way to set the `PATH` as part of the virtual env activation, but will worry about that later.

**Comment by nickerso** [comment]
Just to add an update on how this is now working, important to make sure that libcellml is being built with the same python (version) as being used in the virtual environment. This is especially important now that Visual Studio is shipping with its own python that is picked up by default by CMake...

4. `pip install -e c:\path\to\libcellml-build\src\bindings\python\Release` (or `Debug`, but currently having a problem building debug ;-)

This is all that is needed, module and libraries all seem to be found without any need for tweaking the path.

**Comment by kerimoyle** [comment]
A bit confused ... why would you not build libcellml inside the same virtual environment as you're working in?  Where do the different versions come from?

**Comment by nickerso** [comment]
I'm using the cmake and visual studio GUIs and don't know what I'm doing :) A recent update to Visual Studio looks to have updated the default Python that CMake finds and so I was building the libcellml Python bindings for Python 3.7 but trying to work in Python 3.8. And also I have many virtual environments that I would like to use libCellML from so I don't want to rebuild for each of them.

**Comment by hsorby** [comment]
Closing this, libcellml is now pip-installable  on Windows (and Linux and macOS) `pip install -U libcellml` to install the latest version.
