### ISSUE TITLE
Add support for Clang-Tidy and additional Clang warnings

### ISSUE THREAD

**Issue by agarny** [cellml/libcellml#283]
[Clang-Tidy](https://clang.llvm.org/extra/clang-tidy/) is a tool for "diagnosing and [automatically] fixing typical programming errors". In the case of libCellML, it might be nice to take advantage of such a tool to ensure that our codebase is as "clean" as possible.

We could, in CMake, check whether Clang-Tidy is installed and, if so, run it against our codebase. If anything gets reported then the build would be considered as having failed.

We clearly can't force developers to have Clang-Tidy installed on their system, but our CI system should definitely have it (at least our macOS slave since Clang is the default compiler on that platform).

To start with, we might want to use the Clang-Tidy settings used by Qt Creator and then refine them as we see fit. Those settings are:

```
-checks=-*,bugprone-*,cppcoreguidelines-avoid-goto,cppcoreguidelines-c-copy-assignment-signature,cppcoreguidelines-interfaces-global-init,cppcoreguidelines-narrowing-conversions,cppcoreguidelines-no-malloc,cppcoreguidelines-pro-*,cppcoreguidelines-slicing,cppcoreguidelines-special-member-functions,misc-*,modernize-*,performance-*,readability-avoid-const-params-in-decls,readability-container-size-empty,readability-delete-null-pointer,readability-deleted-default,readability-else-after-return,readability-function-size,readability-identifier-naming,readability-inconsistent-declaration-parameter-name,readability-misleading-indentation,readability-misplaced-array-index,readability-non-const-parameter,readability-redundant-*,readability-simplify-*,readability-static-*,readability-string-compare,readability-uniqueptr-delete-release,readability-rary-objects
```

We might also want to add additional Clang warnings, based on what Qt Creator's Clang Code Model plugin does. Note that this is clearly only relevant if we are building libCellML using Clang, i.e. on macOS for now.

The idea of the above is to catch as many warnings as possible to ensure that our codebase is as good as possible. Also, if libCellML is to be built with warnings as errors, then we should do the same here.

**Comment by kerimoyle** [comment]
Hi Alan
I'm trying to configure my stuff to use clang-tidy but the options above give me "invalid argument" errors (not sure which flag is problematic).  Is it possible to do a -dump-config from your configuration and include the output in a .clang-tidy file in the repo instead?

**Comment by agarny** [comment]
It should all work fine with Clang-Tidy 8.0.0. So:
- Which operating system are you using? macOS, I believe?
- Which version of Clang-Tidy are you using? In my case:
```
$ clang-tidy --version
LLVM (http://llvm.org/):
  LLVM version 8.0.0
  Optimized build.
  Default target: x86_64-apple-darwin18.6.0
  Host CPU: skylake
```
I should have installed it for you (using `brew`; if you run `brew list`, you should see an entry for `llvm`).

About having a `.clang-tidy` file, I agree that it would have been the obvious option (as we have done with ClangFormat), but... if you check [`cmake/common.cmake`](https://github.com/cellml/libcellml/blob/639a06f7aa0e7a24bbc3002b6072851ea844eb10/cmake/common.cmake#L118), you can see that our Clang-Tidy checks are different depending on whether we are building libCellML itself or one of its tests. So, if we wanted to have a `.clang-tidy` file, we would actually need 2 `.clang-tidy` files. This also means that if we ever wanted to change the contents of that file, we would have to remember to update the other one, too, which we could easily forget to do, hence the current approach.

To do `clang-tidy -dump-config` from my configuration will roughly give what is available [`cmake/common.cmake`](https://github.com/cellml/libcellml/blob/639a06f7aa0e7a24bbc3002b6072851ea844eb10/cmake/common.cmake#L118).

**Comment by kerimoyle** [comment]
OK, thanks, but I'm still missing something!  When you run clang-tidy, do you do it from the command line? and with that whole list of flags from the settings line in the first post?  or something else?

**Comment by agarny** [comment]
Are you talking about running Clang-Tidy yourself? If so, you should never have to do that yourself. Our CMake system is such that, if you have Clang-Tidy installed on your system, it will run Clang-Tidy for you, and this using the correct checks.
