### ISSUE TITLE
CMake: hide more distracting variables

### ISSUE THREAD

**Issue by agarny** [cellml/libcellml#285]
If we configure libCellML using `cmake-gui` on Windows or `ccmake` on Linux/macOS, we will see that a variable named `LibXml2_DIR` on Windows or `pkgcfg_lib_PC_LIBXML_xml2` on Linux/macOS. As for some other variables, it would be good to have it set as advanced so that only libCellML-related variables are visible by default.

**Comment by nickerso** [comment]
I think I would generally expect basic configuration options for dependencies to be visible by default...but I could easily be swayed in this :)

**Comment by agarny** [comment]
I believe that, at some point, we agreed that we should only see libCellML-related settings.

Also, personally, I like things to be clean. So, when configuring libCellML, well... I want to configure libCellML itself, not its dependencies which I assume where properly handled by our CMake file. If that's not the case, then ok I go into advanced mode and deal with them there.

**Comment by hsorby** [comment]
I would like to only see LIBCELLML_ type  variables in my CMake interface.  There is generally not a lot one can configure with the dependencies and it seems best fit as an advanced configuration option to me.

**Comment by MichaelClerx** [comment]
Agreed! Ideally the standard options are just things you can add on / leave out, ways to configure libcellml but not stuff that can break it

**Comment by nickerso** [comment]
The only problem is that this would force Windows users to toggle to the advanced options in order to be able to build libCellML (there is no standard install of a suitable libXML on Windows, right?). Unless we add a `LIBCELML_LIBXML_DIR` variable...

**Comment by agarny** [comment]
I am against having `LIBCELML_LIBXML_DIR` only so that Windows users don't have to toggle the advanced options. On Windows, people will anyway have to get their hands dirty (e.g. have to install our recommended `LibXml2` libraries), so I would rather keep things clean for the majority of people.

**Comment by nickerso** [comment]
Define majority? :)

A single non-libcellml variable is all that is currently needed for a windows user to build libcellml and use it in their project. Another one for SWIG is needed if you want Python bindings, I think, but I'm happy for Python bindings to be an advanced option. 

libxml is a hard dependency for libcellml, you simply can't build the library without it. It is not an advanced option for the user to define where libxml can be found on their system. Basic "get up and running" documentation should not start with "and now toggle the advanced options, don't mess with anything other than ... "

Also, I'm definitely not suggesting that we have a `LIBCELLML_LIBXML_DIR` variable, that should have had the :-) appended!

**Comment by agarny** [comment]
Majority in terms of platforms: 2 against 1. Otherwise, there is also the majority in terms of 3 against 1 when it comes to this issue. :)

**Comment by nickerso** [comment]
Linking to #286...
