### ISSUE TITLE
Units::addUnit intended behaviour is not clear?

### ISSUE THREAD

**Issue by kerimoyle** [cellml/libcellml#292]
Hi all

Going through where different aspects are read and validated, I found the function Units::addUnit has some bits which confuse me (see 19.3.1.1): 

> The prefix term is a conceptual property of unit elements.  If the unit element does not have a prefix attribute information item, the prefix term SHALL have value 0.0.  If the prefix attribute information item has a value which is an integer string, then the value of the prefix term SHALL be the numerical value of that string.  Otherwise, the prefix attribute information item MUST have a value taken from the ‘Name’ column of the Prefix values table, and the prefix term SHALL have the value taken from the ‘Value’ column of the same row.

I'm not sure about some things:

1. In the addUnit function all roads lead to the same place (ie: setting u.mPrefix=prefix, or not setting it but then gets the 0.0 default anyway), so I'm not sure what it's intended to do?
2. If we're expecting an integer string to be present, why do we read it as a double (std::stod)?
3. Why compare a double to 0.0 (dodgy anyway)? If prefixDouble == 0.0 then no prefix is set (but the default value should be 0.0 in any case?)

```
    Unit u;
    u.mReference = reference;
    // Allow all nonzero user-specified prefixes
    try
    {
        double prefixDouble = std::stod(prefix);
        if (prefixDouble != 0.0) {
            u.mPrefix = prefix;
        }
    } catch (std::invalid_argument&) {
        u.mPrefix = prefix;
    } catch (std::out_of_range&) {
        u.mPrefix = prefix;
    }
```
Any guidance appreciated ... thanks :)

**Comment by hsorby** [comment]
The default value is the empty string, a prefix of 0.0 does not get written out.

So we are allowing any prefix to be set whether it is valid or not is a question for the validation to answer at a later date.  

There is nothing dodgy about comparing a double to 0.0 it is a number that can be tested for exactly.

**Comment by hsorby** [comment]
In my opinion the best way to understand the workings is through the tests and not the implementation.  You should write a test that sets the expected output that you want to observe from a given input and then compare that expectation with the actual output.  If there is a discrepancy then fix the implementation. 

This is a grossly hashed definition of test driven development.

**Comment by kerimoyle** [comment]
Haha, thanks Hugh :) I generally understand test driven development, but I still don't quite know how I'd write a test for whether the code is taking lots of lines to not do anything ...  Good to know it's not intending to do any validation here though - I'll check it's being done on the validation side instead. Thanks :)
