### ISSUE TITLE
Checks on validation at load/update/validate

### ISSUE THREAD

**Issue by kerimoyle** [cellml/libcellml#293]
There have been a few threads in the past (and distant past) about validation so I thought I'd try and pull them all together here:
- https://github.com/cellml/libcellml/issues/118
- https://github.com/cellml/libcellml/issues/280
- https://github.com/cellml/libcellml/issues/261

I've spent the last couple of days going through the libcellml code to find where and when the different parts of the specifications were enforced.  These are added as tags that generate a doxygen section with the link to the specifications chapter which refers to them (instructions/results at the end of this novel, and it's a work in progress ...).

Before I go any further I want to know from y'all whether there's been consensus on:
- *When* should validation happen?  At load?  At export?  On demand?  All of them?  Some other time?
- *What* should it check?  Just that the correct tags are present in the text of the xml file, or that the underlying intention is followed too? (ie: https://github.com/cellml/libcellml/issues/261) or where we say that "the value of this name attribute must be a valid identifier" etc or just check that there's an attribute called "name="?
- Should the validation check that things specified *make sense* (eg: at present both the specificatons and the code allow negative order integers ... which doesn't really mean anything ...?) or just follow the rules?
- Finally should all these checks be done in the *same way* for all of the different elements and parts?  At present the Validator checks some of them but not others, some others are checked when a model is loaded through the Parser, and others I'm still looking for where/if they're checked. Between the two places there is a lot of coverage, it's just not consistent so I wondered if there was a rationale for how different parts were treated or whether it was a work in progress?

Thoughts and guidance appreciated while I get my head around everything. Thanks! :)

ps - to see the output, either see the (sketchy) files in here:  [validation_coverage_2019.3.27.zip](https://github.com/cellml/libcellml/files/3014357/validation_coverage_2019.3.27.zip) or 
get my [validation branch](https://github.com/kerimoyle/libcellml-keri/tree/validation) and manually add the aliases below to the generated Doxyfile before you run doxygen. The chapters then appear properly under the Related Pages link.  

```
ALIASES                = "cellml2_2=\xrefitem CellML2_2 \"CellML2_2\" \"CellML 2.0: 2. General Matters \"" 
ALIASES				   += "cellml2_3=\xrefitem CellML2_3 \"CellML2_3\" \"CellML 2.0: 3. Data representation \"" 
ALIASES				   += "cellml2_4=\xrefitem CellML2_4 \"CellML2_4\" \"CellML 2.0: 4. Model elements \""
ALIASES				   += "cellml2_5=\xrefitem CellML2_5 \"CellML2_5\" \"CellML 2.0: 5. Import elements \""
ALIASES				   += "cellml2_6=\xrefitem CellML2_6 \"CellML2_6\" \"CellML 2.0: 6. Import-units elements \""
ALIASES				   += "cellml2_7=\xrefitem CellML2_7 \"CellML2_7\" \"CellML 2.0: 7. Import-component elements \""
ALIASES				   += "cellml2_8=\xrefitem CellML2_8 \"CellML2_8\" \"CellML 2.0: 8. Units elements \""
ALIASES				   += "cellml2_9=\xrefitem CellML2_9 \"CellML2_9\" \"CellML 2.0: 9. Unit elements \""
ALIASES				   += "cellml2_10=\xrefitem CellML2_10 \"CellML2_10\" \"CellML 2.0: 10. Component elements \""
ALIASES				   += "cellml2_11=\xrefitem CellML2_11 \"CellML2_11\" \"CellML 2.0: 11. Variable elements \""
ALIASES				   += "cellml2_12=\xrefitem CellML2_12 \"CellML2_12\" \"CellML 2.0: 12. Reset elements \""
ALIASES				   += "cellml2_13=\xrefitem CellML2_13 \"CellML2_13\" \"CellML 2.0: 13. When elements \""
ALIASES				   += "cellml2_14=\xrefitem CellML2_14 \"CellML2_14\" \"CellML 2.0: 14. Math elements \""
ALIASES				   += "cellml2_15=\xrefitem CellML2_15 \"CellML2_15\" \"CellML 2.0: 15. Encapsulation elements \""
ALIASES				   += "cellml2_16=\xrefitem CellML2_16 \"CellML2_16\" \"CellML 2.0: 16. Component-ref elements \""
ALIASES				   += "cellml2_17=\xrefitem CellML2_17 \"CellML2_17\" \"CellML 2.0: 17. Connection elements \""
ALIASES				   += "cellml2_18=\xrefitem CellML2_18 \"CellML2_18\" \"CellML 2.0: 18. Map-variables elements \""
ALIASES				   += "cellml2_19=\xrefitem CellML2_19 \"CellML2_19\" \"CellML 2.0: 19. Interpretation of CellML models \"" 
```

**Comment by hsorby** [comment]
When is easy it should happen on demand.  Definitely not on load or export, the user is fully allowed to load or export invalid CellML.

**Comment by hsorby** [comment]
What it should check is where the document under validation fails to conform to the specification and report any such occurrences (as errors).  To do this it has to follow the intent???  the specification should unambiguously state what the definition is.

**Comment by hsorby** [comment]
Negative orders do make sense, a more negative order comes before other orders less negative.

**Comment by hsorby** [comment]
The whole thing is in progress so don't stress on that.  The validation should only happen on demand, any work done on load/import is not validation it is just handling input that it cannot assign to the relevant property.  If I try and set the text 'bob' to a numerical value this will fail and no value is applied to the property.  It will get ignored.

**Comment by kerimoyle** [comment]
OK, great.  Knowing it doesn't happen on load/export makes a big difference, thanks :) 
Re the order thing, it still seems a bit odd to me, especially when read with this (from 19.11.2): 

> All reset elements SHALL be considered sequentially for the connected variable set (see Interpretation of map_variables) to which the referenced variable belongs. The sequence SHALL be determined by the value of the reset element’s order attribute, lowest (least positive (?!) ) having priority.

It's just my own presumption that if I set something with an order of 0 I'd have expected it will be the first thing to happen. I wouldn't have expected to have to search for other orders all the way back to negative inf to find out which happened first.  Live and learn I guess ...

**Comment by MichaelClerx** [comment]
We did discuss that at one point!
I think the consensus was that a sensible model would probably have orders like 1, 2, 3, etc. But that you may want to hack in an order -1 at some stage to override these.
So we're leaving a sensible choice of order integers to the user

**Comment by hsorby** [comment]
I think the sensible choice for order integers is to leave them with decent gaps 100, 200 so other modellers are able to put in resets where they want.  If you put orders like 1, 2, 3 there is no way for you to reset something at order 2.5.

**Comment by kerimoyle** [comment]
Another conceptual question:  If there is no current mechanism in the code for an invalid model configuration to be created, do we need to validate that it hasn't? ie: if an invalid statement is ignored at parse/load time and therefore filtered out, do we need to check it later on as well or do we assume that our current mechanisms for model creation/editing are the only ones that will ever exist?   
For example: 4.2.3 "a model element must not contain more than one encapsulation element"?  As far as I can tell, encapsulations are created/loaded through 
`Parser::ParserImpl::loadEncapsulation(const ModelPtr &model, const XmlNodePtr &node) `
which does a whole bunch of error checking, including looking in the model element for more than one encapsulation element.  So, since there's no (current) way for the more-than-one encapsulation item to be put into a model, do we need to verify later on that it hasn't occurred in some other (not yet possible) way?  The same goes for other things like the unit multiplier and exponent being a real number (ignored and error thrown by the parser if it's not valid, but not checked when the validateModel is called) etc.

**Comment by hsorby** [comment]
The validation and loading are independent beasts.  The validation should not be assuming how the load/parsing deals with the world.

So, no.

**Comment by kerimoyle** [comment]
Hi again
Does this mean that we should make the Validator class a `friend` of pretty much everything else so that the validator can work independently of the parser and other access functions?  

For example: I want to validate that unit multiplier and exponent are real numbers, so want to write a test setting `mMultiplier="not a number string"` or `mExponent = "also not a number string"`.  As far as I can tell, I can't get these values into the Unit without going through the parser (which has its own protection inside `Parser::ParserImpl::loadUnit`) or calling one `Units::addUnit` (which also protects itself by not permitting strings as arguments).

So, if the validator and its tests need to stand alone, does it need to be able to access private members of the classes it's testing?  And if not, what's the best way to set an invalid string for the multiplier or exponent so we can test it?  Sorry if this is a silly question - I've been going around in circles on it for ages!

**Comment by hsorby** [comment]
The tests work against the external API.  You do not concern yourself with the implementation.  The tests define what you expect to get from the given inputs it is that simple.  So you do not want to test setting `mMultiplier = "not a number string";` as a test writer you don't know about `mMultiplier`.

This is why we have the code coverage test.  Every line of code must be used this gives us a high degree of confidence that our code is working as expected.  It certainly tells us that our code is working on all the tests we have devised.

You will find that the validator is not able to validate some rules because the API does not allow you to set strings for multipliers and exponents.  This is an artefact of the translation from the specification to a typed language.  Thus some of the validation becomes inherent.

**Comment by hsorby** [comment]
Having thought further about this if I was asked to deal with the following model:

```
    const std::string input_model =
            "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
            "<model xmlns=\"http://www.cellml.org/cellml/2.0#\">"
                "<units name=\"my_unit\">"
                    "<unit multiplier=\"a string that cannot be considered a number\"/>"
                "</units>"
            "</model>";
```

I would expect the following:

```
    libcellml::Parser parser;
    libcellml::Validator validator;

    libcellml::ModelPtr model = parser.parseModel(input_model);
    validator.validateModel(model);

    EXPECT_EQ(1, parser.errorCount());
    EXPECT_EQ(0, validator.errorCount());
```

That is I expect the parser to capture the non-conformance of the model to the spec.

We have to remember that we are modelling the domain in libcellml and not the spec. which is written with XML in mind.  So there will be cases where the validator simply won't be able to report some of the rules defined in the spec.

**Comment by kerimoyle** [comment]
Got it now :)  This was what I meant earlier about relying on the behaviour at load/parse time for some of the validation stuff.  Much clearer (and a whole lot less to do ...) this way around.  Thanks!
