### ISSUE TITLE
Validator::validateModel returns false positive for component imports?

### ISSUE THREAD

**Issue by kerimoyle** [cellml/libcellml#298]
I've found an error message I didn't expect when validating imported components.  Have a peek at this test:
```
    libcellml::Validator v;
    libcellml::ModelPtr m = std::make_shared<libcellml::Model>();
    m->setName("model_name");

    // Valid component import
    libcellml::ImportSourcePtr imp = std::make_shared<libcellml::ImportSource>();
    imp->setUrl("some-other-model.xml");
    libcellml::ComponentPtr importedComponent = std::make_shared<libcellml::Component>();
    importedComponent->setName("valid_imported_component_in_this_model");
    importedComponent->setSourceComponent(imp, "component_in_that_model");
    m->addComponent(importedComponent);
    v.validateModel(m);
    EXPECT_EQ(0u, v.errorCount());

    // Valid component import ??
    libcellml::ImportSourcePtr imp5 = std::make_shared<libcellml::ImportSource>();
    imp5->setUrl("yet-another-other-model.xml");
    libcellml::ComponentPtr importedComponent5 = std::make_shared<libcellml::Component>();
    importedComponent5->setName("another_valid_imported_component_in_this_model");
    importedComponent5->setSourceComponent(imp5, "new_shiny_component_ref");
    m->addComponent(importedComponent5);
    v.validateModel(m);
```
They are, as far as I can see, two imports, from different places to different components, but I get an error message "Model 'model_name' contains multiple imported components from 'yet-another-other-model.xml' with the same component_ref attribute 'new_shiny_component_ref'."`
because of this code inside Validator::validateModel:
```
if (model->componentCount() > 0) {
       ...
        for (size_t i = 0; i < model->componentCount(); ++i) {
            ComponentPtr component = model->getComponent(i);
            std::string componentName = component->getName();
            if (componentName.length()) {
                if (component->isImport()) {
                    std::string componentRef = component->getImportReference(); 
                    std::string importSource = component->getImportSource()->getUrl(); 
                    bool foundImportError = false;
                    ... 
                    if ((componentImportSources.size() > 0) && (!foundImportError)) {
                        if ((std::find(componentImportSources.begin(), componentImportSources.end(), importSource) - componentImportSources.begin())
                         == (std::find(componentRefs.begin(), componentRefs.end(), componentRef) - componentRefs.begin())){

// ***** Enters this loop because the new component/ref is *not* found in either list ... ? *****

                            ErrorPtr err = std::make_shared<Error>();
                            err->setDescription("Model '" + model->getName() +
                                                "' contains multiple imported components from '" + importSource +
                                                "' with the same component_ref attribute '" + componentRef + "'.");
                            err->setModel(model);
                            err->setRule(SpecificationRule::IMPORT_COMPONENT_REF);
                            addError(err);
                        }
                    }
                    // Push back the unique sources and refs.
                    componentImportSources.push_back(importSource);
                    componentRefs.push_back(componentRef);
                }
```

Is this expected behavior or am I missing something?

**Comment by agarny** [comment]
Hmm, the libCellML code looks reasonable to me, so I would indeed say that there is a problem with the validator.

**Comment by nickerso** [comment]
good catch, looks like the validation code is wrong. Need to check this code more thoroughly as I don't see how that could ever work. The test looks fine and should be valid.

**Comment by hsorby** [comment]
Yup, add the test and correct the implementation.  It would be just great to have this resolved in a PR.

**Comment by kerimoyle** [comment]
Ok, all fixed in my validation branch.  Will do a pull request in the next day or so.

**Comment by kerimoyle** [comment]
Closing as fixed in #304.

**Comment by hsorby** [comment]
We don't close the issue until the code in this repository actually has the fix.  That is to say once the PR that addresses this issue is merged.  Hopefully this is done when the PR is merged but often this is forgotten and we have to manually come back and close issue(s) addressed by a PR.

**Comment by kerimoyle** [comment]
Ah, ok.  Sorry, I was just working my way through the issues list :)

**Comment by kerimoyle** [comment]
Just checking this again I think that the validation test should be removed completely ...  see discussion #280 because:
> Yup! For example, a model might have 3 copies of some imported component
Thoughts?

**Comment by agarny** [comment]
> Just checking this again I think that the validation test should be removed completely ... see discussion #280 because:
> 
> > Yup! For example, a model might have 3 copies of some imported component
> > Thoughts?

Disagreed, if anything the validation test should be stricter (see discussion #280 indeed).
