### ISSUE TITLE
Validating whitespace-only cn nodes not in spec?

### ISSUE THREAD

**Issue by kerimoyle** [cellml/libcellml#299]
Hi all
In the function `void Validator::ValidatorImpl::validateAndCleanMathCiCnNodes` it will generate an error message on whitespace-only attributes:

```
/// @cellml2_14 14.? Check that names of children are not whitespace only
ErrorPtr err = std::make_shared<Error>();
err->setDescription("MathML " + node->getName() + " element has a whitespace-only child element.");
err->setComponent(component);
err->setKind(Error::Kind::MATHML);
mValidator->addError(err);
```

Just wanted to check whether this was implied by something in the specifications (or whether they need to be explicit?) as I can't find the right section to tag it to? Thanks!

**Comment by agarny** [comment]
This is pure MathML, so I wouldn't expect to find anything about this in the CellML specifications. This being said, when it comes to `ci` and `cn` MathML elements, I wouldn't think it makes sense for them to have a whitespace-only child, hence the error, I think.

**Comment by hsorby** [comment]
As far as I can tell a MathML `ci`or `cn` element can contain text which could be whitespace only.  I guess this is unclearly reporting on 14.1.3.

**Comment by kerimoyle** [comment]
Closing as it seems that no changes are needed.
