### ISSUE TITLE
Duplicate variable permitted in component?

### ISSUE THREAD

**Issue by kerimoyle** [cellml/libcellml#301]
Should this return a validation error?
```
c->addVariable(v);
c->addVariable(v);
```

We catch duplicate variable names in the parser, but not when the functions are called like this - it's just ignored in the validator (and yes, the number of variables in the component is incremented)?

```
void Validator::ValidatorImpl::validateMath(const std::string &input, const ComponentPtr &component)
...
   for (size_t i = 0; i < component->variableCount(); ++i) {
        std::string variableName = component->getVariable(i)->getName();
        if (std::find(variableNames.begin(), variableNames.end(), variableName) == variableNames.end()) {
            variableNames.push_back(variableName);
        }
/// ***** need an else here? *****
    }
...
```

**Comment by agarny** [comment]
I haven't checked the code, but do we really catch duplicate variables names in the parser? As far as I am concerned, the parser should allow that, but the validator should indeed complain about it.

**Comment by hsorby** [comment]
When I run this test I do get errors from the validator.

```
12: CellML identifiers must contain one or more basic Latin alphabetic characters.
12: Variable does not have a valid name attribute.
12: CellML identifiers must contain one or more basic Latin alphabetic characters.
12: Variable '' does not have a valid units attribute.
12: CellML identifiers must contain one or more basic Latin alphabetic characters.
12: Variable does not have a valid name attribute.
12: CellML identifiers must contain one or more basic Latin alphabetic characters.
12: Variable '' does not have a valid units attribute.
```

and also from the parser I do get errors

```
7: Variable '' is missing a required 'name' attribute.
7: Variable '' is missing a required 'units' attribute.
7: Variable '' is missing a required 'name' attribute.
7: Variable '' is missing a required 'units' attribute.
```

What you are looking at there is the maths validation I don't see what that has to do with duplicated variables in a component.

**Comment by hsorby** [comment]
After thinking about this I'm struggling to think why the parsing is doing validation of this sort.  The parser to my mind should just parse as much as it can make sense of and report anything that it couldn't make sense of.

**Comment by kerimoyle** [comment]
Whoops, my bad!  The validator does return an error of the form "Component 'componentName' contains multiple variables with the name 'C'. Valid variable names must be unique to their component."  I missed it earlier because it's listed first in the error list rather than last as I was expecting ... sorry for the confusion :(
