### ISSUE TITLE
Remove validation code form parser.

### ISSUE THREAD

**Issue by hsorby** [cellml/libcellml#302]
Currently the parser has taken upon itself to do some validation.  I think the parser needs to concentrate more on parsing the xml and leaving the validation to the validator.

**Comment by agarny** [comment]
Fully agree with that!

**Comment by kerimoyle** [comment]
It sounds like you have something specific in mind ... ?

**Comment by hsorby** [comment]
Nope, I just want the parser to concentrate on parsing and leaving validation to the validator.  Should be an easy fix.

**Comment by kerimoyle** [comment]
You'll know from my previous comments elsewhere that I don't yet have a good feeling for what should be a parse error and what should be a validation error ... so ... 

- Should it be possible to parse a file which contains a valid model _and_ a bunch of unrecognised rubbish, and print a valid model from it without encountering an error?  Essentially a cleaner for the input?
- Should it be possible to parse an incomplete file without error? By incomplete I mean by cellml standards, not xml (eg empty encapsulation)

Reading through the parser there are several different kinds of things which create an error, but which could perhaps become a warning instead (if we make warnings possible, see #314):
- presence of unrecognised attributes
- presence of nonwhitespace text (which has no other meaning)
- presence of invalid children of nodes

... and finally, is there consensus on how error messages are constructed?  Some of the time there are single quotes around things specific to the message (eg: component 'myComponent' has a problem) and sometimes no quotes used?

Thanks :)
https://github.com/kerimoyle/libcellml-keri/tree/remove_validation_from_parser

**Comment by agarny** [comment]
> * Should it be possible to parse a file which contains a valid model _and_ a bunch of unrecognised rubbish, and print a valid model from it without encountering an error?  Essentially a cleaner for the input?

For me, a parser must ensure that a CellML file's syntax is fine while a validator ensures that its semantics is. So, if a CellML file contains unrecognisable rubbish then I would expect the parser to report it.

> * Should it be possible to parse an incomplete file without error? By incomplete I mean by cellml standards, not xml (eg empty encapsulation)

Based on what I have just said above: yes.

> Reading through the parser there are several different kinds of things which create an error, but which could perhaps become a warning instead (if we make warnings possible, see #314):
> 
> * presence of unrecognised attributes
> * presence of nonwhitespace text (which has no other meaning)
> * presence of invalid children of nodes

Agreed, this is actually the approach I took in my own "old" CellML API.

> ... and finally, is there consensus on how error messages are constructed? Some of the time there are single quotes around things specific to the message (eg: component 'myComponent' has a problem) and sometimes no quotes used?

I am not (yet) familiar with that aspect of libCellML, but some consensus is indeed needed.

**Comment by hsorby** [comment]
I am fine with the parser reporting `errors` when it encounters text that it cannot deal with.  We can of course make these `warnings` but I think they should be errors.

**Comment by hsorby** [comment]
> ... and finally, is there consensus on how error messages are constructed? Some of the time there are single quotes around things specific to the message (eg: component 'myComponent' has a problem) and sometimes no quotes used?

Clearly there is no standard to the error descriptions.  I would like to think that names of entities are quoted in descriptions.  We could come up with a standard but that should be a different issue and dealt with in an associated PR.

**Comment by kerimoyle** [comment]
And one more design principle question: For potential validation errors which can *only* enter the model via the parser, where should these be checked?  For example, that the units multiplier is a number?

**Comment by kerimoyle** [comment]
OK, so I've gone through the parser.cpp file and highlighted the areas that could be moved to the validator.    I wanted to check that these changes were in the right direction before changing the tests and the validation?

See comments (search for TODO or REMOVE):  https://github.com/cellml/libcellml/compare/develop...kerimoyle:remove_validation_from_parser?expand=1 

Thanks ... :)

**Comment by nickerso** [comment]
generally looks good. A couple of the bits flagged for removal probably need to stay in the parser - anything working with `encapsulation` or `connection` elements need to be dealt with in the parser (I think). The libCellML data model represents those via the component hierarchy and variable equivalences, so when parsing if a component reference in an encapsulation or a variable reference in a connection can't be found, the hierarchy or equivalence can't be defined - so the error needs to be flagged during parsing. If that makes sense?

**Comment by kerimoyle** [comment]
OK, thanks.  Will leave those bits in and move the rest over :)

**Comment by kerimoyle** [comment]
So I spent the day today going through the parser/validator in detail, and if we can't touch:
- encapsulations
- connections
- resets and whens ...
... then the grand total of 10 lines below can be removed from the `loadVariable ` function.  @hsorby what am I missing ... ? It sounded like there was more to this?

```
    //if (!nameAttributePresent) {
    //    ErrorPtr err = std::make_shared<Error>(variable);
    //    err->setDescription("Variable '" + node->getAttribute("name") +
    //                        "' is missing a required 'name' attribute.");
    //    err->setRule(SpecificationRule::VARIABLE_NAME);
    //    mParser->addError(err);
    //}
    //if (!unitsAttributePresent) {
    //    ErrorPtr err = std::make_shared<Error>(variable);
    //    err->setDescription("Variable '" + node->getAttribute("name") +
    //                        "' is missing a required 'units' attribute.");
    //    err->setRule(SpecificationRule::VARIABLE_UNITS);
    //    mParser->addError(err);
    //}
```
