### ISSUE TITLE
Childless units vs base units?

### ISSUE THREAD

**Issue by kerimoyle** [cellml/libcellml#305]
Hi all
I'm a bit confused about the specs and code around unit children of the units blocks.  The specs say: "8.1.4: A units element MAY contain one of more unit element children" (so they're allowed to be empty? What's the interpretation for that?)... and whether you think that there was anything that should be caught by the validator here:
```
TEST(Validator, setUnitsWithNoChildUnit) {
    libcellml::Validator validator;
    libcellml::ModelPtr m = std::make_shared<libcellml::Model>();
    libcellml::ComponentPtr c = std::make_shared<libcellml::Component>();
    libcellml::VariablePtr v = std::make_shared<libcellml::Variable>();
    libcellml::UnitsPtr u = std::make_shared<libcellml::Units>();
    m->setName("m");
    c->setName("c");
    v->setName("v");
    u->setName("u"); // has name but nothing else ...
    m->addComponent(c);
    m->addUnits(u);
    c->addVariable(v);
    v->setUnits(u);
    validator.validateModel(m);  // this currently returns no errors 
}
```
The reason I'm a bit worried is because of the way we're testing for base units:
```
bool Units::isBaseUnit() const
{
    return unitCount() == 0;    // << So an empty "units" block becomes a "base unit?"
}
```
... and the validator skips over testing any empty units blocks:
```
 if (units->unitCount() > 0) {
        /// @cellml2_8 8.1.4 Validates each unit in units.
        for (size_t i = 0; i < units->unitCount(); ++i) {
            validateUnitsUnit(i, units, unitsNames);
        }
    }
```
I'm trying to figure out:
- whether empty units blocks are really allowed (or whether the MAY should be a MUST)
- if they are allowed, am I safe to change the way that the isBaseUnit() function works to test the name instead of / as well as the child count
- if they're not allowed, am I safe to add an else to the last block of code to return a validation error?

All this is (unfortunately ...) tied to a coverage issue inside the equivalent units testing from https://github.com/cellml/libcellml/pull/304 which I'm trying to sort ... :(

**Comment by MichaelClerx** [comment]
Hi Keri!

The relevant bit of spec is a bit further down, in the interpretation of units section:

> For the purposes of this specification, the “irreducible units” of a model SHALL consist of 1) the units defined in a model that are not defined in terms of other units (i.e. the set of units elements in the CellML model which have no  unit child elements), and 2) built-in irreducible units (those built-in units with ‘-’ in the ‘Unit Reduction...’ column of the Built-in units Table) referenced by variables or other units in the model.

What that's saying is that a base unit is any unit that is either (1) a built-in base unit (e.g. an SI base unit) or (2) a user-defined base unit - which is a unit without any child unitses

This probably should be a bit more explicit than hidden between parentheses somewhere!

So:

> Whether empty units blocks are really allowed

Yes

> if they are allowed, am I safe to change the way that the isBaseUnit() function works to test the name instead of / as well as the child count

Not sure why the name would help?

**Comment by kerimoyle** [comment]
Thanks @MichaelClerx ! So as it's possible for users to define new base units other than the built-in ones (ampere, candela, kelvin, kilogram, metre, mole, and second) then we need to test the variable equivalence against an arbitrary number of irreducible units, rather than just the built-ins? ... whoops, I have some work to do!
