### ISSUE TITLE
Printer: use indentation and line feeds

### ISSUE THREAD

**Issue by agarny** [cellml/libcellml#309]
Right now, our printer always generates two lines. One for the XML version and encoding we want to use, i.e. `<?xml version=\"1.0\" encoding=\"UTF-8\"?>` and another for the CellML model itself, no matter how long it is.

However, I feel like it might be nice to have our printer output use indentation and line feeds, so that things look a bit better (and are easier to `diff`, if needed). This would also prevent us from having "fake" indentations in our tests, e.g.
```
"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
"<model xmlns=\"http://www.cellml.org/cellml/2.0#\">"
    "<component name=\"parent_component\"/>"
    "<component name=\"child1\"/>"
    "<component name=\"child2\"/>"
    "<component name=\"child3\"/>"
    "<encapsulation>"
        "<component_ref component=\"parent_component\">"
            "<component_ref component=\"child1\"/>"
            "<component_ref component=\"child2\"/>"
            "<component_ref component=\"child3\"/>"
        "</component_ref>"
    "</encapsulation>"
"</model>";
```
while I would personally rather have (note the two-space indentation; this is the indentation used by libxml2):
```
"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
"<model xmlns=\"http://www.cellml.org/cellml/2.0#\">\n"
"  <component name=\"parent_component\"/>\n"
"  <component name=\"child1\"/>\n"
"  <component name=\"child2\"/>\n"
"  <component name=\"child3\"/>\n"
"  <encapsulation>\n"
"    <component_ref component=\"parent_component\">\n"
"      <component_ref component=\"child1\"/>\n"
"      <component_ref component=\"child2\"/>\n"
"      <component_ref component=\"child3\"/>\n"
"    </component_ref>\n"
"  </encapsulation>\n"
"</model>\n";
```
This would also make things better when formatting using Clang-Format (see issue #284).

**Comment by hsorby** [comment]
I don't mind this change.  Having given it some thought I don't mind either output.  If I was going to do a `diff` on a CellML file I would use a node based diff and not line based so the indentation wouldn't effect the results either way.
