### ISSUE TITLE
A component can have child components?

### ISSUE THREAD

**Issue by agarny** [cellml/libcellml#311]
Looking at the [`Component.addChildrenAndSerialise` test](https://github.com/cellml/libcellml/blob/88e9ae60b6ae371cfd42799a886f1545a4895451/tests/component/component.cpp#L106), we can see that components `c0`, `c1`, `c2` and `c3` are created, and that `c2` is added as a child component of `c1`, `c1` as a child component of `c0`, and `c3` as a child component of `c2`. Am I understanding this right?

If that's the case, then could someone tell me how come / why a component can have a child component? I am clearly not talking from an API viewpoint since I can indeed see that `Component` inherits from `ComponentEntity` (as does `Model`) and that `ComponentEntity` has the `addComponent()` method, but rather from a pure CellML viewpoint.

Unless I missed something, I am too tired, etc., a component cannot have child components...!?

**Comment by nickerso** [comment]
That's how the libcellml data model represents encapsulation. Is that what
you are asking?

**Comment by agarny** [comment]
> That's how the libcellml data model represents encapsulation. Is that what you are asking?

Oh, ok, I definitely didn't think of that, but thinking of it, it makes sense indeed. I should really try to stay away from "raw" CellML.
