### ISSUE TITLE
Replace the `Error` class with the `Issue` class with a type (e.g. error, warning, hint)

### ISSUE THREAD

**Issue by kerimoyle** [cellml/libcellml#314]
There are a couple of areas which would benefit from having non-fatal warnings raised (ie without implying an invalid model or stopping the operation):
- multipliers in the units of equivalent variables (currently unchecked)
- multipliers in units in the maths (currently unchecked)
- validation defaulting to 0-depth when there is no file location specified (see #280)
- (perhaps?) where the parser encounters something which will fail later validation.  Would this work as a response to #302 @hsorby? 

It would be nice to be able to return useful warnings to the user which do not affect the final validity of the model, either by mimicking the Error module as a separate Warning module, or by introducing a severity level to the errors (all current ones become fatal by default).

**Comment by agarny** [comment]
> - (perhaps?) where the parser encounters something which will fail later validation.  Would this work as a response to #302 @hsorby? 

I don't think I would want that kind of "warning" when parsing a model. If I want "warnings" that are related to validation, well... I just ask for the model to be validated...

> It would be nice to be able to return useful warnings to the user which do not affect the final validity of the model, either by mimicking the Error module as a separate Warning module, or by introducing a severity level to the errors (all current ones become fatal by default).

Personally, rather than have an `Error` class, I would probably have an `Issue` class and then have a `type` of issue, which could be `warning`, `error`, `fatal` or whatever we deem necessary.

**Comment by hsorby** [comment]
Are you thinking this is purely to do with the parser?

**Comment by hsorby** [comment]
#302 is reminding us that we don't want any validation code in the parser so a big no to doing validation in the parser.

**Comment by hsorby** [comment]
I like the idea of having an `Issue` class that can have levels `warning` or `error` or whatever but I don't think this should be work done that appears in the  validation PR.

**Comment by agarny** [comment]
> I like the idea of having an `Issue` class that can have levels `warning` or `error` or whatever but I don't think this should be work done that appears in the validation PR.

Agreed. If anything, that work ought to be merged in before validation does.

**Comment by hsorby** [comment]
At this point due to the large and significant changes that the validation PR is going to have it might be prudent to do this after the merge.

**Comment by kerimoyle** [comment]
It's a bit chicken and egg, but either option (upgrade to Issue before or after changes to validation) isn't a deal breaker either way - I guess it depends on when you want the validation branch to merge.

> #302 is reminding us that we don't want any validation code in the parser so a big no to doing validation in the parser.

> I like the idea of having an `Issue` class that can have levels `warning` or `error` or whatever but I don't think this should be work done that appears in the validation PR.

Yes, absolutely, and that's why I bring it up - while removing validation stuff from the parser it occurred to me that there were useful error messages there that could perhaps become warnings instead?  There are a few different kinds of errors being detected and reported in the parser at present:
- some are pure validation errors, these will move to the validator
- some are parse errors which are fatal as the xml is insufficient to interpret -> these remain fatal errors in the parser
- some are parse errors which relate to cellml contents but not syntax, so could be fixed by the user with the model open (empty encapsulation, missing variable, etc).  Since these are currently _not saved_ to the model (how could they be, the thing the parser is attempting to save is wrong), they cannot be checked by the validator in a meaningful way.  The validator can return an error saying "I'm missing the 'name' attribute", but it can't return "but there was an attribute called 'namee' which I didn't understand" as that's not saved anywhere.  I think that the latter message from the _parser_ is more useful to the user for debugging, but will also be raised in the validator as an error?
- some are validation errors (I think) but only can occur through the parser: eg the representation of numbers for the unit multiplier, exponent, prefix.  Since the other functions for setting these have a limited argument list, the user can't set a `multiplier="Z"` anywhere except the parser.  But it's really a validation issue to check that `multiplier `is a real number ... so where should that check happen?

I guess I'm still trying to get my head around how this will be used later - what is the significance of an error item being added to the parser? After parsing a file I presume that the user sees the error messages and can edit then?

> Are you thinking this is purely to do with the parser?

No, I think throughout would be useful.  We need levels of issue in the validator too in order to warn of 0-depth import checking, for example.  Other warnings for common gotchas (eg: use of absolute path names in href addresses make the model non-portable, mismatching multipliers in equivalent units etc) could be useful too?

**Comment by hsorby** [comment]
Closing, the Issue class has now replaced the old Error class.
