### ISSUE TITLE
Variable: add an `isEquivalentVariable()` method

### ISSUE THREAD

**Issue by agarny** [cellml/libcellml#321]
Right now, we have all sorts of methods dealing with equivalent variables, but there is none to actually checking whether a variable is equivalent to another through several layers of mapping.

For example, in [this model](https://github.com/cellml/libcellml/files/3164762/two_variables_of_integration.txt):
- `main.time` and `sub.time` would be equivalent;
- `main.time` and `sub_sub.time` would be equivalent; and
- `main.time` and `sub_sub_sub.time` would **NOT** be equivalent.

A quick implementation of such a method can be found [here](https://github.com/agarny/libcellml/commit/742be58f2df24803b1112d616651228c3b90b77b).

**Comment by kerimoyle** [comment]
Hi Alan
There's code in the validator (or will be when the 304 PR goes through) to check this - should it be moved? or removed? or something else?

**Comment by agarny** [comment]
If we agree that such a method should be in libCellML (@hsorby, @nickerso, @MichaelClerx?) then I will create a PR for it.

**Comment by hsorby** [comment]
I think that this is a failing of the `hasEquivalentVariable` method, in my opinion this method should return `true` for this model.

**Comment by agarny** [comment]
I wasn't sure whether `hasEquivalentVariable()` was meant to do what it currently does or whether it should have done what "my" `isEquivalentVariable()` method does. Ok, I am going to modify `hasEquivalentVariable()` accordingly and generate a PR.

**Comment by MichaelClerx** [comment]
Is this done then?

**Comment by hsorby** [comment]
Yes I believe it is.  Please do re-open if this is not the case.
