### ISSUE TITLE
General: replace `getXXX()` with `xxx()`

### ISSUE THREAD

**Issue by agarny** [cellml/libcellml#325]
Our getters are currently named `getXXX()`, but why not simply have `xxx()`? Nothing major, clearly, it's just that it's common practice.

**Comment by hsorby** [comment]
I did it because I prefer it.  Back in the day it was all `getXxx()`, and `setXxx()` then people went with just `xxx()` I have found that I prefer the old way as the two methods match up better.  Clearly this is just a preference.

**Comment by agarny** [comment]
Yes, I remember those "days" with `getXxx()` and was already wondering why not simply use `xxx()`. Agreed, just a preference, but might still be good to do things the "modern" way?... :) Worst case scenario, I would be ok with having both `getXxx()` and `xxx()`.

**Comment by nickerso** [comment]
If it ain't broke, don't fix it? I definitely wouldn't like to see us knowingly add duplicate methods with different names.

**Comment by agarny** [comment]
Well, we have tests, so it can't really break things. :)

In the end, I agree that duplicate methods are not great, hence ok to go with `xxx()`. :)

**Comment by hsorby** [comment]
Yup, definitely one or the other not both.

I don't mind which I'm happy with the status quo but if someone wants to do the work then I'm happy with that too.

**Comment by agarny** [comment]
Ok, will do it, no problem. Will do it once PRs #288 and #310 have been merged in.

**Comment by nickerso** [comment]
Would this have any negative impact on the Python or JS bindings?

**Comment by agarny** [comment]
I guess I will quickly find out when I have a go at it... :)

**Comment by kerimoyle** [comment]
I've preferred the old way too ... just cos you're clearer on what's
happening.

**Comment by agarny** [comment]
There are pros and cons to both approaches, which is the reason I tend to go with the "modern" approach. Nothing worse (so to speak) than having a "new" library that looks "old".
