### ISSUE TITLE
Add use cases demonstrating the modification of an existing model and component encapsulation hierarchy

### ISSUE THREAD

**Issue by nickerso** [cellml/libcellml#33]
Before heading too far down the implementation path of the libCellML object model, we should implement some tests demonstrating the use of libCellML to modify an existing model and component encapsulation hierarchy. See the related discussion thread here: https://groups.google.com/forum/#!msg/libcellml-team/ELvmfQiY7EE/uXwpNayqw_MJ

(current use-case list available at: http://libcellml.readthedocs.org/en/latest/usecases.html)

**Comment by rchristie** [comment]
Looks good to me.
