### ISSUE TITLE
Generic email address for libCellML?

### ISSUE THREAD

**Issue by agarny** [cellml/libcellml#336]
Would it be worth having a generic email address for libCellML? If so, we might want to update `src/bindings/python/setup.in.py` to reference it. (Note: `src/bindings/python/setup.in.py` is currently being worked on in PR #333.)

**Comment by nickerso** [comment]
Lets go with libcellml@googlegroups.com - I've set that up and invited the core development team. Or should we rename it to libcellml-developers or libcellml-contact or some other variant?

**Comment by agarny** [comment]
Simple is sometimes more efficient, so I would stick with that mailing list.

**Comment by nickerso** [comment]
sorted. We can always rename it later if needed.
