### ISSUE TITLE
Rename configure modules to end with .in.cmake.

### ISSUE THREAD

**Issue by hsorby** [cellml/libcellml#337]
When using IDEs the association of a file is generally picked by looking at the suffix of a filename.  With two of the configured CMake modules the filename ends with .cmake.in.  Swapping the order would allow IDEs to detect the correct syntax highlighting and associations.

**Comment by nickerso** [comment]
Seems like a good idea.

**Comment by hsorby** [comment]
It is right!

**Comment by agarny** [comment]
Not sure I like it (it won’t be 100% obvious anymore that we are talking about configurable files), but at the same time I can see the rationale for doing it (incl. for syntax highlighting in some text editors).

**Comment by agarny** [comment]
Closed as a result of PR #338.
