### ISSUE TITLE
Use of Shebang line in Python scripts.

### ISSUE THREAD

**Issue by hsorby** [cellml/libcellml#341]
When we use the shebang line from the Python scripts we open ourselves up to the situation where the file system is Windows and the execution environment is Unix-based.  This is most readily seen when using the Docker image for documentation on a Windows OS.

A solution to this would be to directly drive the Python script with a specific Python interpreter and thus remove the execution of the shebang.

**Comment by MichaelClerx** [comment]
> When we use the shebang line from the Python scripts we open ourselves up to the situation where the file system is Windows and the execution environment is Unix-based.

Doesn't windows just ignore the shebang as a comment?

> with a specific Python interpreter

Wouldn't make it specific, just `python` !

**Comment by hsorby** [comment]
Yes Windows does but with a Docker image that is based in Linux accessing files stored on a Windows OS where the line ending are `\r\n` the executable the Docker image tries to run is `python\r` which is a problem.

Also you can find that the Python that you are using to run something like the coverage test is not the Python you used to build the Python tests against.
