### ISSUE TITLE
Clang-Tidy: may want to make it optional to use it?

### ISSUE THREAD

**Issue by agarny** [cellml/libcellml#347]
Clang-Tidy is clearly worth having, however it makes the build time quite a bit slower. I was therefore wondering whether it wouldn't be worth making it an option? By default, that option would be disabled, which is probably what most people would want.

**Comment by hsorby** [comment]
I don't think most people have it.   How much slower do you think the build is because of it?

**Comment by agarny** [comment]
I have just given it a try using the `develop` branch:

**With Clang-Tidy enabled:**
```
make -j  411.28s user 15.96s system 1020% cpu 41.879 total
make -j  393.41s user 15.20s system 1062% cpu 38.453 total
make -j  403.89s user 15.92s system 1037% cpu 40.477 total
```

**With Clang-Tidy disabled:**
```
make -j  81.31s user 8.52s system 918% cpu 9.777 total
make -j  77.80s user 8.35s system 903% cpu 9.540 total
make -j  78.28s user 8.41s system 911% cpu 9.514 total
```

So, it's roughly four times as slow and that's using `make` (although it's parallel make). So, with `ninja` and `ccache`, it would be even slower.

**Comment by hsorby** [comment]
Didn't expect that, it is a marked increase.

**Comment by hsorby** [comment]
I think at that level of slow down I would have to say that yes it is worth having it disabled by default.

**Comment by kerimoyle** [comment]
Are you able to provide a .clang-tidy file instead of a command-line string (as in #283). If people do choose to use it that would make it a lot easier, and easier to be consistent with what we're doing too (or am I missing something?)

**Comment by agarny** [comment]
See comment [here](https://github.com/cellml/libcellml/issues/283#issuecomment-501897105).
