### ISSUE TITLE
Use cases upto 1.vii

### ISSUE THREAD

**Issue by hsorby** [cellml/libcellml#35]
The use cases we wish to satisfy are:
- manipulation of a model with multi-level component encapsulation hierarchy
  - remove a component
  - change the name of a top-level component
  - change the name of an encapsulated child component
  - replace one component with a new component
  - take a component (remove the component and return it to the user)
  - determine if a component with a given name exists in a model or component
  - determine the number of components encapsulated by a model or component

**Comment by nickerso** [comment]
Resolved by #42.
