### ISSUE TITLE
Code generation

### ISSUE THREAD

**Issue by agarny** [cellml/libcellml#359]
The aim is to come up with a general framework for the generation of code for CellML models.

As a starting point, we want to be able to generate code for any CellML 1.0/1.1 model that has been converted to CellML 2.0 (excluding DAE models).

By default, the framework is to generate C code, but it should be fully configurable so that it can be used to generate other formats, e.g. Python.

**Note:** this issue replaces issue #257.

**Comment by nickerso** [comment]
restricting the scope of this to be code generation for non-DAE CellML 1.0 models, as supported by #360. Extension to this will be worked on in future issues.
