### ISSUE TITLE
CI system: use llvm-cov rather than gcov

### ISSUE THREAD

**Issue by agarny** [cellml/libcellml#375]
Right now, our CI system relies on `gcov` for its coverage test. However, our repository also supports `llvm-cov`. So, we ought to make use of the latter in our CI system. Indeed, `llvm-cov` is more thorough. For example, say that you have the following code:

```
int value = condition ? ifValue : elseValue;
```

then `gcov` will consider that line as covered as long as you have a test for, say, `condition` being `true`. IOW, `gcov` will consider that line as covered even if you don't have a test for `condition` being `false`.

`llvm-cov` will still consider the line has covered, but it will also report one of two regions (for that line) as not being covered.

**Comment by hsorby** [comment]
To make this change the CI would need to understand the output from llvm-cov.  It is fairly straightforward to do this, just takes a bit of processing along with some changes to the CI configuration.

**Comment by hsorby** [comment]
Would we also then need to consider whether we expect all regions to be covered.?

The almost equivalent on gcov is branches but that includes items like has an exception been triggered inside a constructor for a class.  Which we haven't bothered trying to test and I for one have no intention of testing.

**Comment by agarny** [comment]
> Would we also then need to consider whether we expect all regions to be covered.?

If you think of my example [above](https://github.com/cellml/libcellml/issues/375#issue-465033631), I would indeed want to see all regions covered.

**Comment by hsorby** [comment]
I have in a secondary PR against [code coverage](https://github.com/agarny/libcellml/pull/8) which has managed to get full region, line, and function coverage.  So at least this is achievable without having to do an unrealistic amount of work (unlike getting full branch coverage using gcov).

**Comment by hsorby** [comment]
Closing this as we have added LLVM coverage to the CI (as well as gcov coverage).
