### ISSUE TITLE
Any way to make our CI system faster?

### ISSUE THREAD

**Issue by agarny** [cellml/libcellml#376]
Indeed, I find it very slow at the moment. For example, for a recent build:
- [Unit tests](https://autotest.bioeng.auckland.ac.nz/buildbot/libcellml/builders/Tests%20Builder/builds/1232) took 25 mins 10 secs;
- [Memcheck](https://autotest.bioeng.auckland.ac.nz/buildbot/libcellml/builders/Memcheck%20Tests%20Builder%20Ubuntu%2018.04%2064%20Bit/builds/250) took 12 mins 12 secs;
- [Coverage](https://autotest.bioeng.auckland.ac.nz/buildbot/libcellml/builders/Coverage%20Tests%20Builder%20Ubuntu%2018.04%2064%20Bit/builds/250) took 11 mins 32 secs; and
- [ClangFormat](https://autotest.bioeng.auckland.ac.nz/buildbot/libcellml/builders/Clang%20Format%20Test%20Builder%20Mac%20OSX%2010.14/builds/211) took 20 secs.

For comparison, to test libCellML using our Docker file took 3 mins 27 secs. Granted, my computer is faster, etc., but still.

**Comment by hsorby** [comment]
The builds on the Mac OS X platform and Ubuntu platform are serial so we could easily make them parallel.  This might save 50% of the total time?  I should be able to easily make this change in the CI system.

**Comment by kerimoyle** [comment]
Sounds good to me :)

**Comment by hsorby** [comment]
At this time I have made the CI system as I think it can get at this point.  The expected time to finish is now just over 10 minutes.

The major sticking points now are the clang-tidy on macOS and the memory check on Ubuntu.  I can't see a way to make these any faster at this time.  Ideas on making these tasks take less time are welcome.

**Comment by agarny** [comment]
I agree with what you consider to be our sticking points and I am not sure there is much we can do about them.

Are we using `Ninja` and `clcache`/`ccache`?

**Comment by hsorby** [comment]
We are not using `Ninja` but we are using `clcache/ccache`.  I don't think switching to `Ninja` will give us a significant reduction in the CI completion time.

**Comment by agarny** [comment]
Agreed, but still every little helps. :)
