### ISSUE TITLE
Return references or pointers?

### ISSUE THREAD

**Issue by hsorby** [cellml/libcellml#38]
Now that we are a little way through the implementation and have had a look at how the API is starting to form, there appears to be a difference of opinion on what should be returned through the API:
- references, or
- pointers.

This issue is to decide which route we should take.

This issue was raised in pull request #36

**Comment by hsorby** [comment]
references for me.

**Comment by rchristie** [comment]
For me: neither; I prefer safe handles to objects e.g. smart pointers.

Giving references or raw pointers to internal objects is not safe as there is no guarantee on the lifetime of the referred-to object. You can cause memory corruption simply by using the API; I don't expect a high level API such as libCellML to be that unsafe, but YMMV.

The currently proposed APIs for removing components are not very object oriented, and are flawed:
- indexes can become invalid with other re-ordering methods
- names are not necessarily unique

Why I'm mentioning this here is that I'd expect to supply an actual object handle to remove. This can't be done safely with a reference as the caller is left with an invalid reference. Addresses of pointers could be passed and the pointer cleared, but this is inelegant.

If you work with handles at all times you need fewer APIs:
- one API to get by index
- one API to get by name
- one remove API taking a handle
- take = get + remove

**Comment by nickerso** [comment]
My vote is for references.

**Comment by agarny** [comment]
@rchristie makes some good points. I would be curious to see some sample code for the different approaches.

This aside, and FWIW, it looks (from a very quick glance at their source code) like both [libSBML](http://sbml.org/Software/libSBML) and [libSEDML](https://github.com/fbergmann/libSEDML/) return pointers. I know, it doesn't mean that we should do the same, but for someone coming from SBML and interested in CellML, it might make things easier if we did.

Anyway, at this stage, my vote is still for pointers.

**Comment by nickerso** [comment]
@mirams @jonc125 @mtcooling - would be good to get this resolved, so please express an opinion :)

**Comment by mirams** [comment]
Shared pointers would seem to make sense to me, so that things don't disappear if the API goes out of scope.

**Comment by jonc125** [comment]
I'd also prefer safe handles, and smart pointers are the easiest standard solution. It's easy to envisage a user creating a component, adding it to a model, later deleting the model (or even just removing the component from the model), and wondering why accessing the component now causes the program to crash.

**Comment by nickerso** [comment]
It is sounding like it is not a simple choice between references and pointers, but rather a "safe API" vs one that expects users to know what they are doing. It would be useful if anyone wanted to take the current tests (perhaps those from pull request #36) and edit them to show how you'd imagine the API working with shared/smart pointers. @hsorby and I are happy with the current state of the tests (& implementation) and, for me at least, I'm really struggling to see how the use of smart handles to objects is any benefit for such a low-level library that libCellML should be. Getting actual code that shows how others think things should work would be a great help and make sure we are all talking about what we think we are :)

**Comment by mtcooling** [comment]
I've never regretted making things more robust than I first thought necessary, especially for an API.

**Comment by hsorby** [comment]
If I have this right, we have:
 1 - for pointers
 2 - for references
 3 - for smart pointers
 1 - for robust

For me at this stage of the project we don't need to have smart pointers as the memory management at this point really isn't that complex.  If in the distant future tool developers using libcellml are having difficulties with managing memory and start asking for a smart pointer interface we could implement it then.  With our test cases refactoring will generally be straightforward and moving from the current reference based implementation to smart pointers will be manageable.

**Comment by hsorby** [comment]
Some Q&A I have had with myself:

 Q. Do I want to rewrite the code using smart pointers? A. No, C++ is a programming language for people who know how to program in C++, I expect a tool developer to have a good level of competency with C++.  If they don't they will run into problems, there is nothing I can do about that.
 Q. Does the documentation adequately explain the code? A. Yes, If a tool developer actually reads the documentation they should be able to use the library without resorting to looking at the source code.  If tool developers are looking at the source code then more documentation needs to be written.
 Q. Is it a good idea to pass smart pointers through a shared object API? A. Probably not.  There will be some issues todo with binary compatibility that could appear when distributing binaries.  Then again if I start concerning myself with ABI then I should probably be offering a C++ header only interface to a C API, blech!

It is my opinion that we should close this issue with the decision to continue with a reference based API for the foreseeable future for two reasons.
1. No one is going to write the alternative smart pointer implementation at this point.
2. We can move to a smart pointer implementation at a later date, if there is more motivation than what currently exists.

**Comment by mtcooling** [comment]
lol, sorry if my response was unnecessarily cryptic. The way I see it is that more of us think smart pointers is the way to go, all other things being equal. To me, an API shouldn't be crashable even by a completely novice developer - developer competence is not an issue.

BUT we aren't the ones that have to do it, and the project is not exactly well resourced. Also, as Alan has already pointed out, libSBML etc uses pointers. Finally, I'm probably going to want to be calling it from Java via SWIG and don't expect it to be very robust no matter what this decision is :).

**Comment by hsorby** [comment]
I agree, sort of.

Users shouldn't be able to cause the library to crash no matter what they input into it, but we are raising exceptions so the stack will be pointing to libcellml in some cases, this is expected.  If they can then there is a test to be written and a bug to fix.

Any developer can cause a crash with bad programming, novice or otherwise.  We cannot stop that no matter what, we can only document and example with the aim of providing help in determining the cause of the crash.

Robustness to me is that the library works as expected with zero known bugs.  This is independent of whether smart pointers are used which to me are for use in managing memory (when memory management gets difficult).

It is sad that you don't expect the library to be robust when you use it, we shall have to endeavour to keep you happy @mtcooling.  And yes since you are most likely going to be using Java to make use of the library then whether it uses smart pointers or references is irrelevant to you.

**Comment by hsorby** [comment]
I had a chat with @mtcooling and we discussed this issue.  The upshot being that since the vote is more in favour of smart pointers than anything else then smart pointers should be implemented. (I paraphrase a bit).  So I will modify the code in #36 (as a new pull request) to use smart pointers and probably pass them straight out of the API ignoring possible issues with ABI compatibility and then we can see what we think of that approach and continue on with the winner.
