### ISSUE TITLE
Validation: generate a warning if some units differ by some multiplicative factor

### ISSUE THREAD

**Issue by agarny** [cellml/libcellml#381]
Ideally, this would have been done as part of issue #361, but we need to be able to generate warnings for this while we can only generate errors at this stage. In other words, we need to address issue #314 first before addressing this issue.

**Comment by kerimoyle** [comment]
This is already in progress  - along with the other things mentioned in the first statement of PR #314 :) . It did indeed used to be part of the larger validation PR, but as it's not actually required for validation, it was removed...
