### ISSUE TITLE
Clang-tidy with llvm 9.0

### ISSUE THREAD

**Issue by hsorby** [cellml/libcellml#397]
llvm 9.0 has opened up a whole can of worms with regards to new checks.  These need to be considered and either included or excluded before we can merge any pull requests.

**Comment by hsorby** [comment]
Here is an example of a command that will fix: `modernize-use-trailing-return-type` errors

```
/usr/local/Cellar/llvm/9.0.0/bin/clang-tidy -checks='modernize-use-trailing-return-type' -fix $files 
--header-filter=.* -- -Dcellml_EXPORTS -I${libcellml_build_dir}/build-release-libcellml/src/api 
-I${libcellml_src_dir}/libcellml/src/api -I${libcellml_src_dir}/libcellml/src/api/libcellml/module 
-I${libcellml_build_dir}/build-release-libcellml/src 
-I/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/libxml2 
 -O3 -DNDEBUG -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk 
-fPIC -fvisibility=hidden -fvisibility-inlines-hidden   -fprofile-arcs -ftest-coverage 
-fprofile-instr-generate -fcoverage-mapping -Weverything -Wno-c++98-compat 
-Wno-c++98-compat-pedantic -Wno-documentation 
-Wno-documentation-unknown-command -Wno-exit-time-destructors 
-Wno-global-constructors -Wno-missing-prototypes -Wno-padded 
-Wno-reserved-id-macro -Wall -W -Werror -std=gnu++11
```

given: `files`, `libcellml_src_dir`, `libcellml_build_dir` are properly defined shell variables.

**Comment by hsorby** [comment]
It would be good to revisit the inclusion exclusion list of clang tidy that we now have at some point in the future. Chances though are not high.

**Comment by agarny** [comment]
I have just create issue #402 for that purpose. So that, at least, we will now have an issue to remind us about it!
