### ISSUE TITLE
link documentation on readthedocs to current "develop" doxygen and coverage

### ISSUE THREAD

**Issue by nickerso** [cellml/libcellml#41]
Now that the documentation links to the doxygen and coverage generated documentation in addition to the sphinx docs, we need some way to link to a version of that matches the current state of the develop branch (which is what "latest" on readthedocs points at). We can do this by having a step in the buildbot setup that syncs the docs when a merge is being performed, rather than a pull-request being updated.

This issue is mostly here as a reminder that this needs to be implemented. When someone has a chance to do so :)

**Comment by hsorby** [comment]
Closing this as we now have the documentation in place and available on the libcellml.org website.
