### ISSUE TITLE
Clang format in VS 2019

### ISSUE THREAD

**Issue by nickerso** [cellml/libcellml#411]
Do we know if the version of ClangFormat included in Visual Studio 2019 is going to play nicely with the libCellML codebase? By default, it wanted to turn it on for me, but I'm worried that it might result in a significant number of issues....

**Comment by agarny** [comment]
If it's version is 8.0.0 or later then it's a version that is compatible with what we need. However, libCellML enables/disables certain checks, which may or not (most likely) be the same as the ones done by MSVC 2019.

**Comment by hsorby** [comment]
I'm not sure if we disable clang-format if the version is too old for libCellML.

**Comment by agarny** [comment]
As far as I remember, we don't. We just agreed that we would be supporting version 8.0.0 and above.

**Comment by hsorby** [comment]
I think you're right I can see that VS2017 has llvm/clang version 5.0 bundled with it but I can't find anything for VS2019.

**Comment by hsorby** [comment]
I think it might be wise to disable clang-format if the version is too old.

**Comment by agarny** [comment]
Agreed, we should disable it and output a warning/information message about it.

**Comment by nickerso** [comment]
Not sure this is something that can be disabled: VS popped up a message saying something along the lines of "We found a .clangformat file so we're going to use it for any formatting actions. Go here to turn this off if you want to.".

It looks like it is version 8.0.1 in VS 2019, so should be good.

**Comment by agarny** [comment]
Yes, it will be fine if VS only uses our `.clang-format` file.
