### ISSUE TITLE
Provide python casts for Entity::parent()

### ISSUE THREAD

**Issue by kerimoyle** [cellml/libcellml#422]
I've just updated my local python library to the develop branch, and the functionality which relied on component->parentComponent() and ->parentModel() is now gone (as expected from changes in PR #405).  I'm wondering what the better approach is for the python bindings?
- to provide a SWIG interface for a pre-cast pointer to each type, so that the parentComponent() and parentModel() calls (or something similar) in Python work, or
- to require the user to do the casting themselves in Python whenever they need to retrieve a parent of any kind?

Returning an entity pointer (which isn't really used anywhere else?) isn't as useful as a pointer to a concrete class would be ... (at least in my head!)

Thoughts anyone?

**Comment by hsorby** [comment]
I'm not sure you need one in Python.  If it is a `Model` object you use it as a model object if it is a `Component` object you use it as a component.

**Comment by kerimoyle** [comment]
That's what I'd imagined originally, but the SWIG wrapping in Python gives
you an Entity, not either a Component or Model, so you don't have access to
the functions which are tied to those derived classes.  Returning a cast
pointer behaved as I expected though.

**Comment by kerimoyle** [comment]
Here's an example of how I've needed it and what I get.  The program is designed to load a cellml model using libcellml and translates it into a database class structure; this function connects the database objects to each other through the connections/equivalent variables.

```
def connect_equivalent_variables(component, in_entity):
    in_component = in_entity.component(component.cellml_index)

    for v in range(0, in_component.variableCount()):
        in_variable = in_component.variable(v)

        variable = component.variables.filter(name=in_variable.name()).first()

        for ev in range(0, in_variable.equivalentVariableCount()):

            in_equiv = in_variable.equivalentVariable(ev)  # returns a Variable

            # -------------------------------------
            in_equiv_parent = in_equiv.parent()  # returns an Entity
            # ent_name = in_equiv_parent.name()  # cannot be accessed because NamedEntity is a subclass ... ditto all the other functions that are useful in the child classes
            # -------------------------------------
            in_equiv_component = in_equiv.parentAsComponent()  # returns a Component
            in_equiv_grandparent = in_equiv_component.parentAsComponent()  # returns a Component, if it exists or None
            if not in_equiv_grandparent:
                in_equiv_grandparent = in_equiv_component.parentAsModel()  # returns a Model

            out_equiv_component = component.model.all_components.filter(name=in_equiv_component.name()).first()

            # Look for variable in the sibling component set
            if out_equiv_component:
                out_equiv_variable = out_equiv_component.variables.filter(name=in_equiv.name()).first()
            else:
                pass

            if out_equiv_variable:
                variable.equivalent_variables.add(out_equiv_variable)
            else:
                pass

    for child_component in component.child_components.all():
        connect_equivalent_variables(child_component, in_component)

```

.. gives this result:

![Screen Shot 2019-10-09 at 8 49 22 AM](https://user-images.githubusercontent.com/46887220/66457927-cd6a2380-ea71-11e9-8fd6-c4033aabcd9c.png)

So the things returned from SWIG are libcellml-ish objects, rather than pointers that can be used as they are in C++?  If there is an easy way to cast Python objects from one form to another then I'd be keen to hear about it, but at least from what I've read so far it's not really standard practice the way it is in C++?

**Comment by hsorby** [comment]
I have been trying to get SWIG to allow the proper cast to the parent object but have so far failed.  Just letting you know that I'm investigating an alternative to adding API to the Entity class.  As this is not a problem with the API more a restriction coming from SWIG I'm trying to resolve it through there.
