### ISSUE TITLE
Improve handling of namespaces in math strings

### ISSUE THREAD

**Issue by nickerso** [cellml/libcellml#424]
We currently do a rather poor job of handling XML namespaces with math strings. As described in the discussion starting here: https://github.com/cellml/libcellml/issues/118#issuecomment-235479335; we should make sure the math strings are fully self contained XML fragments which define all required XML namespaces when parsing models and similarly update the documentation of the `setMath()` methods to clearly define that the strings are expected to be self-contained fragments when set by user code.

See also: https://github.com/cellml/libcellml/pull/420#discussion_r332825594; for the validation code that will need to updated.

This is closely related to #175, which was semi-addressed by #420.

**Comment by hsorby** [comment]
I have done some work on this and I have mapped the namespace to the math when parsing a model.  When validating a model it removes the cellml namespace information and attributes using libxml2 before asking MathML DTD for its opinion.

**Comment by kerimoyle** [comment]
Here's a simple test based on the current develop branch which is really confusing me:

```
TEST(Validator, transformedCellml1To2)
{
    libcellml::Parser parser;
    libcellml::ModelPtr model = parser.parseModel(fileContents("segfault.cellml"));
    printErrors(parser);

    libcellml::Validator validator;
    validator.validateModel(model);
    printErrors(validator);

    EXPECT_EQ(size_t(0),validator.errorCount());
}
```
where the `segfault.cellml` file is this (I know the maths is wonky):

```
<?xml version="1.0" encoding="UTF-8"?>
<model xmlns="http://www.cellml.org/cellml/2.0#" xmlns:cellml="http://www.cellml.org/cellml/2.0#"
	name="segfault" id="segfault_id">
    <component name="component1"></component>
    <component name="component2">
        <variable name="a" units="dimensionless"/>
        <math xmlns="http://www.w3.org/1998/Math/MathML">
            <apply><eq/>
                <ci>a</ci>
                <cn cellml:units="dimensionless">10</cn>
            </apply>
        </math>
    </component>
    <encapsulation>
        <component_ref component="component1">
            <component_ref component="component2"/>
        </component_ref>
    </encapsulation>
</model>
```

which gives validation errors of:
```
Namespace prefix cellml for units on cn is not defined., 
Math cn element has an invalid attribute type 'cellml:units' in the cellml namespace., 
CellML identifiers must contain one or more basic Latin alphabetic characters., 3.1.3
Math cn element with the value '10' does not have a valid cellml:units attribute., 
Namespace prefix cellml for units on cn is not defined., 
No declaration for attribute cellml:units of element cn., 
```

If - following the namespaces in the parser for cn - I add `xmlns:cellml="http://www.cellml.org/cellml/2.0#"` to the `cn` tag then the validator gets a segmentation fault inside `Validator::ValidatorImpl::validateAndCleanMathCiCnNodes`.

If I remove the encapsulation (both with and without the extra namespace tag above), the test passes without a segfault.  

If I change the order of the components included in the encapsulation (both with and without the extra namespace tag above), the test passes without a segfault. 
```
    <encapsulation>
        <component_ref component="component2">
            <component_ref component="component1"/>
        </component_ref>
    </encapsulation> 
```

I am bamboozled ...

**Comment by hsorby** [comment]
I have added this test to pull request #426. and it didn't segfault but did highlight a bug when dealing with multiple definitions of the cellml namespace.  Have a look and review that work as it will solve this issue.
