### ISSUE TITLE
Export of compiler features.

### ISSUE THREAD

**Issue by hsorby** [cellml/libcellml#428]
Currently the compiler features used by the libCellML library do not get exported.  This results in consuming projects not picking up the compiler features required for building against the libCellML library.  This needs to be fixed.

**Comment by agarny** [comment]
Not sure I understand what you are talking about here...?

**Comment by hsorby** [comment]
When someone (like @kerimoyle ) is trying to create an application like a tutorial (the consumer here) the compiler flags that are required to build successfully against the libCellML library are not propagated to the consuming target.  This results in a build failure.

**Comment by agarny** [comment]
Oh, ok, got it now. Thanks.

**Comment by nickerso** [comment]
Should we (can we?) look to add a test for this working? or that is really outside of the scope of our testing?

**Comment by hsorby** [comment]
It is outside the scope of our unit testing but would still be a good test.  Would need to have a think about how this could be added.

**Comment by kerimoyle** [comment]
Yuss! Huzzah!
