### ISSUE TITLE
Equivalent variables not validated properly

### ISSUE THREAD

**Issue by kerimoyle** [cellml/libcellml#436]
Here's a test showing that we don't check for invalid connections between equivalent variables or for interfaces:

```
TEST(Validator, variableEquivalenceErrorsNotRaised)
{
    // Create a model with three components and one variable in each to be shared between them
    libcellml::ModelPtr model = std::make_shared<libcellml::Model>();
    libcellml::ComponentPtr c1 = std::make_shared<libcellml::Component>();
    libcellml::ComponentPtr c2 = std::make_shared<libcellml::Component>();
    libcellml::ComponentPtr c3 = std::make_shared<libcellml::Component>();

    libcellml::Validator validator;

    model->setName("model");
    c1->setName("c1");
    c2->setName("c2");
    c3->setName("c3");

    // Two siblings in the model, one child in component2
    model->addComponent(c1);
    model->addComponent(c2);
    c2->addComponent(c3);

    libcellml::VariablePtr v1 = std::make_shared<libcellml::Variable>();
    v1->setName("v1");
    v1->setUnits("dimensionless");

    libcellml::VariablePtr v2 = std::make_shared<libcellml::Variable>();
    v2->setName("v2");
    v2->setUnits("dimensionless");

    libcellml::VariablePtr v3 = std::make_shared<libcellml::Variable>();
    v3->setName("v3");
    v3->setUnits("dimensionless");

    c1->addVariable(v1);
    c2->addVariable(v2);
    c3->addVariable(v3);

    libcellml::Variable::addEquivalence(v1, v3); // invalid equivalence, too far away
    validator.validateModel(model);
    // expect errors saying that components are too distant for variable equivalence, and no specification of interface type
    EXPECT_FALSE(validator.errorCount() == size_t(0));

    // Change to a valid configuration
    libcellml::Variable::removeEquivalence(v1, v3);
    libcellml::Variable::addEquivalence(v1, v2);
    libcellml::Variable::addEquivalence(v2, v3);

    // Now expect errors only related to the interface type missing
    validator.validateModel(model);
    EXPECT_FALSE(validator.errorCount() == size_t(0));

    // Add the interface types and expect no errors
    v1->setInterfaceType("public_and_private");
    v2->setInterfaceType("public_and_private");
    v3->setInterfaceType("public_and_private");

    validator.validateModel(model);
    EXPECT_EQ(size_t(0), validator.errorCount());
}
```

**Comment by hsorby** [comment]
As part of this should the `addEquivalence` method set the interface type for the variables if it can work them out?

**Comment by agarny** [comment]
> As part of this should the `addEquivalence` method set the interface type for the variables if it can work them out?

Yes, that would be nice to have.

**Comment by kerimoyle** [comment]
> Yes, that would be nice to have.

I'm a bit confused about this ... I'd thought that the whole idea behind having types of interface was so that the user had control over what wasn't shown, and defaulted the interface to `None`.  If we tie an interface type automatically to a variable equivalence, we're effectively changing the default to Not None? Or what am I missing?

**Comment by hsorby** [comment]
If you make an equivalence then the variable interface cannot be 'none', it would have to be one of 'public', 'private', or 'public_and_private'.  Once an equivalence is made you are in a position to set the interface based on the parent components relative position to each other.

**Comment by kerimoyle** [comment]
Yes, I get that ... but we had a discussion about this earlier and I'm just wondering why it's now the other way around (or from what I understand!) . See https://github.com/cellml/libcellml/issues/407#issuecomment-536945805

I think that over-riding a user's explicit specification of an interface type with an inferred one is super-dodgy.  It would be better to return an error from the validation, otherwise we're breaking our "all models are creatable" rule?  And we're also no longer having the default value of none which is specified in the spec.  I know you can't have a connection with a none interface, but that's still what we've said so I think we have to follow it ... ?

**Comment by nickerso** [comment]
> As part of this should the addEquivalence method set the interface type for the variables if it can work them out?

I was talking to @hsorby about this today - and I definitely don't think adding an equivalence should be changing the interface on either of the variables. This is too much of a side effect. Parsing a model will never be sure to result in the model as was read and you'd get different behaviour if you added equivalences for a variable before vs after adding it to a component.

It would be useful, however, to have a method that takes a model and will correct variable interfaces based on the equivalences and even create new variables when, for example, a variable in a grandchild has been set to equivalent to a variable in a grandparent, without a variable in the parent ever being added to the equivalence set.

**Comment by kerimoyle** [comment]
Agreed - but I think that such a process (your second paragraph) should be something called explicitly, and perhaps (we need that Issues class!) warns when it's overwriting an already declared interface type along the way.  Or perhaps it's enough to first output a useful error from the validator?  eg: "You have tried to make grandpa equivalent to grandson, you can't do this without involving dad".   Maybe it's cleaner if the user does the correction but the software identifies and suggests what it should be (as we have everywhere else ...?)
