### ISSUE TITLE
Where can units live?

### ISSUE THREAD

**Issue by kerimoyle** [cellml/libcellml#437]
I'm getting confused about where units can live.  Is it just in the model, or are they also allowed to be children of a component?

- the spec says in the model only (component children can be variable, reset, and math only)
- ... but the error message from an unfound unit is:
> Variable 'Cm' has an invalid units reference 'microF_per_cm2' that does not correspond
>  with a standard unit or units in the **variable's parent component** or model.
- ... and in the OpenCOR tutorial I'm reading it says:
> Note that the only units that need to be defined for this top level HH model are the ones 
> explicitly required for the membrane component.  All the other units, required for the various
> imported submodels, **are imported along with the imported components**.

So what's the real version?

In my tutorials I'm just parsing the models then transferring ownership of "not-really-imported" components to the combined model (you can read all those exciting details [here](https://github.com/kerimoyle/libcellml-tutorials/tree/development/tutorial8)) ... but when you do this you _do_ explicitly need to retrieve the units needed by that component from the parent model.  Is this a change for CellML2.0?  Did units used to live inside components too?  Is this why we have the bug related to parents of units (see #417 and the test there)?

**Comment by agarny** [comment]
CellML 1.0/1.1 (and therefore OpenCOR, as it currently stands): units can be defined at the model or component level.
CellML 2.0: units can *only* be defined at the model level.

**Comment by kerimoyle** [comment]
Thanks! So we need to update the error message for CellML2.0.

**Comment by agarny** [comment]
It looks like it, yes.
