### ISSUE TITLE
id strings could be anything?

### ISSUE THREAD

**Issue by kerimoyle** [cellml/libcellml#438]
I see that there was discussion on "allowing" `id` attributes everywhere ... but they're never used? They're not currently checked in the validator, and I'm trying to explain what they are/do in the tutorials ...

**Comment by agarny** [comment]
They are "just" a way to identify a CellML element so that it can, for example, be used for annotation.

**Comment by kerimoyle** [comment]
Weird name for them then!  I would have thought `id` required something stricter than `name`.  Ah well.

**Comment by nickerso** [comment]
The `id` attribute is defined as an ID type attribute - simply providing a unique identifier to any element in the XML document. Typically these are only used when wanting to directly address a specific element in the document - for example when annotating or defining an XPath expression in SED-ML.

If they are not being validated, then that is the actual bug :) will close this one and open a new one for that.
