### ISSUE TITLE
model copy constructor is not making a new copy of the model

### ISSUE THREAD

**Issue by nickerso** [cellml/libcellml#439]
When making a copy of a model (or any ``ComponentEntity`` really) I would expect it to make a new independent copy of the model. This doesn't seem to be the case currently. The vector of child components is copied, but this will simply have a list of the same component pointers, not new component objects.

**Comment by nickerso** [comment]
As per #440, it seems that the copy constructor is simply making  a new pointer to the same "data". Changing this will likely have a large impact? So maybe the way to go for me to get what I need for now is to implement a clone (shallow and deep) method and take it from there.

**Comment by kerimoyle** [comment]
When I was writing the online version I made a deep and shallow copy function, but found pretty quickly that the shallow one didn't really make much sense.  I think it would be cleaner to have a recursive duplicate (where the child items, through as many generations as needed are copied too).  I can't think of a use case for the shallow copy in our current situation except perhaps for units (but even then, not really since they have to be within the model anyway) ... what was it you had in mind for the shallow copy?

**Comment by nickerso** [comment]
yep. Shallow isn't likely to be useful for what I need now, but should be a subset of the deep. I think.

**Comment by agarny** [comment]
From http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0201r0.pdf, a "`shared-ptr`’s copy constructor is shallow". So, it looks like having a deep clone would be the way forward and... the aforementioned link provides a class that does just that.

**Comment by hsorby** [comment]
I would like to see a function `duplicateModel`, with the work I am doing #418 the copy constructor will not be available due to the use of `enable_shared_from_this`.

**Comment by agarny** [comment]
I am not sure we want a `duplicateModel()` method. Instead, I would expect something like `Entity::clone(bool deep = true)`?

**Comment by hsorby** [comment]
I don't mind that but I would probably drop the `deep` parameter and just make the method do a deep copy job.

**Comment by hsorby** [comment]
I can't see how a shallow copy could be useful and so far no use case exists to show that we need one.

**Comment by agarny** [comment]
Fine by me (I merely put it in there because it had been mentioned before).

**Comment by hsorby** [comment]
First tier clone-able objects (or objects that need to be cloned to create a cloned model):

- [ ] Model
- [ ] Component
- [ ] Variable
- [ ] Units
- [ ] ImportSource
- [ ] Reset

Second tier clone-able objects (or objects that may be helpful to be clone-able):

- [ ] GeneratorProfile

**Comment by hsorby** [comment]
If we are able to clone all first tier objects I think this would satisfy this issue.
