### ISSUE TITLE
consistency in clearing math strings

### ISSUE THREAD

**Issue by nickerso** [cellml/libcellml#443]
as per https://github.com/cellml/libcellml/pull/416#pullrequestreview-306336108 we need to make sure we are consistent in the way we clear math strings from our objects.

**Comment by hsorby** [comment]
I think this method should be called `removeMath` as that is the pairing we have used elsewhere in the code (add/remove).

**Comment by hsorby** [comment]
While we are at it we should probably add a `removeUnits` method to the `Variable` class.

**Comment by kerimoyle** [comment]
> While we are at it we should probably add a `removeUnits` method to the `Variable` class.

... also see test in https://github.com/cellml/libcellml/pull/417 for bug with units
