### ISSUE TITLE
Should the validator report on missing initial conditions?

### ISSUE THREAD

**Issue by kerimoyle** [cellml/libcellml#445]
It's possible to create a model which is reported "valid" but have it return errors from the generator by not initialising variables.  To what extent can/should this be checked in the validator?  Am guessing it's not possible really as the validator doesn't care about maths ... but figured I'd check ... ?

**Comment by hsorby** [comment]
At the moment the validator is only tasked with checking that the structure of the xml is CellML compliant, it should cover anything mentioned in the spec. as that is what it is validating against.

There is nothing in the spec. that discusses not initialising variables suitable to satisfy the creation of a set of equations (unless section 19.8 covers it somehow?).

**Comment by kerimoyle** [comment]
OK, thanks.  19.8 doesn't mention the initial conditions, but it was more the idea the initial conditions might(?) be able to change the validity of the underlying maths model if treated as a "statement which holds true unconditionally".  I think that section 19.6.2 is the CellML get-out-of-checking card, but not sure whether that included libCellML too:

> The conditions when initial values hold are (by design) not defined in a CellML model document. It is intended that those conditions be supplied by CellML processing software where appropriate.

**Comment by nickerso** [comment]
The validator is only checking for valid CellML, not a valid and/or complete simulate-able model. Closing this but please re-open if I've missed something...
