### ISSUE TITLE
Use `https` in our CellML 2.0 namespace?

### ISSUE THREAD

**Issue by agarny** [cellml/libcellml#452]
Right now, we are using `http://www.cellml.org/cellml/2.0#` for our CellML 2.0 namespace. IOW, we are using `http` rather than `https`, which is the norm nowadays. I would therefore expect the CellML 2.0 namespace to be `https://www.cellml.org/cellml/2.0#`.

**Comment by nickerso** [comment]
I can't see anything against this, but have ping'd the spec writing group to see what others think. @metatoaster may also have an opinion?

**Comment by metatoaster** [comment]
No real upside to specify https for namespaces, and that http://www.cellml.org will redirect to the secure version anyway.

Future versions of HTTP protocol may fully enforce TLS anyway, rendering https:// prefix redundant.

**Comment by jonc125** [comment]
XML namespaces don't have to resolve to anything anyway, and I think most still use http. It's also consistent with older CellML versions - less surprising for users.

**Comment by agarny** [comment]
Fully agree with all the comments so far. I am (was?) merely after consistency with current practices with regards to `http` vs. `https`.

**Comment by nickerso** [comment]
closing as it seems clear that we should stick with `http`. Please reopen if this is not the case.
