### ISSUE TITLE
Create repo for tutorials please?

### ISSUE THREAD

**Issue by kerimoyle** [cellml/libcellml#454]
Further to #425 ... I'm nearing the end of the tutorial writing, and it would be great to give them a home somewhere.  I've thought about where the best place for them would be, and I **don't** think it's this prime libcellml repository as the audience is quite different to libcellml developers.  I don't have the right permissions to be able to create a new repository under the cellml heading - please can someone do that for me?  

At present I use three different ones:
- one for the documentation creation (so that users don't have to use Sphinx etc to build it) see https://github.com/kerimoyle/libcellml-tutorials-instructions.  Currently the built html directories are manually copied into the other repositories below.  I'm going to try and make these submodules instead of copying stuff ... (but currently too chicken to try it out!)  Note that inside this repo are three streams, one for C++, Python, and "general" which holds the information about the modelling theory/HH model background/info on units etc which are agnostic of language.
- one for tutorials in C++, see https://github.com/kerimoyle/libcellml-tutorials-cpp
- one for tutorials in Python, see https://github.com/kerimoyle/libcellml-tutorials-python

I'm not sure what the best strategy is within the cellml library - whether to keep them split into languages or to put them together?  I only split them so that I could keep track easier, and to make the downloads smaller when people clone them.

I still have some work to do to create some simple solvers so that the generated code will run (I will probably steal something from @hsorby's cellsolver for python?), and to finish off the tutorials which were previously segfaulting, then finally make installing easier, but hopefully you'll get the idea and be able to give me your opinions on how this should work ... @agarny @nickerso @hsorby ... thanks :)

**Comment by agarny** [comment]
I would simply have https://github.com/libcellml/tutorials (i.e. once it's under the `libcellml` organisation) with the contents of your current https://github.com/kerimoyle/libcellml-tutorials-instructions. Nothing more nothing less. The HTML files are generated files, so as far as I am concerned, they have nothing to do in a Git repository. It's a different thing to have source code in a repository, and to deply the "built" tutorials.

**Comment by hsorby** [comment]
Is this going to go under a new organisation `libcellml` or under the existing organisation `cellml`?

**Comment by agarny** [comment]
Oops, since we indeed have the `cellml` organisation and that the libCellML project is under it, then maybe the tutorials should in https://github.com/cellml/libcellml-tutorials?

**Comment by kerimoyle** [comment]
Yes, i think it should be a sibling of libcellml under cellml, as alan
suggests

**Comment by kerimoyle** [comment]
And any thoughts on how best to split languages?

**Comment by agarny** [comment]
Why would you want to split languages? What is wrong with having everything under the same repository? In fact, from what I understand (I haven't tried to build your tutorials), this is what you have, no? My point is that, when looking at a tutorial for an API, I like the idea of being able to see code for C++, Python, etc. without having to go to a completely different place.

**Comment by kerimoyle** [comment]
> Why would you want to split languages? What is wrong with having everything under the same repository?

So that people didn't have to clone a whole collection of code and instructions for language(s) that they didn't care about - they could just get the one that they needed and go from there.  

> In fact, from what I understand (I haven't tried to build your tutorials), this is what you have, no?

I currently have them in two separate repos, [one for C++](https://github.com/kerimoyle/libcellml-tutorials-cpp) and a separate [one for Python](https://github.com/kerimoyle/libcellml-tutorials-python), which each contain two sets of files - one with the "answers" to the tutorial, and one with skeleton code so that people can work through the steps themselves.  The instructions in the HTML mimic the comments in the skeleton code so I hope it will be quite easy to follow.  

> My point is that, when looking at a tutorial for an API, I like the idea of being able to see code for C++, Python, etc. without having to go to a completely different place.

We can certainly make the HTML of the _instructions_ in a central place - that's what [the third repo](https://github.com/kerimoyle/libcellml-tutorials-instructions) is currently used for - but it seems weird to me that anyone would download all the tutorials for lots (one day...) of languages when they only need one.

**Comment by hsorby** [comment]
Do people want to download a tutorial or just read it online?  I would have thought people would want to follow a tutorial online.

**Comment by kerimoyle** [comment]
Haha, this depends very much on how you see learning ... I reckon to understand things people need to _do_ them, hence the need to download and do the business.  They can always just read the instructions without doing anything, but that's a bit too shallow for me.  Downloading also gives them a template structure for linking libCellML into their own projects too.

**Comment by agarny** [comment]
I just had a (very) quick look https://github.com/kerimoyle/libcellml-tutorials-instructions. I hadn't realised that it contains the HTML files. Ok, for me, this is not the way to go. It's as if you were to have `.obj`, `.exe`, `.lib`, etc. files in our libCellML repository, which we clearly don't want to do.

I would expect the tutorials to be made available on, say, [Read the Docs](https://readthedocs.org/), or some other place we manage ourselves (as we, for example, do for the OpenCOR [user](https://opencor.ws/user/index.html) and [developer](https://opencor.ws/developer/index.html) documentations), and point to C++/Python sample code on our GitHub repository. From there, if on [Read the Docs](https://readthedocs.org/), then a [PDF file will automatically be available](https://docs.readthedocs.io/en/stable/features.html#pdf-generation). Equally, if we host the tutorials ourselves, we can also make the PDF available. Easy peasy.

**Comment by kerimoyle** [comment]
Yes, exactly, that's what I'm aiming for - to have the instructions repo output (the built html) hosted on readthedocs/whatever, but it still needs a place to live in the meantime :)

**Comment by agarny** [comment]
No, it doesn't. Ideally, when committing/merging changes to the main branch, the tutorials would be automatically built and uploaded to, say, RTD.

**Comment by kerimoyle** [comment]
Yes, ok, but where does that main branch for instructions live? inside the current libcellml repo? then it's weird to go outside it to get the tutorials themselves? I think it's cleaner to have something separate from the libcellml development repo, hence this request.

**Comment by agarny** [comment]
I believe the tutorials themselves (i.e. the C++/Python files, right?) could be copied over to RTD, if we really wanted to have everything in one place (and maybe they should be indeed).

**Comment by nickerso** [comment]
So jumping into this a bit late, but here are some of my thoughts.

Generated content should not be in the git repos - its trivial to regenerate the HTML so we don't need to archive it. 

There should be a single canonical repo `cellml/libcellml-tutorials` or similar that is used as the source for a `libcellml-tutorials.readthedocs.io` - this is the one place that people would go to in order to learn how to use libcellml in any language. This could in turn be built up from a number of submodules, each with a specific focus, but I think we do want a single place online for people who want to learn how to use libcellml. My thought for now is that we could go with a single repo and split it out if needed in future, or keep the current idea of the C++ and Python- specific content as separate repos.

It would be good to do what I did with the OpenCMISS examples documentation (which is long since broken) as per: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4283644/ and https://opencmiss-cellml-examples.readthedocs.io/en/latest/: i.e., to make the tutorial material readable both on readthedocs and Github, we use a README.rst alongside each of the source files rather than having them separate and the top-level `index.rst` simply includes the top-level `README.rst`. The Sphinx reStructuredText mostly renders fine on Github and this makes it clear what needs updating when the example source gets updated. And by linking to the files with `:download:` or similar type references in Sphinx they will automatically be copied to the build tree and made available via the online documentation. 

It would be good to a have a stand-alone basic libCellML C++ repo that users could clone and use as a starting point for a new project that uses libCellML. This should be documented and be linked into the tutorial.

**Comment by hsorby** [comment]
Repository for tutorials has been created here: https://github.com/libcellml/userguides
