### ISSUE TITLE
Incorrect scaling factor when passing in empty UnitsPtr as input

### ISSUE THREAD

**Issue by awickens** [cellml/libcellml#470]
When passing in a `unitsPtr` `vector` with no `Unit` structs within to the `scalingFactor` method, there is  an erroneous scaling factor which is returned.

**Comment by awickens** [comment]
Note: currently the output of comparing units means the scaling factor of the `Unit` which is *not* empty is returned. Should this be changed to 0.0 to clearly signal that an invalid comparison is being made?

**Comment by agarny** [comment]
> Note: currently the output of comparing units means the scaling factor of the `Unit` which is _not_ empty is returned. Should this be changed to 0.0 to clearly signal that an invalid comparison is being made?

Yes, I would return `0.0`. Less misleading that way.
