### ISSUE TITLE
Create installers of libCellML binaries 

### ISSUE THREAD

**Issue by hsorby** [cellml/libcellml#486]
We should look at using `CPack` to package libCellML binaries into system specific installers for this.

**Comment by kerimoyle** [comment]
Are you familiar with VCPkg?  I was doing some reading last week about this and it seemed to be a broad way to go?  https://docs.microsoft.com/en-us/cpp/build/vcpkg?view=vs-2019

**Comment by hsorby** [comment]
Comparing the two I think `CPack` is the way to go.  Mostly because of the integration it has with `CMake`, there is less work to do to produce the installers for users.

**Comment by kerimoyle** [comment]
... shouldn't the consideration be how much work for the users?  Not sure how either measures up in that respect...
