### ISSUE TITLE
Where's the API documentation?

### ISSUE THREAD

**Issue by MichaelClerx** [cellml/libcellml#495]
Hiya!

Just trying to catch up with where libcellml is at. Thought I'd start on readthedocs, but my first click was on "API Documentation" and that's not available on readthedocs?

Would it be hard to fix that? And is it related to #41 ?

**Comment by hsorby** [comment]
Yes it is related, some progress has been made on this and more progress is scheduled soon :).

**Comment by kerimoyle** [comment]
You can read it in your own installation of libcellml locally in the meantime?  The other set of documentation for users/tutorials/etc (very much work in progress) is [here](https://libcellml-tutorials.readthedocs.io/en/pr344_documentation/).

**Comment by MichaelClerx** [comment]
Awesome!

**Comment by hsorby** [comment]
Documentation is now available at https://libcellml.org/documentation, this is where the latest libCellML documentation will be made available.
