### ISSUE TITLE
Thoughts on using auto?

### ISSUE THREAD

**Issue by kerimoyle** [cellml/libcellml#500]
I wanted to check how people felt about using the `auto` type to declare (in particular) variables formed from the `create`() method?  See [Google style guide](https://google.github.io/styleguide/cppguide.html#Type_deduction).  I reckon it makes the code a whole lot cleaner and easier to read ... ?

**Comment by agarny** [comment]
You will see that we already use `auto` here and there and in particular for the `create()` method (see `tests/clone/clone.cpp` for example). So, for me, when the type is obvious then I am more than happy to use `auto`.

**Comment by kerimoyle** [comment]
OK, thanks.  Just trying to work out "best practice" for the tutorials :)
