### ISSUE TITLE
Inconsistent tabs/spaces in parsing/printing a model

### ISSUE THREAD

**Issue by kerimoyle** [cellml/libcellml#506]
I'm trying to make sure that the printed cellml files in the tutorials are easy to read, but struggling for consistency at the moment.  

For the simple tab-delimited cellml file below:
![image](https://user-images.githubusercontent.com/46887220/71807015-a15b4000-306a-11ea-9c4c-5e458bd19b42.png)

This is parsed and printed to give a mixture of space-and-tab delimited file below:
![image](https://user-images.githubusercontent.com/46887220/71807338-60aff680-306b-11ea-951b-6d8fd2696e42.png)

It seems weird to me to use a mixture of tabs and spaces as delimiters?  What am I doing wrong?  Should the defaults be set differently somewhere, or is this expected behaviour?

**Comment by kerimoyle** [comment]
... or is it the standard to use two-spaces for all XML input?

**Comment by kerimoyle** [comment]
Changing the input file to be two-space-delimited is a little nicer, but still something off with the mathml indentation?
![image](https://user-images.githubusercontent.com/46887220/71808292-bc7b7f00-306d-11ea-9651-ae6f880858a1.png)

**Comment by nickerso** [comment]
When printing, all the "CellML" elements will have their own indentation - which I don't think can be configured at run time. The MathML is always treated as a string so I think keeps its own whitespace but might also get some additional indentation. I know @agarny was looking at something similar yesterday, but he might have given up :)

The real answer is that the XML should not be looked at by humans, and if it must then you should first pass it through an XML pretty printer/formatter. I know this can be done with libxml2 (and the xmllint command line tool). See #346.

**Comment by agarny** [comment]
Indeed, I looked into it and managed to fix the problem that was bugging me (see https://github.com/cellml/libcellml/pull/483/commits/750bfea6885ee7f67dc5f2ada63095b510bff021). However, this indeed assumes that the XML only contains spaces, no tabs. I initially wanted to account for tabs too, but... how many spaces are we to assume for a tab? 8 is typical, but we can't and shouldn't assume anything.

Anyway, as @nickerso said, we are now in a position to switch to libXml2, and this is probably what we should be doing. Ok, I am going to look into it.

**Comment by agarny** [comment]
Closing since it will be irrelevant once issue #346 has been addressed.
