### ISSUE TITLE
Discussion of error construction and usage

### ISSUE THREAD

**Issue by kerimoyle** [cellml/libcellml#514]
Something new and hinky is happening in the validator ... here's a test to show you what I mean:
The test fails because the units defined inside the parsed model aren't being found when checking the variables inside the manually-created component, giving the message:
```
Description: Variable 't' has a units reference 'millisecond' that does not correspond with a standard units and is not a units defined in the variable's model.
```
There are a couple of things here:
- the error message needs to also report the name of its parent component so we can find it more easily
- if we're going to stick with "units" as a singular noun, how about this for the message:
"Variable 't' in component 'whatever' has units of 'millisecond' which are neither standard nor defined within its model." (just to avoid the awkward "a units" sentences!)
- but the main thing is ... the error shouldn't be happening as the units *are* defined in the model ... or am I missing something dumb?

```
TEST(Validator, unfoundUnitsInParsedModel)
{
    auto parser = libcellml::Parser::create();
    auto validator = libcellml::Validator::create();

    std::string in = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
                     "<model xmlns=\"http://www.cellml.org/cellml/2.0#\" name=\"error_in_units\">"
                     "  <units name=\"millisecond\">"
                     "    <unit prefix=\"milli\" units=\"second\"/>"
                     "  </units>"
                     "  <component name=\"IonChannel\">"
                     "    <variable name=\"t\" units=\"millisecond\"/>"
                     "  </component>"
                     "</model>";

    auto model = parser->parseModel(in);

    validator->validateModel(model);
    EXPECT_EQ(size_t(0), validator->errorCount()); // <<< this is fine!

    // Add a component to represent the voltage dependency of the n-gate
    auto nGate = libcellml::Component::create("nGate");
    model->addComponent(nGate);

    auto t2 = libcellml::Variable::create("t2");
    t2->setUnits("millisecond");
    nGate->addVariable(t2);

    validator->validateModel(model);
    EXPECT_EQ(size_t(0), validator->errorCount()); // <<< test fails!
}
```

**Comment by agarny** [comment]
> * the error message needs to also report the name of its parent component so we can find it more easily

Definitely agree. We might also want to report the name of the model? This is what I have done when adding errors from the code generator (since we can import units/components).

> * if we're going to stick with "units" as a singular noun, how about this for the message:
>   "Variable 't' in component 'whatever' has units of 'millisecond' which are neither standard nor defined within its model." (just to avoid the awkward "a units" sentences!)

Definitely agree with this one too.

> * but the main thing is ... the error shouldn't be happening as the units _are_ defined in the model ... or am I missing something dumb?

I have just tried your test using the `develop` branch and it's all fine. Are you sure fully up-to-date?

**Comment by kerimoyle** [comment]
Alas ... I'm still kinda hoping I've done something dumb, but I've tried (re)downloading the develop branch, and even cloning a brand new copy I still get the error ... :|

**Comment by kerimoyle** [comment]
I've opened a PR as I found one (!) cause of the problem ... please see [the comment there](https://github.com/cellml/libcellml/pull/516#issuecomment-572557141).

**Comment by agarny** [comment]
> Alas ... I'm still kinda hoping I've done something dumb, but I've tried (re)downloading the develop branch, and even cloning a brand new copy I still get the error ... :|

No, my bad, it was me who, somehow, didn't do the right thing, but no idea what I did wrong!?

**Comment by kerimoyle** [comment]
Eh, we've all been there...

**Comment by kerimoyle** [comment]
Just a note to say that the error message for units not found from `<cn>` items in maths should also return the name of the component.  Currently it's hard to figure out from just "Math":

```
Validator error[0]:
     Description: Math has a cn element with a cellml:units attribute 'per_mV_ms' that is not a valid reference to units in the model 'Tutorial8_HHModel' or a standard unit.
  Validator error[1]:
     Description: Math has a cn element with a cellml:units attribute 'per_millivolt_millisecond' that is not a valid reference to units in the model 'Tutorial8_HHModel' or a standard unit.
```

**Comment by agarny** [comment]
Agreed re error messages being currently generated. Might be worth having a special issue to review all our error messages and make sure they are (really) useful to end users. However, probably something that should be done once we have implemented our `Issue` class... whenever that is going to be done...

**Comment by hsorby** [comment]
We are all aware that the object that the error originates from is given in the `Error` right.  So in the case of a `Variable` error or `Units` error you have the actual object to hand.  You don't need to go looking for it?

**Comment by agarny** [comment]
In that case it means that if we want the error message to be useful to the end user then a tool like OpenCOR will need to generate an error message of its own, based on the current error message and on the fact that the error comes from a specific class.

So, sure, it can be done, but it would be rather cumbersome and any software that uses libCellML will have to do the same if they want to provide useful error messages to their end users.

... or am I missing something?...

**Comment by hsorby** [comment]
I would have thought that OpenCOR would want to give its own error message for the context that the user is working in and not simply pass on the one received from libCellML unless the user is working in some raw mode.

**Comment by agarny** [comment]
Hmm... indeed, I might end up having to do that for OpenCOR, who knows?...

Still, there is no harm in having error messages that are fully explicit. I mean, an end user shouldn't be forced to check the class where the error comes from (and maybe other classes too) to find out exactly what the error message meant in the first place.

At the end of the day, I would expect to understand what an error is about by just looking at the corresponding error message. Might just be me though...? :)

**Comment by nickerso** [comment]
I think the validator error message should be sufficient to know what rule is being broken and how (which in this case is clear, to me at least). The contextual information should come from the relevant object associated with the error message. There is no way a library like libCellML can generate a single error message that will work for all possible applications that might use it (editor, simulator, GUI, command line, library, python script, Qt, HTML, JS, etc.) - so best to stick to the lowest common denominator and let the application determine what contextual information would be useful to their user. For example, in OpenCOR highlighting the relevant equation in the editing interface plus this error message would likely be sufficient, right?

**Comment by agarny** [comment]
> There is no way a library like libCellML can generate a single error message that will work for all possible applications that might use it

Agreed, hence by default I would expect libCellML to generate an error message which is as explicit as possible.

Then, if a libCellML-based tool wants to give a more succint error message then that's fine. We should just provide an error code of sorts so that they can do whatever they want with the error.

I know that the validator has a `Kind` and a `SpecificationRule`, but this is not enough. For example, the code generator generates error messages and although we can specify its `Kind`, we obviously can't specify a `SpecificationRule` for it.

So, although I *tried* to provide error messages that are as explicit as possible for the code generator (which I understand is "wrong"...!?), we would still need an error code of sorts, so that libCellML-based tools can indeed generate the error message they want.

**Comment by kerimoyle** [comment]
> . We are all aware that the object that the error originates from is given in the Error right. So in the case of a Variable error or Units error you have the actual object to hand. You don't need to go looking for it?

@hsorby That's true only as long as you're interacting with libcellml in a "live" way.  If you have written a program that converts cellml file into a generated one and call it from the command line, you only have the information which is printed.  Of course it's possible to *also* write something which retrieves the object just so we can find its name and print to the screen, but this is super-clumsy!  All we need are error messages that are stand-alone and informative ... and it's not so hard:
`Math in component "myComponent" has a cn element ... etc` instead of inexplicably not mentioning the component name, where everywhere else we do (or have tried to) ...?
While I agree that we're not going to keep everyone happy all the time (as @nickerso said), I do think there's a lot of room for improvement/consistency here.

**Comment by hsorby** [comment]
I do agree that some of the error messages are not the best but I think we should write down some rules for error messages.  With some rules in place we can review existing error messages and make them all consistent.

**Comment by kerimoyle** [comment]
My thoughts:
- I think that this thread should be renamed as it's swamping the original cause!  I'll move that to a new one.
- I've started a PR with the new `Issue` class.  Work in progress, but at least it's begun (again) #521

How about this to start discussions for what Issues/Errors should be:

- the description should stand alone and allow the user to reasonably find the problem without needing runtime access.  This then implies:
    - instance error descriptions include own name and location 
        - eg: variables report name **and** component name
        - units report name (and model name?)
        - components report name and parent name (model or component)
        - mathml issues report component name
   - something-is-missing errors include name and usage location
       - eg: units report name and variable and component name where it's needed
       - units in <cn> report name and component where it's needed
       - nested units report name and units where it's needed
    - all issues include a reference to specification heading (or FAQ or something if not in the spec??)
    - basics of consistent formatting, language, use of quotation marks around names, UK/US spellings, etc.

**Comment by hsorby** [comment]
It is a good start.  One thing for me is do we want the full path to a component in the error message? (Starting from the model name) for deep hierarchies  you might see something like this:
`model_name/main_component/sub_component/' has an issue.

**Comment by kerimoyle** [comment]
I'm not sure ... easy enough to do ... but at the same time it could get
very long, and since everything sits inside a named component anyway, just
one level should make it traceable, independent of the encapsulation? I
could go either way so happy to go with the democratic option :)

**Comment by agarny** [comment]
Agreed with writing down some rules for error messages. What @kerimoyle is a start, but:

> * the description should stand alone and allow the user to reasonably find the problem without needing runtime access.  This then implies:

Fully agree!

>   * instance error descriptions include own name and location
>     * eg: variables report name **and** component name
>     * units report name (and model name?)

Am I correct in remembering that validation is only done for the "current" model? I.e., if a model has imports, we don't check the imports themselves? If so, then I don't think we need the model name for units.

>     * components report name and parent name (model or component)

Not sure the parent name is useful unless the error is related to encapsulation?

>     * mathml issues report component name
>   * something-is-missing errors include name and usage location
>     * eg: units report name and variable and component name where it's needed
>     * units in  report name and component where it's needed
>     * nested units report name and units where it's needed
>   * all issues include a reference to specification heading (or FAQ or something if not in the spec??)

That's the thing, not all errors are validation errors. Remember that the code generator may also generate errors. To have a reference to the specification heading (through `SpecificationRule`) is very useful, but it should be made more generic. For any error we generate, we should have some kind of (unique) error code.

>   * basics of consistent formatting, language, use of quotation marks around names, UK/US spellings, etc.

Definitely!

**Comment by kerimoyle** [comment]
Just to carry @awickens thoughts across here too - what do people think about how to best report maths when an error is found?  Personally I think that naming the component and the LHS variable would be enough to locate the equation itself (rather than the entire equation), then maybe reporting more specifically on which variable(s) have the problem after that.  Eg:
- Maths in component "myComponent" has mismatched dimensions in the equation for "a":
      LHS units are "m.s^-2", RHS units are "s^-2".  The mismatch is "m".
- Maths in component "myComponent" has mismatched multiplier in units in the equation for "a":
     LHS units are "cm^2", RHS units are "mm^2".  The mismatch is 100.

**Comment by agarny** [comment]
Remember, the LHS doesn't necessarily consist of only one variable. IOW, although we typically have something like:
```
a = b + c + d
```
to compute `a` (assuming that `b`, `c` and `d` are known), you could instead have:
```
a - b = c + d
```

**Comment by awickens** [comment]
At the moment, I've got something like this for `math` errors:

```
"The units in the expression '<expression, e.g. plus, minus>' in component '<componentName>' of model '<modelName>' are not equivalent. The unit mismatch is <mismatch>"
```

Although @agarny is right when he says that the LHS may not be just one variable, and thus we might have errors way up the tree instead of at the bottom. I was thinking perhaps to have a running stack of the entire tree and return the actual expression (where it's gotten to), but for debugging purposes (for some of the models used as test models) I found the above error message was sufficient. 

However, it would probably make it harder to locate errors if we had an expression which used a lot of the same expressions to construct a model - maybe return the operation and the variables involved would be sufficient for the user?

**Comment by nickerso** [comment]
I also agree that it would be good to define the rules for how to define error messages and then use that to guide the implementation. I do think that we also need to base this on a realistic use-case, such as @kerimoyle's example of a command line application that is writing messages to the console. What is missing/inconsistent in the current API that makes this not possible?

> the description should stand alone and allow the user to reasonably find the problem without needing runtime access.

libCellML is a library. By definition users of the library have run-time access - so this seems irrelevant. The focus in this case, I think, is that example application which is using libCellML to write messages to a console.

A lot of these comments are implying that structuring text strings consisting of the names of various objects would be helpful. Maybe worth remembering that one of the most common validation errors are names being wrong or missing. And names don't help when I'm validating a model in which I have multiple components or variables or units with the same name :)

**Comment by hsorby** [comment]
I think that we shouldn't write these rules down here but maybe in a separate issue where we only edit the first comment and therefore don't create a massive comment chain.

**Comment by hsorby** [comment]
I agree that a common validation error would be duplicated names but the user will have to take some responsibility for reading error messages.  As long as libCellML reports the duplicated name errors then the user will have all the tools they need to resolve issues.  Whether they choose to use those tools is entirely up to them.

**Comment by kerimoyle** [comment]
I think as long as we follow a principle of giving:
1. enough info on what kind of thing is wrong (illegal characters in name, mismatched units, etc)
2. where to find it (name of thing (if possible), name of parent (if possible) etc)
3. somewhere to refer for more info (spec number, other reference)
... we should be fine ... 
Where the name is the problem, we can still report it and the name of the parent (or something that complies with 2 above).

I think that the command-line use-case is a really good baseline (we can't get much simpler after all!). 

To clarify my "run-time" comment, I think that the user shouldn't need to access their code to figure out an error in an external cellml file - the error messages we generate should be sufficient for any model.  Not sure if that makes sense to others (but I know what I mean, whew).

**Comment by kerimoyle** [comment]
> Am I correct in remembering that validation is only done for the "current" model? I.e., if a model has imports, we don't check the imports themselves? If so, then I don't think we need the model name for units.

The `Issue` class can be used outside of validation, so the opportunity is there to report things found from imports too.

**Comment by kerimoyle** [comment]
Please leave your thoughts/suggestions as **edits** on the #523 issue instead so I don't have to trawl a huge comment trail :)
