### ISSUE TITLE
Create an Importer class to enable error logging when resolving imports

### ISSUE THREAD

**Issue by kerimoyle** [cellml/libcellml#530]
After discussions yesterday with @hsorby I'm going to have a go at writing a `Debugger/Helper/Checker/Validator` class which will include the current `Validator` behaviour but also allow for wider checking of the model.  As part of this tweak, there will be a new `Flattener/Importer/??` class into which the current `Model::flatten() `and `Model::resolveImports() `functions and their dependents will be moved.  This `Importer` class will have its own logger, so we'll be able to catch things like the current segfaults/recursive depth errors caused by circular imports (see #527, #528, #529) without needing to attach a logger to the `Model` itself (see https://github.com/cellml/libcellml/pull/521#issuecomment-577617784 )

**Comment by agarny** [comment]
Hmm, indeed, it looks like a reasonable way forward.
