### ISSUE TITLE
Need to clarify documentation/names of units and scaling factors?

### ISSUE THREAD

**Issue by kerimoyle** [cellml/libcellml#539]
1) This is misleading:
```
    /**
     * @brief Return the scaling factor difference between two @c Units.
     *
     * This can be interpreted as factor, where units2 = (factor)*units1.  This method
     * does not check to see if the units are compatible.
     *
     * @param units1 The first units to compare.
     * @param units2 The second units to compare.
     *
     * @return The factor units1/units2. <<< This bit is wrong
     */
    static double scalingFactor(const UnitsPtr &units1, const UnitsPtr &units2);
```
- the return and the equation given say different things ...
- the method returns 0 when the units do not have the same base?  What does "does not check to see if the units are compatible" mean?

2) I'm not sure about the naming of the `equivalent` and `dimensionallyEquivalent` functions.  I'm happy with them, just not the names.  The "dimensional" bit of "dimensional analysis" refers to the base units, not the scaling factor ... so I would have thought that these names should be around the other way?

**Comment by hsorby** [comment]
> * @return The factor units1/units2. <<< This bit is wrong

Should be an easy fix.

**Comment by hsorby** [comment]
> * the method returns 0 when the units do not have the same base?  What does "does not check to see if the units are compatible" mean?

The documentation could be changed or the implementation.  If it is working this way then I guess the documentation should be changed to match.

**Comment by hsorby** [comment]
> so I would have thought that these names should be around the other way?

I agree, the names should be swapped.

**Comment by kerimoyle** [comment]
Related to #541
