### ISSUE TITLE
Units: scalingFactor to check dimensionality?

### ISSUE THREAD

**Issue by agarny** [cellml/libcellml#541]
One of our units-based tests reads:

```
TEST(Units, compareMultiplierSimple)
{
    // u1 = 1000*u2
    libcellml::UnitsPtr u1 = libcellml::Units::create();
    u1->setName("u1");
    u1->addUnit("metre", 0, 1.0, 1000.0);
    libcellml::UnitsPtr u2 = libcellml::Units::create();
    u2->setName("u2");
    u2->addUnit("metre", 0, 1.0, 1.0);

    EXPECT_EQ(0.001, libcellml::Units::scalingFactor(u1, u2)); // 10^-3.0 factor difference
    EXPECT_EQ(1000.0, libcellml::Units::scalingFactor(u2, u1)); // 10^3.0 factor difference
}
```

It all works fine, but now if we modify the test to read (i.e. copied/pasted `u2->addUnit("metre", 0, 1.0, 1.0);`):

```
TEST(Units, compareMultiplierSimple)
{
    // u1 = 1000*u2
    libcellml::UnitsPtr u1 = libcellml::Units::create();
    u1->setName("u1");
    u1->addUnit("metre", 0, 1.0, 1000.0);
    libcellml::UnitsPtr u2 = libcellml::Units::create();
    u2->setName("u2");
    u2->addUnit("metre", 0, 1.0, 1.0);
    u2->addUnit("metre", 0, 1.0, 1.0);
    u2->addUnit("metre", 0, 1.0, 1.0);

    EXPECT_EQ(0.001, libcellml::Units::scalingFactor(u1, u2)); // 10^-3.0 factor difference
    EXPECT_EQ(1000.0, libcellml::Units::scalingFactor(u2, u1)); // 10^3.0 factor difference
}
```

then we can see that the test still passes while it clearly shouldn't. @kerimoyle, any views on this?

**Comment by kerimoyle** [comment]
Hi @agarny.  I agree - I think that the test should fail with a scaling factor of 0 as the base units are no longer the same (m vs m^3).  Not sure where the difference is coming from ... @awickens do you have any thoughts?

**Comment by kerimoyle** [comment]
Neither the `dimensionallyEquivalent` nor the `equivalent` functions return true, so I think that this should be the first check inside the `scalingFactor` function: if the base units are not the same then the scaling factor returns 0.

**Comment by awickens** [comment]
Yeah, ```scalingFactor``` doesn't check if the units have the same base (```equivalent()``` would return ```false``` in the case which @agarny showed above). I guess it depends on whether we want the user to be able to compare any two units (such a comparison, to me, doesn't make too much sense), or only compare units which have the same base.

**Comment by kerimoyle** [comment]
I'm not sure that it makes sense to return a number for scaling two different units ... because you'd expect to be able to simply multiply it into the units to make them identical, and this is not the case.  - I think it's safer to return 0,
- ... but a possible alternative would be to return the mismatch in terms of a Unit item, so it's no longer a simple float return.  Not really a fan of this though - if that functionality was wanted it's cleaner in a separate function.
Overall I'd vote for having the dimensionality check at the start of the `scalingFactor` function.

**Comment by agarny** [comment]
In my amended test, I would indeed have `scalingFactor()` return `0.0`. However, as @nickerso pointed out to me, the documentation says that "[`scalingFactor()`] does not check to see if the units are compatible". So, although I don't agree with what `scalingFactor()` does, it nonetheless remains that it does what it is claiming to be doing.

So, if anything, I would be in favour of changing `scalingFactor()`'s behaviour to ensure that the units are indeed compatible and return `0.0` if they are not. Not least because `scalingFactor()` is a `static` method, so I would expect such a method to be bullet proof.

**Comment by kerimoyle** [comment]
That just means that if we change what `scalingFactor` does we also update the documentation!  @nickerso is there a reason that it **shouldn't** check that the units are compatible?

**Comment by kerimoyle** [comment]
Just starting to do the tweaks for this issue as well as the #539 related one, and changed the first test above to be as below.  Would we expect this to pass?  Currently fails with the scaling factor of 1e+/-9 rather than (my) expected 1e+/-3 ... 
```
TEST(Units, scalingFactorBetweenSimilarUnits)
{
    // u1 = 1000*u2 ... but is it really ... ?
    libcellml::UnitsPtr u1 = libcellml::Units::create();
    u1->setName("u1");
    u1->addUnit("metre", 0, 3.0, 1000.0);
    libcellml::UnitsPtr u2 = libcellml::Units::create();
    u2->setName("u2");
    u2->addUnit("metre", 0, 1.0, 1.0);
    u2->addUnit("metre", 0, 1.0, 1.0);
    u2->addUnit("metre", 0, 1.0, 1.0);

    EXPECT_EQ(1000.0, libcellml::Units::scalingFactor(u2, u1));
    EXPECT_EQ(0.001, libcellml::Units::scalingFactor(u1, u2));
}
```
