### ISSUE TITLE
Prefix (for units): the enumeration should be moved to `units.h`

### ISSUE THREAD

**Issue by agarny** [cellml/libcellml#542]
Right now, the `Prefix` enum class is defined in `[libCellML]/src/api/libcellml/enumerations.h` while I would expect it to be defined in `[libCellML]/src/api/libcellml/units.h`, as is the case for `StandardUnit` enum class. This means that, in the end, there is no need for `[libCellML]/src/api/libcellml/enumerations.h`.

**Comment by kerimoyle** [comment]
I can't see a use for `Prefix` outside of `Units` ... but which way makes more sense?  To move the `StandardUnit` to `enumerations.h` or vv?

**Comment by agarny** [comment]
`StandardUnit` and `Prefix` are related to `Units`, so for me they should be in `units.h`. Simple as that. (I "hate" having to look in different places for things that are related.)

**Comment by agarny** [comment]
Closing following the merging of PR #543.
