### ISSUE TITLE
Units: the scaling factor between a standard unit and a derived standard unit wrongly returns zero

### ISSUE THREAD

**Issue by agarny** [cellml/libcellml#544]
I would expect the following test to pass, yet it fails:

```
libcellml::UnitsPtr u1 = libcellml::Units::create("second");
libcellml::UnitsPtr u2 = libcellml::Units::create("millisecond");
u2->addUnit(libcellml::Units::StandardUnit::SECOND, libcellml::Prefix::MILLI);

EXPECT_EQ(0.001, libcellml::Units::scalingFactor(u1, u2));
EXPECT_EQ(1000.0, libcellml::Units::scalingFactor(u2, u1));
```

The reason is that the `second` units doesn't have any `Unit` children and the `second` and `millisecond` units don't have the same name, so `Units::scalingFactor()` returns `0.0`.

**Comment by hsorby** [comment]
Is this getting fixed in a pending PR?

**Comment by agarny** [comment]
I was going to fix it, but... I misdiagnosed the problem I am having. Indeed, `u1` actually defines a base unit called `second`, which is not what I want. What I want is to get the scaling factor between the standard unit `second` and `u2`.

See issue #545 for the issue I should have reported.
