### ISSUE TITLE
Code generator: list the different variables under the "correct" component

### ISSUE THREAD

**Issue by agarny** [cellml/libcellml#546]
If we look at the [C code](https://github.com/cellml/libcellml/blob/b1865f87d3f6264d4b69aec901f635918e4c496e/tests/resources/generator/hodgkin_huxley_squid_axon_model_1952/model.c#L14-L42) generated for the Hodgking-Huxley 1952 model, we can see that `time` is listed under the `membrane` component, as are `i_Na`, `i_K` and `i_L` for example.

However, "ideally", `time` would be listed under the `environment` component while `i_Na`, `i_K` and `i_L` would be listed under the `sodium_channel`, `potassium_channel` and `leakage_current` component, respectively.

The problem is that CellML 2.0 doesn't have the notion of directionality at the connection level. So, we can't tell what the reference variable is. However, when it comes to computed variables, we could assume that the "reference" component is the one that contains the corresponding equation. This leaves the VOI, for which things are trickier. Maybe we could assume that its "reference" component is the first component that defines it...?

FWIW, the reason for wanting the above is that tools like OpenCOR need to make model parameters available to end-users, and to list them under their "reference" component makes sense...

To be done:
 - [x] Have the VOI listed under the first component in which it is defined.
 - [x] Have state variables listed under the component in which they are computed, independent of where they are initialised.
 - [x] Have variables listed under the component in which they are computed (e.g. algebraic variable) or initialised (i.e. constants).

**Comment by kerimoyle** [comment]
I believe that we're wanting to avoid the environment component?  I'm not sure I fully follow this bit:

> If we look at the C code generated for the Hodgkin-Huxley 1952 model, we can see that time is listed under the membrane component, as are i_Na, i_K and i_L for example.  However, "ideally", time would be listed under the environment component while i_Na, i_K and i_L would be listed under the sodium_channel, potassium_channel and leakage_current component, respectively.

In CellML2 all these variables get listed under both components ... so is the issue you're talking about is that when that's generated into code then we need to know which is the "real" variable and which is the "inheriting/connected/downstream/etc" one?  Since the `Generator` already contains checks for initialisation, can't we use the same idea/processing to determine which is the "real" one?  IOW, reference variables are defined as those which must be either VOI or initialised, and inheriting variables are the others?

**Comment by agarny** [comment]
> I believe that we're wanting to avoid the environment component?

Indeed, we want to avoid the infamous `environment` component, but the fact remains that 99.9% of CellML 1.0/1.1 models use it. So, even though OpenCOR will automatically convert them to CellML 2.0, that `environment` component will still be there.

> In CellML2 all these variables get listed under both components ... so is the issue you're talking about is that when that's generated into code then we need to know which is the "real" variable and which is the "inheriting/connected/downstream/etc" one? Since the Generator already contains checks for initialisation, can't we use the same idea/processing to determine which is the "real" one? IOW, reference variables are defined as those which must be either VOI or initialised, and inheriting variables are the others?

When it comes to code generation and, more generally, to running a model, we don't need to know where a variable comes from. It's just that the code we generate does provide that information, so we should make it as accurate as possible. Not to mention that this information is useful to tools like OpenCOR where we list variables in a tree-like structure:

<img width="440" alt="Screen Shot 2020-02-19 at 11 14 46 AM" src="https://user-images.githubusercontent.com/602265/74782812-162bc600-5309-11ea-9aa0-932d1d5642f7.png">

So, yes, that information is only needed to make the end-user's life "easier".

**Comment by kerimoyle** [comment]
In general I'd be in favour of making the end user's life easier :)  Last year I thought that a general info section in the generated code would be good (I needed the model name, see #501 ).  Perhaps a simple dictionary containing this kind of "extra" info would be good?
