### ISSUE TITLE
Bug in equivalent units with dimensionless 

### ISSUE THREAD

**Issue by kerimoyle** [cellml/libcellml#552]
When the difference between two units is a `dimensionless` unit, the units are not equivalent, so this test fails.  I think that's not what we want, but not sure if others think otherwise?

```
TEST(Units, customUnitsScalingFactorDimensionless)
{
    auto m = libcellml::Model::create("model");
    auto u1 = libcellml::Units::create("u1");

    m->addUnits(u1);

    auto u2 = libcellml::Units::create("u2");
    u2->addUnit("u1");
    u2->addUnit("dimensionless");

    m->addUnits(u2);

    m->linkUnits();

    EXPECT_TRUE(libcellml::Units::baseEquivalent(u1, u2)); // <<< base units are not the same
    EXPECT_EQ(1.0, libcellml::Units::scalingFactor(u1, u2));
    EXPECT_TRUE(libcellml::Units::equivalent(u1, u2));
}
```

**Comment by hsorby** [comment]
I think this should be equivalent.

**Comment by hsorby** [comment]
I have also been wondering how a user might be able to set their own units as dimensionless so that comparisons to `radians` would work.

**Comment by kerimoyle** [comment]
Since `dimensionless` is (or was?) one of the 7+1 base units, it should be able to be used in the same way as others (eg `metre` etc)?  The only difference is that the exponent shouldn't be counted.  Something like radians could be specified as `m/m`, or steradians m^2/m^2 and I think that that should return true in a comparison to dimensionless?

**Comment by kerimoyle** [comment]
Try it out on #554 where this issue was fixed and see ...
