### ISSUE TITLE
Expected behaviour of importing units?

### ISSUE THREAD

**Issue by kerimoyle** [cellml/libcellml#555]
I'm getting confused about the design rationale behind imports, and what the user would expect to happen. Imagine I have a model which imports ten components which all use the units "millisecond".  As it stands, importing these would create **ten separate copies of those same units**, all with different names "millisecond_1, millisecond_2, etc".   The MathML would be changed to reference those units, and since we're not providing any functionality to manipulate the MathML strings to change units easily, I can see this creating a nightmare for the user!  They can expect validation errors like "you have used units millisecond_99732 which is not defined in your model", when they already have 99731 copies of the same millisecond units.

This makes me wonder ...

- When importing is it reasonable expect default behaviour which says "**only** change the name of units and reimport where the name is duplicated but the units themselves are **not** equivalent"? ie: if `myUnits` in one model is not equivalent to `myUnits` in another -> create `myUnits_1` ... BUT if they are equivalent, then do not change anything, and make use of the nice design of the cellml structure.
- Is it also reasonable to have an optional flag where the user can say "import all the units that my imported components need because (for some unknown reason) I really do want to have lots of copies of them with different names"?
- How is it helpful to define units outside of components, if reuse of those units is not going to be straightforward?

I am so confused ... !

(This is related to #520 but seemed to be wider than just that situation). Any thoughts @hsorby @agarny  @nickerso ?

**Comment by hsorby** [comment]
This is not the case if the units named `millisecond` are equivalent.  The name is only changed if the units are not equivalent.

**Comment by kerimoyle** [comment]
That's what I would have hoped, but can you point me to where that testing is done?  All I can see in the `flattenComponent` function is testing whether the pointer exists, or the name exists, but nothing about unit equivalence?

```
for (const auto &u : requiredUnits) {
            if (!model->hasUnits(u)) {
                size_t count = 0;
                while (!model->hasUnits(u) && model->hasUnits(u->name())) {
                    auto name = u->name();
                    name += "_" + convertToString(++count);
                    u->setName(name);
                }
                model->addUnits(u);
            }
        }
```

**Comment by hsorby** [comment]
Unit equivalence is tested here:
`if (!model->hasUnits(u)) {`

**Comment by kerimoyle** [comment]
Thanks - I found it in the end.  I'd forgotten we'd decided to treat searching by name and by reference differently :| My bad.
