### ISSUE TITLE
`isBaseUnit` returns `true` for derived units like *volt*.

### ISSUE THREAD

**Issue by hsorby** [cellml/libcellml#565]
`isBaseUnit` isn't entirely honest when it returns `true`.  If you have a units with the name *volt* with no unit defined then `isBaseUnit` will return `true`.  Probably not what one would consider to be a base unit.

**Comment by kerimoyle** [comment]
Exactly.  I think somewhere along the line it's gone from testing base units to testing imported units ... hence my comment in the earlier PR.
