### ISSUE TITLE
Debug functions: make them automatically available when building a debug version

### ISSUE THREAD

**Issue by agarny** [cellml/libcellml#567]
Right now, if we want to take advantage of debug functions, we must manually define `ENABLE_DEBUG_FUNCTIONS` as a boolean equal to `ON`. I understand from @hsorby that the reason is that we then don't have to worry about coverage (and maybe some other things?). However, this is a bit annoying. When I build in debug mode, I would expect to have access to the debug functions. Simple as that. (I keep having to search what I need to define to get access to those functions.)

**Comment by hsorby** [comment]
I can look into this, it is a little awkward for MSVC but should still be doable.

**Comment by agarny** [comment]
Great, that would be nice.
