### ISSUE TITLE
API: why do we have an `OrderedEntity` class?

### ISSUE THREAD

**Issue by agarny** [cellml/libcellml#578]
Only the `Reset` class inherits from `OrderedEntity`. So, I would expect the `OrderedEntity` class to be removed and its contents moved to the `Reset` class.

P.S.: the documentation for `OrderedEntity` is wrong.

**Comment by nickerso** [comment]
Pretty sure this is a hangover from when we had `when`'s. Now that we only have `reset`'s as the only ordered entity we could look to remove the `OrderedEntity` class.

**Comment by agarny** [comment]
> Pretty sure this is a hangover from when we had `when`'s.

Yes, I thought it might be

> Now that we only have `reset`'s as the only ordered entity we could look to remove the `OrderedEntity` class.

Ok, will do it when I have a few minutes.
