### ISSUE TITLE
Utilities: `convertToInt()` should return `0` if a conversion is unsuccessful

### ISSUE THREAD

**Issue by agarny** [cellml/libcellml#579]
Right now, `convertToInt()` crashes libCellML if we pass to it a value that is not convertible to an integer. Ideally, we would do something similar to what we have done / are doing in issue #577, but we can't do that since both `nan` and `inf` are `double`s.

So, all we can probably do is to return `0` if we cannot convert a `std::string` to an `int`?

**Comment by kerimoyle** [comment]
I don't think that a failed conversion to integer should return something that's an integer ... that feels like a recipe for hard-to-find bugs.  Is there a reason it can't try/catch the conversion properly?

**Comment by kerimoyle** [comment]
.. and I thought we had this caught already, we certainly have a test for an out-of-range integer conversion?

**Comment by agarny** [comment]
> I don't think that a failed conversion to integer should return something that's an integer ... that feels like a recipe for hard-to-find bugs. Is there a reason it can't try/catch the conversion properly?
> .. and I thought we had this caught already, we certainly have a test for an out-of-range integer conversion?

I appreciate your concern and I would be happy with any other suggestion that you may have. If you look at PR #580, you will see a test where we have a valid reset order. However, that reset order is out of range for an `int`. So, what should we do with it?

**Comment by kerimoyle** [comment]
Can you not call `isCellMLInt` before `convertToInt` the way we do through the rest of the code? This way it can return an error nicely?  It's longer, sure ... but I think less prone to weirdness than this?

**Comment by agarny** [comment]
`convertToInt()` is only called once, in our parser, and it is done [here](https://github.com/cellml/libcellml/blob/f54b1c61f88e09bb27bc3c77aeff9edabe110596/src/parser.cpp#L1338). As you can see, there is a call to `isCellMLInteger()` just before. So, `attribute->value()` is a valid integer, it's just that it may still be out of range (for `std::stoi()`). So, what do we do in such a case?...

**Comment by kerimoyle** [comment]
Ah, sorry, I was looking in the wrong place.  
Option 1: Have `isCellMLInteger` test for being in the int range?  And adding that to the spec, for integers and real numbers too? OR
Option 2: 

```
} else if (attribute->isType("order")) {
            orderDefined = true;
            orderValid = isCellMLInteger(attribute->value());
            if (orderValid) {
                try {
                    order = convertToInt(attribute->value());
                 }
                 catch (something) {
                      ErrorPtr err = Error::create();
                err->setDescription("Reset in component '" + component->name() + "' referencing variable '" + variableName + "' has an out of range integer order value '" + attribute->value() + "'.");
                err->setReset(reset);
                err->setRule(SpecificationRule::RESET_ORDER);
                mParser->addError(err);
}
                
        
            } else { // This value won't be saved for validation later, so it does need to be reported now.
                if (reset->variable() != nullptr) {
                    variableName = reset->variable()->name();
                }
                ErrorPtr err = Error::create();
                err->setDescription("Reset in component '" + component->name() + "' referencing variable '" + variableName + "' has a non-integer order value '" + attribute->value() + "'.");
                err->setReset(reset);
                err->setRule(SpecificationRule::RESET_ORDER);
                mParser->addError(err);
            }

```

**Comment by agarny** [comment]
Considering the current utilities that we have, I would go for option 2. So, we can probably close this issue and its corresponding PR in favour of a new issue for option 2.

**Comment by agarny** [comment]
Closing in favour of issue #583.
