### ISSUE TITLE
Utilities: have `convertToInt()` and `convertToDouble()` check whether the value to convert is out of range

### ISSUE THREAD

**Issue by agarny** [cellml/libcellml#583]
This issue is a result of some discussions in issue #579 and PR #356 

Basically, `convertToInt()` and `convertToDouble()` assume that the string that is passed to them represents a valid integer and a valid real number, respectively. That is fine. However, a valid integer/real number may be out of range for the `int`/`double` type, in which case we need the caller to know about it.

Right now, the methods have the following signature:

```
int convertToInt(const std::string &candidate);
double convertToDouble(const std::string &candidate);
```

We could therefore change them to:

```
bool convertToInt(const std::string &from, int &to);
bool convertToDouble(const std::string &from, double &to);
```

The idea is that if `convertToInt()`/`convertToDouble()` was successful then the method returns `true` and `to` has the expected value. On the other hand, if `convertToInt()`/`convertToDouble()` failed because `from` represents a value that is out of range for the `int`/`double` type then it would return `false` and `to` would be ignored.

Does that sound reasonable @hsorby, @nickerso and @kerimoyle?

**Comment by kerimoyle** [comment]
I'm a whole lot happier with this philosophy than the earlier one :) I guess it means that our current test for out of range integers (see `TEST(Units, unitsWithPrefixOutOfRange)` ) is insufficient - perhaps needs to be replicated/moved into the parser?

**Comment by agarny** [comment]
> I'm a whole lot happier with this philosophy than the earlier one :) I guess it means that our current test for out of range integers (see `TEST(Units, unitsWithPrefixOutOfRange)` ) is insufficient - perhaps needs to be replicated/moved into the parser?

I guess this is now done in the [`TEST(Validator, integerStrings)`](https://github.com/agarny/libcellml/blob/3d6ada980cbe14c9fa5aeb7654a0ccfce68b7471/tests/validator/validator.cpp#L883)?
