### ISSUE TITLE
Don't use US spelling for function names?

### ISSUE THREAD

**Issue by kerimoyle** [cellml/libcellml#588]
The generator has a function `initializeStatesAndConstants` which should be `initialiseStatesAndConstants`?  Not sure if there are others lurking around the place too?

**Comment by agarny** [comment]
When it comes to the code generator, I believe this should be it. Either way, we (happy to be that person) need to check [src/generator.cpp](https://github.com/cellml/libcellml/blob/develop/src/generator.cpp) and [src/generatorprofile.cpp](https://github.com/cellml/libcellml/blob/develop/src/generatorprofile.cpp) and their corresponding headers / tests.

**Comment by kerimoyle** [comment]
Thanks @agarny - I only found this one in my instructions, I have no idea what else is in there :)

**Comment by agarny** [comment]
Some code to generate some C/Python code... :)

**Comment by kerimoyle** [comment]
Can this be closed now @agarny ?

**Comment by agarny** [comment]
Hmm... I actually have yet to rename those methods in PR #631. Ok, I am going to do it now and make sure that everything is in British English in that PR. so, yes, this issue can be closed. Just to be on the safe side, I have added a bullet point to issue #402 in case US spelling is used elsewhere in our codebase.
