### ISSUE TITLE
Update use-case order to Modify before Load

### ISSUE THREAD

**Issue by dladd** [cellml/libcellml#59]
This is a proposal to swap out the Load (currently 2) and Modify (currently 3) tasks in [usecases.rst](https://github.com/cellml/libcellml/blob/develop/docs/usecases.rst). 

The thinking here is that it will be a more logically incremental step for development/testing to extend the models from the Create task (1) than to start dealing with loading/importing models at this stage.

**Comment by jonc125** [comment]
Seems sensible to me. I note that task 1.viii appears at least partially to depend on loading models - it might be worth clarifying if what is intended is just to create the import elements, not instantiate the imports?

**Comment by nickerso** [comment]
yeah, all those create ones are just about creating the information in a CellML model, there is no intention in 1.\* to instantiate imports.
