### ISSUE TITLE
Cannot print a model with imports?

### ISSUE THREAD

**Issue by kerimoyle** [cellml/libcellml#590]
Say I have two models, one of which imports the other (see below).  According to [2.15.1 ](https://cellml-specification.readthedocs.io/en/latest/reference/formal_and_informative/specB15.html)and [3.4.2.2](https://cellml-specification.readthedocs.io/en/latest/reference/formal_and_informative/specC04_component_reference.html#specc-component-reference), I'm allowed to have a map_variables item that points to an imported component.  How can I get this output using the API?
- if I serialise the model without flattening, there can be no equivalences stored as the variables are not instantiated;
- if I serialise the model after flattening, then it's no longer an import situation ... ?

```
<?xml version="1.0" encoding="UTF-8"?>
<model xmlns="http://www.cellml.org/cellml/2.0#" name="import_example">
  <import xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="importMe.cellml">
    <component component_ref="importedComponent" name="importMe"/>
  </import>
  <component name="localComponent">
    <variable name="x" units="dimensionless" interface="public_and_private"/>
  </component>
  <connection component_1="localComponent" component_2="importedComponent">
    <map_variables variable_1="x" variable_2="x"/> ///**** NOTE THIS BIT!!
  </connection>
</model>
```
Inside importMe.cellml:
```
<?xml version="1.0" encoding="UTF-8"?>
<model xmlns="http://www.cellml.org/cellml/2.0#" name="import_me">
  <component name="importMe">
    <variable name="x" units="dimensionless" interface="public_and_private"/>
  </component>
</model>
```

**Comment by nickerso** [comment]
Maybe throw together a test which demonstrates this behaviour, that would be the easiest way to look at this. Cause as it stands this sounds like a huge bug.

**Comment by hsorby** [comment]
small bug

**Comment by kerimoyle** [comment]
I've written two small tests in https://github.com/cellml/libcellml/pull/591 ... the second one (in variable tests) won't compile, but it shows what I'd expect to be able to do?

**Comment by nickerso** [comment]
So as we remember how this was designed to work, there is actually no bug (see discussion on #591). But there could be new API to make the solution more convenient.

**Comment by kerimoyle** [comment]
> So as we remember how this was designed to work, there is actually no bug (see discussion on #591). But there could be new API to make the solution more convenient.

Nope, sorry @nickerso. There *is* a bug in that the variable equivalences are not being printed (see first test in PR) How the equivalence is established in the first place is a different thing ...

**Comment by nickerso** [comment]
is this the issue reported in #594? or do you mean something else?

**Comment by kerimoyle** [comment]
Something else - the original reason for this issue.  The printer is not printing equivalences between variables when one (or more) of their components is imported.  ie: the first test in #591
