### ISSUE TITLE
resolvePath(...) relies on Unix-style path separator

### ISSUE THREAD

**Issue by nickerso** [cellml/libcellml#592]
Our current "temporary" import resolution code relies on the very naive `resolvePath()` function to resolve relative import source locations. It does this with a search for the last `/` character and adding the relative path to that (see https://github.com/cellml/libcellml/blob/develop/src/model.cpp#L403). This kind of works fine, until you forget this is what it is doing and you try to use Python's `os.path` module to handle file paths - in which case you end up with no `/` and the import resolution silently falls over :) But it doesn't segfault, so that is good!

Mostly just reporting this so that we keep this in mind when working on the Importer class #531 to try and make this more generally useful.

**Comment by kerimoyle** [comment]
This is a great candidate for an Issue::Level(WARNING) :)
