### ISSUE TITLE
Validator should not check units or interfaces for dummy variables

### ISSUE THREAD

**Issue by kerimoyle** [cellml/libcellml#594]
At the moment when you create dummy variables so you can connect to an imported component, the validator checks your dummy variables for equivalent units and interface types.  This check should be removed.

See discussion here: https://github.com/cellml/libcellml/pull/591#discussion_r421194441

**Comment by nickerso** [comment]
yep, sounds good. If the imported component has been resolved the validation could proceed as normal but for unresolved imports the validator should not be checking any variables that might exist.
