### ISSUE TITLE
Questions about the Issue class

### ISSUE THREAD

**Issue by kerimoyle** [cellml/libcellml#610]
1) Throughout the tests we only seem to use one entity associated with each issue.  If this is the case in general, would it be cleaner to use a single method to return whatever this item is, cast appropriately?  At present, the user has to write their own switch statement just to decide what item type to ask for, which seems awkward to me.  For example ... imagine that your code gives you an `Issue` pointer.  You can find out some stuff about it easily (cause, level, url, description, reference) but getting the item itself is trickier than it should be.  If we just stored a single entity pointer, this could be cast according to the cause and returned?

2) Why is `Generator` listed as a `Cause` of an issue?  This seems odd as it's quite a different thing to the other causes listed?

**Comment by kerimoyle** [comment]
1 will be resolved when #696 is merged.
2 will be resolved when #631 is merged.

**Comment by hsorby** [comment]
Closing this issue as both PRs it references have been merged.
