### ISSUE TITLE
addVariable, addUnits have unexpected behaviour; addEquivalence returns false but changes model

### ISSUE THREAD

**Issue by kerimoyle** [cellml/libcellml#620]
I've found a couple of things that I didn't expect when using variables and equivalences (and perhaps makes another argument for #616).  
- I can add the same variable many times over (I would have expected only one copy of it to appear, as is the case for adding components many times).
- I can add the same variable to more than one component (again, would have expected it to move, rather than be duplicated)
- I can create connections between these duplicated variables - this is a weird one, the `addEquivalence` function returns false, but the model _is_ actually altered!

```
    auto model = libcellml::Model::create("model");
    auto tomato = libcellml::Component::create("tomato");
    auto apple = libcellml::Component::create("apple");
    auto pip = libcellml::Variable::create("pip");
    auto pippiness = libcellml::Units::create("pippiness");

    assert(model->addComponent(tomato));
    assert(model->addComponent(apple));

    // I can add the same units pointer over and over again ... 
    model->addUnits(pippiness);
    model->addUnits(pippiness);
    model->addUnits(pippiness);

    pip->setUnits(pippiness);

    // Adding a pip to the tomato: It would be nice to have a boolean return from all addSomething functions!
    tomato->addVariable(pip);
    
    // Add some more ... (this shouldn't be allowed, but I can do it!)
    tomato->addVariable(pip);
    tomato->addVariable(pip);
    tomato->addVariable(pip);

    // Add a pip to the apple as well (I'd expect this to move the variable out
    // of the tomato component, but it just adds it here too):
    apple->addVariable(pip);

    printModelToTerminal(model);

    // Push it further ... create a connection between pip variables
    // (how does it even get one from all those ones in the tomato?)
    auto success = libcellml::Variable::addEquivalence(tomato->variable("pip"), apple->variable("pip"));
    // Expect the line above to return false ...
    assert(!success);
    // ... but the equivalence is added anyway, and shows the apple pip equivalent to itself ... ?!
    printModelToTerminal(model);

    // I would expect the last addVariable (which was in to the apple component) to move the
    // pip variable there.
    assert(size_t(1) ==  apple->variableCount());
    // ... and out of the tomato:
    assert(size_t(0) == tomato->variableCount());

```

Printing the model shows that I have several copies of the same units and variables, and that I can even connect variables to itself, even though the function says I haven't (the arrows show equivalent variables):
![image](https://user-images.githubusercontent.com/46887220/84107114-f6afd900-aa70-11ea-90a0-fc6cf7d5957a.png)

**Comment by agarny** [comment]
Hmm... not sure I can see anything wrong with what you would expect from your tests...

**Comment by kerimoyle** [comment]
I've altered the `Model::addUnits(units)` function to:
- add a duplicate it if the `units` has a different parent model already;
- avoid adding the same units pointer twice to the same model.  
The tests pass.

I've altered the `Component::addVariable(variable)` function to:
- avoid adding the same variable pointer twice to the same component, and
- **move** the variable from its previous parent component into this one.   I'm not sure about this.  Do we think it should be duplicated or moved?? Is it useful to create a template variable once and be able to add it to many different components (effectively duplicating it into them?)
The tests pass.

(I need to alter the test so that the equivalence stuff is surfaced again)

Thoughts? @agarny @hsorby @nickerso

**Comment by agarny** [comment]
I haven't double checked, but I understand that it's in line with what is already done for things like `addComponent()`? If so, then I guess it makes sense to have the same for `addUnits()` and `addVariable()`. Otherwise:
 - Does `addComponent()` add a duplicate component if the component already has a different parent model?
 - I find it strange for an `addXxx()` method to move things. I would either have it return `false` if `xxx` has already been added or duplicate `xxx` and add it to whatever.

**Comment by kerimoyle** [comment]
`addComponent` moves the component, hence my confusion ...

**Comment by kerimoyle** [comment]
Maybe it would be better to have a specific `moveComponent` function, and use all `addXyz` functions to either:
a) add a copy if already parented (allows for templating, would be really convenient), or 
b) refuse to add if already parented?  

But this discussion should probably be combined with a wider talk about parents in general (along with #615 and https://github.com/cellml/libcellml/pull/572#discussion_r428317362)
