### ISSUE TITLE
Make use of `owningModel()` and `owningComponent()`

### ISSUE THREAD

**Issue by agarny** [cellml/libcellml#623]

**Comment by nickerso** [comment]
Issues like this are not very helpful at communicating the reason for why something should be done. It would be good to know what this issue is actually trying to achieve?

**Comment by agarny** [comment]
Fair point. Our codebase has two "new" utilities (`owningModel()` and `owningComponent()`), so this issue is about ensuring that our whole codebase makes use of it wherever possible. This will result in cleaner (no casting all over the place) and more consistent code.
