### ISSUE TITLE
Add mathId()/removeMathId() function to Component?

### ISSUE THREAD

**Issue by kerimoyle** [cellml/libcellml#628]
At present the MathML string in the `Component::math()` is included verbatim, without parsing and storing its `id` attribute (if present).  Should we include functions along the lines of those used in the `resetValueId` and `testValueId` functions in resets for the maths in components too?

Edit: It's a bit more complicated than I'd thought ... we currently store `mTestValue`, `mTestValueId`,  `mResetValue`, and `mResetValueId` in each reset, but these ids are *not* printed as attributes inside the child `<math>` block of the values, rather inside the `<test_value>` or `<reset_value>` blocks.  This is different from how we store `math` children of components.  

BUT ...

There's still a bug (ish?) in that we can't retrieve, set, or remove math ids at all ... ?

**Comment by kerimoyle** [comment]
(I should also add that we can't validate properly until we're able to interrogate maths ids ... see #624 )

**Comment by kerimoyle** [comment]
This is addressed in PR #630 where the functionality to parse a MathML string and get its `id` attribute is given.  We don't need set and clear functions as the id is stored within the MathML string, not separately.

**Comment by nickerso** [comment]
I think we can close this one now that we're on the same page in that all MathML elements can have IDs, not just the `math` element. Right?
