### ISSUE TITLE
 Support use case 1.xi: a model with variables

### ISSUE THREAD

**Issue by dladd** [cellml/libcellml#63]
This issue is for implementing support for use case 1.xi, creating a model with variables. 

This includes:
- [x] **a.** model from _1.iv.a_ and define a variable with a valid name and units dimensionless
  - [x] **1.** with a valid variable initial value of 0.0
- [x] **b.** model from _1.iv.a_ and define a variable with an invalid name and units dimensionless
- [x] **c.** model from _1.iv.a_ and define a variable with a valid name and invalid units name.
- [x] **d.** a model with a single component containing two variables.
  - [x] **1.** with valid variable initial values of 1.0 and -1.0, respectively
  - [x] **2.** one with an initial value of 1.0 and the other with an initial value of the first variable.

**Comment by dladd** [comment]
If there are no objections (@hsorby, @agarny, @nickerso, @jonc125), I'd like to limit this issue to use-cases 1.xi.a - 1.xi.c. This issue/pull will then just cover the reviewed modifications to the object model from #62.

That will then leave 1.xi.d, which deals with interface connections, for the next set of edits to the object model(s), testing, and implementation.

**Comment by nickerso** [comment]
sounds good to me. Will be good to keep the initial implementation of the variable object separate from the issue of dealing with connections.

**Comment by jonc125** [comment]
+1

**Comment by agarny** [comment]
+1
