### ISSUE TITLE
Add functionality to return individual <math> from concatenated <math> blocks, and individual ids

### ISSUE THREAD

**Issue by kerimoyle** [cellml/libcellml#633]
The spec says that multiple blocks with `<math>` tags are permitted inside components.  This means that they could all have their own `id` attributes.  We need to be able to retrieve these for validation, and it would make sense to also be able to access each of the blocks individually too.  The status quo API calls should be maintained so that the behaviour doesn't change: ie, `component->math()` will return the entire math string as usual.

**Comment by nickerso** [comment]
Its not clear to me why the `math` element is being treated differently to the rest of the MathML string.  And the API suggested here starts to get us away from always treating MathML as a string in the libCellML API. If we want to go down that road, I'd be much more in favour of moving to exposing our AST from the generator (which I suspect may already be proposed in another issue).

**Comment by kerimoyle** [comment]
Yep, it was written before I knew that ids were possible on the child attributes ... (see #635)

**Comment by nickerso** [comment]
Another one that I think can be closed given that all MathML elements need to be checked, not just the `math` elements.
