### ISSUE TITLE
Upgrade minimum compiler to C++17

### ISSUE THREAD

**Issue by kerimoyle** [cellml/libcellml#634]
Add -modernize-use-nodiscard flag to ignore warnings to common.cmake
Change cxx_std_11 to cxx_std_17 in CMakeLists.txt

**Comment by nickerso** [comment]
Not that I'm against this change, but would be useful for this ticket to record why this change would be useful (or link to such a discussion somewhere).

**Comment by kerimoyle** [comment]
It's to allow the use of `std::variant` type, so that we're able to return items by `id` attribute of many different types ... which is in preparation for getting tools ready to support people with annotation stuff.  This type is only available from 17 onwards, apparently, and the other workarounds for the same functionality are hideous.
