### ISSUE TITLE
Python: make sure that we can find Python 3.8.x

### ISSUE THREAD

**Issue by agarny** [cellml/libcellml#655]
On systems with multiple pythons installed, our CMake configuration will not currently choose Python 3.8.x.

**Comment by kerimoyle** [comment]
Why does it need to be 3.8? Why not 3.somethinglessthan8?

**Comment by agarny** [comment]
Our CMake script can find Python 3.0 to 3.7, but not 3.8, hence this issue and https://github.com/cellml/libcellml/pull/656/files#diff-01d7c6dd961002e07a74b697f4967894 that addresses it.

**Comment by nickerso** [comment]
See https://github.com/cellml/libcellml/pull/656#discussion_r453405819 for explanation of this issue.

@agarny - also please note that empty issues are not very useful...

**Comment by agarny** [comment]
> @agarny - also please note that empty issues are not very useful...

Agreed, I was a bit quick on this one.
