### ISSUE TITLE
Importer: externalDependency() should return a pointer to a class rather than a `std::pair`

### ISSUE THREAD

**Issue by agarny** [cellml/libcellml#681]
`Importer::externalDependency()` currently returns a `std::pair<std::string, std::string>` object, which is not neat. Ideally, we would return a pointer to a class that has only two methods to retun each of the strings in the original pair. (This is what is done in PR #631 with the `AnalyserModel` class for example.)

See https://github.com/cellml/libcellml/pull/608/files#r466043964.

**Comment by kerimoyle** [comment]
Discussions about this should probably wait until after #668 is figured out?

**Comment by agarny** [comment]
Yes, I hadn't checked @nickerso's comment in the test, but I agree that #688 should be addressed first and then this one, if still relevant.
