### ISSUE TITLE
Parser to create messages when it can't read stuff?

### ISSUE THREAD

**Issue by kerimoyle** [cellml/libcellml#686]
While working on the `Importer` functionality I had first-hand experience at how tricky it can be to figure out errors and unexpected behaviour in an imported model situation.  The biggest area that I struggled with was when the `Parser` didn't have any issues, but wasn't reading the file in the way I thought it should have been.  I'd like to take advantage of the different levels of `Issue` to create warnings/hints/messages when the `Parser` encounters anything that can't be instantiated into a model.

**Comment by agarny** [comment]
Seems reasonable to me.

**Comment by kerimoyle** [comment]
I should have known it wasn't going to be straightforward.  The errors I need are coming from the `model->linkUnits()` function, and because the `Model` class has no logger, they're not recorded anywhere ...
