### ISSUE TITLE
Make `pip install libcellml` functionality available

### ISSUE THREAD

**Issue by kerimoyle** [cellml/libcellml#697]
Does what it says ...

**Comment by nickerso** [comment]
So this is "currently available" as described here: #277. There is also #206, from which I suspect this ticket is really about the last step in that one of making the python bindings available on pypi? If so, suggest we close this one as a duplicate.

**Comment by kerimoyle** [comment]
You're right, it's the last step in #206.  The other is about linking to a local build, which wasn't what I was aiming for.  I'll close this and add 206 to the things-to-do-before-COMBINE list.
