### ISSUE TITLE
Check MathML2 for schema

### ISSUE THREAD

**Issue by kerimoyle** [cellml/libcellml#700]
We need to have a better way of making sense of the MathML than just the DTD, perhaps using a schema?

**Comment by agarny** [comment]
Failing that, we will need our `Analyser` to do some extra work to ensure that the MathML code is sensical.

**Comment by nickerso** [comment]
Just to reiterate my view that the only useful way to improve our handling of MathML is to move away from treating the MathML as strings, expose the AST tree directly in components, and validate the actual math using the Analyser. Anything else is not really going to offer significant improvements in the user experience and we shouldn't spend resource going down such paths. 

Suggest closing this issue.

**Comment by agarny** [comment]
> we should spend resource going down such paths.

"Should" or "shouldn't"? Anyway, I take it that you want things to be done in the analyser. Right now, a model that is analysed will result in an AST tree (if everything is fine) or issues (if something went wrong). So, it's just that by using a schema of something, we will make the analyser's job easier. This being said, I am happy either way.

**Comment by nickerso** [comment]
oops, good catch :) Using an XML Schema will not in any way make the Analyser's job any easier than the current DTD based validation.

**Comment by agarny** [comment]
Ok, I have never used a schema, so I shall take your word for it. :)

**Comment by agarny** [comment]
Ok, I am going to close this in favour of issue #688. That's going to be a "fun" (read: tedious) one to tackle, but I can see the reason for going that path.

**Comment by kerimoyle** [comment]
Should we add the other issue to the COMBINE targets?

**Comment by agarny** [comment]
?? Issue #688 is already there. (You are propbably the one who added it?)
