### ISSUE TITLE
Importer: Flattened models should not contain any importSource items

### ISSUE THREAD

**Issue by kerimoyle** [cellml/libcellml#702]
I've been able to break stuff by assuming that flat models have `model->importSourceCount() == 0` ... which isn't true in a few of our test cases.  It really should be zero, so we need to check where this is coming from ...

**Comment by agarny** [comment]
Strange indeed!

**Comment by nickerso** [comment]
I won't be zero for models that fail to flatten, right? are those the cases that we're talking about?

**Comment by kerimoyle** [comment]
No, these are successfully flattened models which have a non-zero import source count and a zero error count, eg:
Importer.missingUnitsFromImportOfCnTerms
Importer.importingComponentWithCnUnitsThatAreAlreadyDefinedInImportingModel
Importer.importUnitsNotDuplicated
Importer.rangeOfValidSituations
etc
There are about 12 of them.  I need to dig a little further ...

**Comment by kerimoyle** [comment]
Since we're exposing all of the `clone()` family of functions to users, we can't be sure how they'll be used.  For example, we use them internally during model flattening, where we know and can update parents of any cloned item.  But if someone clones an imported component, should the import source be cloned too or not?  
- If so, then cloning a model containing (say) 10 imports all from the same import source will result in a cloned model with 10 distinct import sources -> no longer an exact clone of the model.  
- If not, then we risk losing information unless the user knows to also clone the relevant import source too.
Thoughts anyone?

**Comment by agarny** [comment]
Rule of thumb: never assume that the end user knows how to "properly" use an API. The API should be such that it's bullet proof to use. So, if anything, I would definitely rule out option 2. As for option 1, I am not happy about it, but haven't thought about it hard enough to offer a viable alternative.

**Comment by nickerso** [comment]
I'd say yes to option 1, but it also means that model cloning needs to be smart enough to put all those cloned components into the same import source.

**Comment by agarny** [comment]
> I'd say yes to option 1, but it also means that model cloning needs to be smart enough to put all those cloned components into the same import source.

That's indeed what I would expect to see.

**Comment by kerimoyle** [comment]
So for the mechanism of model (and also component) cloning being smart enough ... my suggestions would be and/all of:
- overload the clone functions with an argument that we use internally to avoid duplication when it's not required;
- treat cloning of imported entities differently to cloning of non-imported stuff; and/or
- documentation documentation documentation ...
?

**Comment by nickerso** [comment]
When cloning a model the code would need to update the `ImportSource` for components and units that are imported in that model. That is the only place where you have the information to know whether the cloned imported components and units should be set to have the same `ImportSource` or not.

**Comment by kerimoyle** [comment]
It's bigger than just this ... unfortunately. When cloning a model we orphan units too (I figured I could follow the logic we used for those in fixing the imports, as it's kinda the same situation: a model owns an item (units/import) which is used somewhere else (variables/imported entities).  This test fails the last three lines:

```
TEST(Model, clonedModelOrphansUnits)
{
    auto model = libcellml::Model::create("model");
    auto units = libcellml::Units::create("units");
    auto component = libcellml::Component::create("component");
    auto v1 = libcellml::Variable::create("v1");
    auto v2 = libcellml::Variable::create("v2");

    model->addComponent(component);
    model->addUnits(units);
    component->addVariable(v1);
    component->addVariable(v2);
    v1->setUnits(units);
    v2->setUnits(units);

    EXPECT_EQ(model->component(0)->variable(0)->units(), model->component(0)->variable(1)->units());
    EXPECT_EQ(model->units(0), model->component(0)->variable(0)->units());
    EXPECT_EQ(model->units(0), model->component(0)->variable(1)->units());

    auto clonedModel = model->clone();

    EXPECT_EQ(clonedModel->component(0)->variable(0)->units(), clonedModel->component(0)->variable(1)->units());
    EXPECT_EQ(clonedModel->units(0), clonedModel->component(0)->variable(0)->units());
    EXPECT_EQ(clonedModel->units(0), clonedModel->component(0)->variable(1)->units());
}
```

**Comment by kerimoyle** [comment]
> When cloning a model the code would need to update the ImportSource for components and units that are imported in that model. That is the only place where you have the information to know whether the cloned imported components and units should be set to have the same ImportSource or not.

@nickerso So when cloning a component or units item in isolation, should the import source that they are connected to be duplicated or not?
- if so, then I will change the signature/arguments of the Component::clone() function to distinguish between whether it's being called from within a model clone, or on its own.
- if not, then we risk losing information but it's an easy fix.
