### ISSUE TITLE
Model::linkUnits() not working properly?

### ISSUE THREAD

**Issue by kerimoyle** [cellml/libcellml#712]
I have a situation where I rename a `Units`, which should raise a validation error as the previous units name was used by a variable.  It works as expected if you **don't** call `model->linkUnits()` but as soon as you do, it fails ... @hsorby any thoughts?

```
TEST(Model, renameUnits) {
    auto model = createModelTwoComponentsWithOneVariableEach("model", "c1", "c2", "v1", "v2");
    auto v1 = model->component("c1")->variable("v1");
    auto v2 = model->component("c2")->variable("v2");

    auto u = libcellml::Units::create("units1");
    model->addUnits(u);

    v1->setUnits("units1");
    v2->setUnits("units2");

    // model->linkUnits();  // If this is included, the test below fails.

    // Validate the model, expect error related to missing units "units2"
    auto validator = libcellml::Validator::create();
    validator->validateModel(model);
    EXPECT_EQ(size_t(1), validator->errorCount());
    printIssues(validator); // Prints: Variable 'v2' in component 'c2' has a units reference 'units2' which is neither standard nor defined in the parent model.

    // Rename the units1 to be called "units2".
    u->setName("units2");
    // model->linkUnits();  // If this is included, the test below fails. 

    validator->validateModel(model);
    EXPECT_EQ(size_t(1), validator->errorCount()); // FAILS: No errors reported when model->linkUnits() has been called at any point.
}
```

**Comment by kerimoyle** [comment]
Thinking about this more I can see where it's coming from ... but really I don't like it!  The way that the `Variable::setUnits(std::string)` function works is to create a dummy Units pointer with the same name as the string submitted.  This means that we have the possibility of weirdness when users set a variable's units by a string (creating a link to new, fake units), and then later adjust the names of the units objects.  I think that this should change: I think we should store the units' name separately, and then only create the link when asked for it, and only to properly defined units.  What do others think? @hsorby @agarny @nickerso

**Comment by nickerso** [comment]
> and then only create the link when asked for it,

isn't that the whole point of `linkUnits()` ?

**Comment by kerimoyle** [comment]
Yes.  But that's not what's happening, since the addUnits function actually creates an orphaned item.

**Comment by nickerso** [comment]
not sure I follow. Don't you get the behaviour you are expecting if you set the variable units by object rather than name? `setUnits` (typo in your reply?) by name will always create a dummy orphan units object and when you link the units up in the context of a model you get the resolved object. From there you can rename the object and everything would work as expected.

**Comment by kerimoyle** [comment]
As it stands, we end up with one set of units, not two.  I would expect that where `setUnits` was called with a string, that that relationship persists, so that changing the name of a Units item would mean that `v1` couldn't find its units anymore rather than making both `v1` and `v2` have the same units.  In order to do that, we'd have to store the name as a string separate from the pointer.  The `linkUnits` function would then go through and update properly.

**Comment by hsorby** [comment]
Closing this because `linkUnits` is working as expected.
