### ISSUE TITLE
Imported Entity: remove the `setResolved()` method from the API

### ISSUE THREAD

**Issue by agarny** [cellml/libcellml#724]
In PR #685, the `ImportedEntity::setResolved()` method is available through the API while there is no reason for this, but is "needed" so that another class can call it. Instead, we probably ought to make any class that needs to call `ImportedEntity::setResolved()` a friend of `ImportedEntity` (I don't personally like friend classes, but this might be one of those cases where this is needed).

See https://github.com/cellml/libcellml/pull/685/files#r496388838.

**Comment by hsorby** [comment]
`setResolved` method has been removed from the API.
