### ISSUE TITLE
Generator should provide the ability to specify the name of the header file that's included.

### ISSUE THREAD

**Issue by kerimoyle** [cellml/libcellml#736]
At the moment the top of the generated *.c code contains a line `#include "model.h"`.  This means that either users always have to name their files "model" (which seems way too restrictive to be helpful) or they have to edit the generated code (which we don't want).  I'd like there to be an option in the Generator API where we can set what we want this to be.

**Comment by agarny** [comment]
I believe we are all set for that. See `GeneratorProfile::setInterfaceFileNameString()`.

**Comment by kerimoyle** [comment]
Ah ... it's in the `GeneratorProfile` not the `Generator` ... :)  Does that mean we need to create a new profile for each new model we generate code for?

**Comment by agarny** [comment]
No, you can retrieve the (default C++) profile and update it as you see fit.
