### ISSUE TITLE
Code formatting tidy-up

### ISSUE THREAD

**Issue by dladd** [cellml/libcellml#75]
To standardise practices in the codebase, a formatting tidy-up has been proposed after pulls #71 and #68 come through.

I'll add to and edit the list of changes to be implemented in this opening comment based on agreed upon features in the discussion below.
### Practices to standardise
- [x] Increment should be done in pre-form (`++i` rather than `i++`) when the methods are otherwise equivalent.
- [x] Conditional and loop statements should have a space before opening parentheses. E.g., `for (` rather than `for(`.
- [x] Doxygen comments should be in sentence-style: beginning with capitalisation and ending with punctuation.
- [x] Test names should be in camelCase and explicit to help identify which specific features they cover.
- [x] Spaces should be used for indentation- not tabs.

**Comment by dladd** [comment]
Another issue was brought up in #68 is the shorthand currently standard in tests.

It was suggested that names and tested variable values should be made explicit. This includes
- Variable abbreviations- e.g., `expected` rather than `e`, `actual` rather than `a`, and `variable` rather than `v`.
- Tested values/names should be defined as constants rather than directly manipulating strings

For example, the current

``` c++
TEST(Variable, setInitialValueByString_shorthand) {
    const std::string e = "<variable initial_value=\"0.0\"/>";
    libcellml::Variable v;
    v.setInitialValue("0.0");
    std::string a = v.serialise(libcellml::FORMAT_XML);
    EXPECT_EQ(e, a);
}
```

versus the explicit

``` c++
TEST(Variable, setInitialValueByString_explicit) {
    const std::string initialValue = "0.0";
    const std::string expected = "<variable initial_value=\"" + initialValue + "\"/>";
    libcellml::Variable variable;
    variable.setInitialValue(initialValue);
    std::string actual = variable.serialise(libcellml::FORMAT_XML);
    EXPECT_EQ(expected, actual);
}
```

Personally, I prefer the _shorthand version as I find it easier to follow.

**Comment by hsorby** [comment]
+1 to using shorthand version in the tests.  The test code is not examplar code, it's short snippets to test the library.  I'm fine with the other suggestions from comment 1.

**Comment by agarny** [comment]
I like things to be explicit, but I am happy to go with the shorthand version. I just want (and need :)) consistency.

Otherwise, we might want to add the use of spaces rather than tabs in the list in comment 1? Also, that list probably ought to be mentioned in an 'official' document somewhere. Maybe in [dev_coding_standard.rst](https://github.com/cellml/libcellml/blob/develop/docs/dev_coding_standard.rst)?

**Comment by dladd** [comment]
I think a lot of these so far are explicitly or implicitly part of the Google style guide- for example [spaces instead of tabs](https://google.github.io/styleguide/cppguide.html#Spaces_vs._Tabs). The trick will be spotting inconsistencies that may have crept in and propagated around.

Once we get a list here we are happy with, I'll be sure to update that doc with any exceptions or additions like the "correct sentence Doxygen comment" and "test naming" items.

**Comment by dladd** [comment]
Apologies- I accidentally hit "close and comment" rather than "comment". I blame my iPad...

**Comment by dladd** [comment]
I've changed the Doxygen comment item from "full sentences" to "sentence-style: beginning with capitalisation and ending with punctuation" as I think that better describes what we're after. For example

``` cpp
class Component; /**< Forward declaration of Component class. */
```

nicely and succinctly comments the line but isn't necessarily a complete sentence.

**Comment by dladd** [comment]
I'd like to propose that Doxygen comments starting with code-words be exempt from capitalisation. They can instead be pre-empted by "@c" to render them in typewriter font. For example, the return on: 

``` cpp
    /**
     * @brief Serialise entity to std::string.
     * @param format The format to serialise the object to.
     * @return @c std::string representation of the object.
     */
    std::string serialise(libcellml::FORMATS format) const;
```

for which you can find the [generated version here](http://autotest.bioeng.auckland.ac.nz/libcellml-buildbot/b8a163fb017ccc9def0bd1eea60b7f25f9020705/dox/code/classlibcellml_1_1Entity.html#a069846deec77c02ca04cbd2541c79535)

**Comment by dladd** [comment]
I've updated the "test naming" item to specify names in camelCase.

**Comment by dladd** [comment]
Another thing "we" should add to the exceptions in [dev_coding_standard.rst](https://github.com/cellml/libcellml/blob/develop/docs/dev_coding_standard.rst) is that we use 4-space indentation rather than the [2-space indentation specified in the Google style guide](https://google.github.io/styleguide/cppguide.html#Spaces_vs._Tabs). :-)

**Comment by agarny** [comment]
> Another thing "we" should add to the exceptions in [dev_coding_standard.rst](https://github.com/cellml/libcellml/blob/develop/docs/dev_coding_standard.rst) is that we use 4-space indentation rather than the [2-space indentation specified in the Google style guide](https://google.github.io/styleguide/cppguide.html#Spaces_vs._Tabs). :-)

FWIW, 2-space indentation is currently being used in CMake files while 4-space indentation indeed for C++ files.

**Comment by agarny** [comment]
Closing as per comment https://github.com/cellml/libcellml/pull/76#issuecomment-210353994.
