### ISSUE TITLE
Failing `io_unit_test_parser` test

### ISSUE THREAD

**Issue by MichaelClerx** [cellml/libcellml#751]
```
99% tests passed, 1 tests failed out of 67

Total Test time (real) =  18.64 sec

The following tests FAILED:
	 15 - io_unit_test_parser (Failed)
Errors while running CTest
make: *** [Makefile:172: test] Error 8
```

**Comment by MichaelClerx** [comment]
What do I type to get you some more debug info?

**Comment by agarny** [comment]
You may want to `rgrep` `io_unit_test_parser`, to give you the path to the `.log` file. From there, you should get a bit more information. Personally, I build/debug libCellML using an IDE like Qt Creator, which allows me to run a particular target, e.g. the `Parser` target. From there, I can put traces, etc.

**Comment by MichaelClerx** [comment]
```
[ RUN      ] Parser.parseInvalidXmlDirectlyUsingLibxml
/:2: parser error : Opening and ending tag mismatch: component line 2 and model
<model xmlns="http://www.cellml.org/cellml/2.0#"><component></model>
                                                                    ^
/:2: parser error : EndTag: '</' not found
<model xmlns="http://www.cellml.org/cellml/2.0#"><component></model>
                                                                    ^
[       OK ] Parser.parseInvalidXmlDirectlyUsingLibxml (0 ms)
[ RUN      ] Parser.invalidXMLElements
/home/michael/dev/cellml/libcellml/source/tests/parser/parser.cpp:57: Failure
Expected equality of these values:
  expectedIssues.at(i + 1)
    Which is: "LibXml2 error: Opening and ending tag mismatch: Dwarf line 3 and ShortGuy."
  p->issue(i)->description()
    Which is: "LibXml2 error: Opening and ending tag mismatch: Dwarf line 2 and ShortGuy."
/home/michael/dev/cellml/libcellml/source/tests/parser/parser.cpp:57: Failure
Expected equality of these values:
  expectedIssues.at(i + 1)
    Which is: "LibXml2 error: Opening and ending tag mismatch: Hobbit line 4 and EvenShorterGuy."
  p->issue(i)->description()
    Which is: "LibXml2 error: Opening and ending tag mismatch: Hobbit line 2 and EvenShorterGuy."
/home/michael/dev/cellml/libcellml/source/tests/parser/parser.cpp:57: Failure
Expected equality of these values:
  expectedIssues.at(i + 1)
    Which is: "LibXml2 error: Opening and ending tag mismatch: Wizard line 5 and SomeGuyWithAStaff."
  p->issue(i)->description()
    Which is: "LibXml2 error: Opening and ending tag mismatch: Wizard line 2 and SomeGuyWithAStaff."
/home/michael/dev/cellml/libcellml/source/tests/parser/parser.cpp:57: Failure
Expected equality of these values:
  expectedIssues.at(i + 1)
    Which is: "LibXml2 error: Opening and ending tag mismatch: Elf line 6 and fellows."
  p->issue(i)->description()
    Which is: "LibXml2 error: Opening and ending tag mismatch: Elf line 2 and fellows."
/home/michael/dev/cellml/libcellml/source/tests/parser/parser.cpp:57: Failure
Expected equality of these values:
  expectedIssues.at(i + 1)
    Which is: "LibXml2 error: Premature end of data in tag fellowship line 2."
  p->issue(i)->description()
    Which is: "LibXml2 error: EndTag: '</' not found."
[  FAILED  ] Parser.invalidXMLElements (0 ms)
```

**Comment by agarny** [comment]
Which version of libCellML are you trying to build? Which platform? It looks like some Linux distribution?

**Comment by MichaelClerx** [comment]
```
-----------------------------------------------
    Welcome to libCellML!
    This version number is 0.2.0
-----------------------------------------------
```
It's the develop branch installed following the tutorial guidelines.

Looks to me like the error is intentional but the error message isn't what you're expecting?

Running Fedora 30, libxml2 2.9.10-3.

**Comment by agarny** [comment]
Let me try on Ubuntu using https://libcellml-tutorials.readthedocs.io/en/combine/installation/build_from_source.html since I believe this is what you used.

**Comment by MichaelClerx** [comment]
Carissa in the tutorial reports the same on Ubuntu 20.04.1 LTS, libxml2-dev 2.9.10+dfsg-5

**Comment by carissableker** [comment]
This is me!

**Comment by agarny** [comment]
Ok, just for the record, I can indeed confirm the issue on Ubuntu 20.04, but not Ubuntu 18.04. This is due to a difference in the version of libxml2 used on those two versions of Ubuntu.

Now, when it comes to the "failing" test, this is nothing to worry about. This is a tests that "fails" and retrieves the error from libxml2 and the "new" version of libxml2 generates a slightly different error message, hence it fails on Ubuntu 20.04, but not Ubuntu 18.04 which is the version of Ubuntu that we use for our continuous integration.

@hsorby: this is just so that you know. :)

**Comment by kerimoyle** [comment]
Hey folks!  I was just about to fix this, but I'm a little concerned by the actual messages coming back.  It seems that they're all reporting that the problem is in line 2 ... when it's not ... so I think that the problem is actually internal to the newer version of libXML2.  I know that we have no control over this error message, so I'll make a patch so that the tests pass for both versions, but it's probably worth keeping this issue open (or starting another) so that we can remember what's going on, and update the test if/when that's ever fixed?  FYI this is the input string:
```
    const std::string in =
        "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
        "<fellowship>\n"
        "  <Dwarf bearded>Gimli</ShortGuy>\n"
        "  <Hobbit>Frodo</EvenShorterGuy>\n"
        "  <Wizard>Gandalf</SomeGuyWithAStaff>\n"
        "  <Elf>\n"
        "</fellows>\n";
```

**Comment by agarny** [comment]
> ..., but it's probably worth keeping this issue open (or starting another) so that we can remember what's going on, and update the test if/when that's ever fixed?

Yes, definitely.

> FYI this is the input string:
> 
> ```
>     const std::string in =
>         "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
>         "<fellowship>\n"
>         "  <Dwarf bearded>Gimli</ShortGuy>\n"
>         "  <Hobbit>Frodo</EvenShorterGuy>\n"
>         "  <Wizard>Gandalf</SomeGuyWithAStaff>\n"
>         "  <Elf>\n"
>         "</fellows>\n";
> ```

What error message does libxml2 generate exactly?

**Comment by kerimoyle** [comment]
The ones from Michael are in the earlier comment.  Each of the expected values has a proper line number that makes sense, each of the given ones mentions only line 2 ...
