### ISSUE TITLE
I can't access the core libcellml types?

### ISSUE THREAD

**Issue by MichaelClerx** [cellml/libcellml#753]
Step 1 in the combine tutorial, the old-fashioned way:

    libcellml::Model model;
    model = libcellml::Model::create();

Not allowed!

    /home/michael/dev/cellml/libcellml/tutorials/c1-creating/createGateModel.cpp: In function ‘int main()’:
    /home/michael/dev/cellml/libcellml/tutorials/c1-creating/createGateModel.cpp:33:22: error: ‘libcellml::Model::Model()’ is private within this context

**Comment by agarny** [comment]
Yes, you need it to read: `libcellml::ModelPtr model;`

**Comment by MichaelClerx** [comment]
Thanks

**Comment by agarny** [comment]
FTR, this is why I personally just write `auto model = libcellml::Model::create();`.
