### ISSUE TITLE
Renaming of branches in the repository.

### ISSUE THREAD

**Issue by hsorby** [cellml/libcellml#758]
To remove offensive terms from day to day use GitHub and Git are moving away from using `master` as the label for the default branch ([see here](https://sfconservancy.org/news/2020/jun/23/gitbranchname/)).

This will have an effect on us and how we have setup our development eco-system.

I personally support this change and would like to move this forward.  We have some options open to us about what we can do but now is potentially a good time for us to address this while we have only a few open pull requests.

GitHub will be rolling out tools to make this change very seamless.  We could wait for this but I feel the benefit for our project will be minimal and one we can manage for ourselves.  Of course the GitHub tools will not help with our Buildbot testing that may keel over with this change.

**Comment by hsorby** [comment]
My proposal would be for the following renaming scheme:

```
master => release(s)
develop => main
```

**Comment by kerimoyle** [comment]
I'm happy to rename master -> release, but I'd rather keep develop as is.  Main implies it's more stable than it actually is ... (and doesn't actually mean anything).  Develop is accurate, not offensive, and understood by the community.

**Comment by hsorby** [comment]
`main` is (going to be) defined as the main branch for development.  So I think it would be a good idea to align with this understanding.

**Comment by agarny** [comment]
I find that move away from`master` to be PC gone mad, but we indeed have no choice, so may as well get ready for it.

So, why not simply keep `develop` as is and have `master` changed to `main`?

**Comment by hsorby** [comment]
Our `master` branch is currently defined as our release branch (if you read the documentation) so I think it would be better served with a name the truly reflects the purpose of the branch.

**Comment by agarny** [comment]
Ok, happy to go with:
 - `master` -> `release`; and
 - `develop` -> `main`.

**Comment by kerimoyle** [comment]
... except that since we release once a decade, it's basically dead!  I think @agarny 's suggestion is good.

**Comment by hsorby** [comment]
I am currently writing a release script so it becomes much easier to make a release !!

**Comment by agarny** [comment]
> I am currently writing a release script so it becomes much easier to make a release !!

Looking forward to it. Regular "snapshots" would certainly be nice to have.

**Comment by agarny** [comment]
Thinking of it, such snapshots (if we were to go with that idea) might be best pushed to a special branch called `snapshot`?

**Comment by hsorby** [comment]
This has now been actioned:

master => release
develop => main
