### ISSUE TITLE
LLVM/Clang 11 is released, should we support it

### ISSUE THREAD

**Issue by nickerso** [cellml/libcellml#765]
A new version of LLVM has been released, is this something we should support. Looks like the only changes required are given in #761.

**Comment by agarny** [comment]
When it comes to compiling libCellML, #761 is indeed all that is required (and it clearly also works with LLVM 10). However, something to keep in mind is that ClangFormat 11 formats our source code slightly differently:

<img width="1324" alt="Screen Shot 2020-10-27 at 20 07 39" src="https://user-images.githubusercontent.com/602265/97268027-1c0e7980-1890-11eb-9e9c-25fb3f7ee6c3.png">

**Comment by hsorby** [comment]
Closing as LLVM/Clang 11 is supported now.
