### ISSUE TITLE
Segfault in model flattening

### ISSUE THREAD

**Issue by kerimoyle** [cellml/libcellml#766]
Perhaps related to earlier issue #589, but found under different circumstances so I'm making a separate issue.  The model flattening process segfaults when we have a model with circular imports because the function `hasUnresolvedImports` relies on recursion (which never ends!).  We should make use of the cleaner way to iterate through imports using the model's `ImportSource` pointers instead of recursive searches that segfault.  Here's the test that fails:

```
TEST(ModelFlattening, KRM)
{
    auto parser = libcellml::Parser::create();
    auto originalModel = parser->parseModel(fileContents("modelflattening/segfault/importExample2b.cellml"));
    auto importer = libcellml::Importer::create();

    // Resolve the imports.
    importer->resolveImports(originalModel, resourcePath("modelflattening/segfault/"));

    // Check for issues: expect one reporting the circular import.
    EXPECT_EQ(size_t(1), importer->issueCount());
    printIssues(importer);

    // Attempt to create a flattened version even though there's been a warning.
    auto flatModel = importer->flattenModel(originalModel); // segfaults
}
```
The model files are:

importExample2b.cellml
```
<?xml version="1.0" encoding="UTF-8"?>
<model xmlns="http://www.cellml.org/cellml/2.0#" name="importExample2b">
  <import xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="circularImport1.cellml">
    <component component_ref="shared" name="sideB"/>
  </import>
</model>
```

circularImport1.cellml
```
<?xml version="1.0" encoding="UTF-8"?>
<model xmlns="http://www.cellml.org/cellml/2.0#" name="circularImport1">
  <import xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="circularImport2.cellml">
    <component component_ref="circular2" name="shared"/>
  </import>
</model>
```

circularImport2.cellml
```
<?xml version="1.0" encoding="UTF-8"?>
<model xmlns="http://www.cellml.org/cellml/2.0#" name="circularImport2">
  <import xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="circularImport1.cellml">
    <component component_ref="shared" name="circular2"/>
  </import>
</model>
```

**Comment by agarny** [comment]
I feel like it might be one of those cases where @hsorby and @nickerso (?) might wonder why you are calling `Importer:: flattenModel()` when `Importer::issueCount()` doesn't return `0`? IOW, he/they might say that you asked for trouble and you got it. :) (This is what I remember from some previous conversations, but happy to be corrected!)

Personally, I am of the view that any call to the API should be "safe". IOW, I wouldn't expect `Importer::flattenModel()` to segfault, no matter what is thrown at it.

**Comment by kerimoyle** [comment]
My thinking was that since it's not invalid to have circular imports (the issue returned is only a `WARNING`), it's pretty easy for the user to assume that they can sort it out later, and then get a segfault.  I think that we could upgrade it to an `ERROR` and/or include something that checks for importer issues before flattening.  But it would also be good to make better/wider use of the two-way lookup to import source items since that's likely to be more efficient than a lot of `if` statements in recursive function calls.  

In any case, I think we should make it as hard as possible for someone to segfault.  It will never be impossible since they can always call things like `model->component(-99)->variable("i_dont_exist")->name()` etc.

**Comment by kerimoyle** [comment]
After discussions this week it's decided that we:
- upgrade the issue created for circular imports to an `ERROR`; and
- test for circularity before attempting to flatten a model to prevent the segfault.
This will be done in #767.
