### ISSUE TITLE
Should empty import sources be printed?

### ISSUE THREAD

**Issue by kerimoyle** [cellml/libcellml#775]
Should the `Printer` write models containing an empty import source like this?

```
  <import xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="importedModel.cellml"/>
```

**Comment by agarny** [comment]
I don't find it "clean" to print something that is meaningless, but I understand that the printer is to print the contents of a model description. So, if the user has created an empty import source then... it should be printed. Indeed, the user may, later on, decide to reopen the CellML model, and add imports to it and, here, s/he could do it without first having to recreate the import source.

**Comment by kerimoyle** [comment]
> Indeed, the user may, later on, decide to reopen the CellML model, and add imports to it and, here, s/he could do it without first having to recreate the import source. 

That was my thinking.  Even though they might be currently "empty", they still contain data (the url), which shouldn't be thrown away by default. It's the same as having empty components.

**Comment by agarny** [comment]
> It's the same as having empty components.

Exactly.

**Comment by kerimoyle** [comment]
After discussions this week, we should make a utility function in the `Model` class that will remove any unused or empty items without changing the underlying model semantics.
