### ISSUE TITLE
isResolved() should do more of the work in determining if an imported entity is resolved.

### ISSUE THREAD

**Issue by hsorby** [cellml/libcellml#786]
I think the `isResolved` method of an imported entity would be better placed on the importer class as that is the object that answers the question.

**Comment by hsorby** [comment]
I'll answer my own question ... No.  I think `isResolved` could possibly just be better implemented.

**Comment by nickerso** [comment]
so we can close this one?

**Comment by hsorby** [comment]
No, `isResolved` still needs a better implementation.

**Comment by hsorby** [comment]
Decided to change the name of this issue rather than start a new one and close this one.  I was on the right track but came up with the wrong idea about the solution initially.
