### ISSUE TITLE
ImportSource shouldn't be a parentable entity.

### ISSUE THREAD

**Issue by hsorby** [cellml/libcellml#803]
The ImportSource class I think would benefit from not being a parentable entity.

**Comment by kerimoyle** [comment]
I don't understand what the benefits are?  I would have thought that they would follow the same kind of parent structure as `Units`?

**Comment by hsorby** [comment]
To my way of thinking the ImportSource doesn't belong to one thing or sit in a hierarchy.  It is a container for the source of an import.  A Units may have an import source as well as a Component may have an import source.  But other Units or Components may have the same import source so a Units or Component cannot be a parent of an ImportSource. A Model doesn't own an ImportSource it is independent of a Model and therefore a Model cannot be a parent of an ImportSource.  

Given this there is not need for an ImportSource to be parentable.
