### ISSUE TITLE
Units: breaking down of some standard units is wrong

### ISSUE THREAD

**Issue by agarny** [cellml/libcellml#806]
While working on issue #496, @awickens identified a couple of of mistakes in the breaking down of `coulomb` and `farad` in `src/utilities.h`:
 - `{"coulomb", {{"ampere", -1.0}, {"second", 1.0}}},` should be replaced with
   `{"coulomb", {{"ampere", 1.0}, {"second", 1.0}}},`; and
 - `{"farad", {{"ampere", 2.0}, {"kilogram", -1.0}, {"metre", -2.0}, {"second", -4.0}}},` should be replaced with
   `{"farad", {{"ampere", 2.0}, {"kilogram", -1.0}, {"metre", -2.0}, {"second", 4.0}}},`.

**Comment by kerimoyle** [comment]
This is weird!  These were fixed about 6 months ago ... not sure where the gremlins have come from :(

**Comment by agarny** [comment]
Hmm... https://github.com/cellml/libcellml/blame/develop/src/utilities.h tells me the last time this part of the code was modified was 2 years ago...?
