### ISSUE TITLE
ClangFormat: only run the ClangFormat test if we have at least version 11 of ClangFormat

### ISSUE THREAD

**Issue by agarny** [cellml/libcellml#808]
The reason for this is that the formatting that results from ClangFormat version 11+ (vs. version 10-) is slightly differently:

<img width="1324" alt="Screen Shot 2020-10-27 at 20 07 39" src="https://user-images.githubusercontent.com/602265/97268027-1c0e7980-1890-11eb-9e9c-25fb3f7ee6c3.png">

**Comment by nickerso** [comment]
why is this a problem? i.e., it would be good to have some useful information rather than "No description provided".

**Comment by agarny** [comment]
> why is this a problem? i.e., it would be good to have some useful information rather than "No description provided".

Added some description.
