### ISSUE TITLE
Current thinking on connections

### ISSUE THREAD

**Issue by dladd** [cellml/libcellml#82]
The next feature to build on from the use-cases doc is 1.xii: a model with connections. I thought it would be a good idea to put down some of the current thinking on how things might fit together.

Consider a simple serialised model with a connection:

``` xml
    <?xml version=\"1.0\" encoding=\"UTF-8\"?>
    <model xmlns=\"http://www.cellml.org/cellml/1.2#\">
      <component name=\"component1\">
        <variable name=\"variable1\"/>
      </component>
      <component name=\"component2\">
        <variable name=\"variable2\"/>
      </component>
      <connection>
        <map_components component_1=\"component1\" component_2=\"component2\"/>
        <map_variables variable_1=\"variable1\" variable_2=\"variable2\"/>
      </connection>
    </model>
```

To build this up, two options have been discussed so far: (1) allowing direct access to connections through the API and (2) keeping connections "under the hood":
- 1. The connection is built through the API and passed variables to map: e.g.,

``` c++
    libcellml::Model m;
    // Create connection object.
    libcellml::ConnectionPtr connection1 = std::make_shared<libcellml::Connection>(); 
    libcellml::ComponentPtr comp1 = std::make_shared<libcellml::Component>();
    libcellml::ComponentPtr comp2 = std::make_shared<libcellml::Component>();
    libcellml::VariablePtr v1 = std::make_shared<libcellml::Variable>();
    libcellml::VariablePtr v2 = std::make_shared<libcellml::Variable>();

    comp1->setName("component1");
    comp2->setName("component2");
    v1->setName("variable1");
    v2->setName("variable2");

    comp1->addVariable(v1);
    comp2->addVariable(v2);
    m.addComponent(comp1);
    m.addComponent(comp2);
    // Pass the two variables to the connection object
    connection1.mapVariables(v1,v2); 
    // Add the connection to the model
    m.addConnection(connection1); 
```
- 2. The connection is instantiated as a part of the model inside the library: e.g., don't create `connection1` and replace the last two non-comment lines from (1) with:

``` c++
    ...
    // Instantiate the connection; pass v1 and v2 to the connection; add the connection to the parent model
    v1.isEquivalentTo(v2); 
```

In both cases, I am assuming that we get each component for `map_components` as each variable's respective parent component. In (2) I also assume that we can similarly get the parent model from these components to instantiate a new connection. 

In discussions at the ABI on Friday, I believe the team here were more in favour of option (2). It is arguably more user-friendly and specifying the operations associated with connection in the `Variable` class allows for a cleaner set of overloaded functions. There was also some debate over whether the concept of a connection was relevant to a user.

However, while (1) may be a bit more clunky, it relaxes the requirements on variables passed to the connection. For a valid model, the mapped variables do not need to have parent components or models until serialisation. (1) also allows for invalid definitions of connections (e.g., variables without parent components), which has been standard for testing other features so far (e.g., variables without defined units). Thus (1) is also more conducive to testing. In contrast, (2) requires mapped variables to have both parent components and parent models at execution of `isEquivalentTo()` in order to instantiate the connection.

~~I am therefore now more in favour of option (1) personally.~~

**Comment by jonc125** [comment]
Firstly, I think the question of what is better for testing is irrelevant. We should only be considering what _users_ of the library would like to do, and design accordingly.

From this perspective, option (2) is a _much_ cleaner API, and also a better conceptual match for what connections represent.

You do raise a valid point about users possibly wanting to specify a connection before the variables have been added to a model. I'm not sure this is that likely, however, since there isn't really a need to connect variables until they exist in separate components - you can just talk about a single variable up to that point. So perhaps what would address that use case better is a method to create a second instance of a variable in another component and connect it to the original one?

**Comment by nickerso** [comment]
I'm not sure I'm seeing a problem if I want to make statements like `v1.isEquivalentTo(v2)` before either `v1` or `v2` is added to a model. Setting a variable to be equivalent to another variable is simply setting a property on that variable object, but it is a property that is only ever used in the context of a model. When serialising a variable, it is a property that is not serialised. Same for components.

If you then serialise a model, then you would need to iterate over all variables that _are in the model_ looking for equivalence relationships and then serialising them as connections. If `v1` and `v2` are not both added to components in  the model prior to serialisation then that particular equivalence relationship is not applicable to that model and wouldn't be serialised. Or perhaps serialised as an incomplete connection?

**Comment by jonc125** [comment]
Indeed, that would be another way to approach implementation. Essentially having an 'equivalence set' object attached to variables (by reference counting pointers, presumably), merge sets when variables are connected that are already in sets, etc. So a bit more work for implementation (e.g. checking that you don't serialise a connection twice) and testing these cases, but arguably a much nicer user interface. And it'll support later use cases that want easily to iterate over equivalence sets and the like as well (code generation for instance).

**Comment by dladd** [comment]
Interesting- I admit that is different to how I had envisioned connections in the first place. I was thinking we need to instantiate connection objects as soon as they are defined but, as you both say, we can instead just flag those operations to happen at serialisation with objects that indicate the relationships.  

So (2) could instead be implemented as (2.1):

``` c++
    ...
    // Set "equivalence" objects on variables v1 and v2
    v1.isEquivalentTo(v2); 
```

**Comment by hsorby** [comment]
If I had a variable <code>v1</code> and I added it to component <code>c1</code> and then added it to component <code>c2</code>, would that then constitute a connection?  This I think would work nicely with an equivalence set.

I don't see a need for a connection object to be available in the API it just means more work for the user.  Because we think it is better for testing doesn't feel like a reason that I would give much weight to.

**Comment by jonc125** [comment]
We'd need to be careful on whether adding a variable to 2 components meant connection or move. For that reason it might be better to have explicit methods for (one or both of) these and disallow adding a variable to a component if it was already in another.

Also, a variable may well have different interfaces (and even different names & units) in different components, so the 'multiple add' wouldn't make sense in such cases.

**Comment by agarny** [comment]
From the perspective of an API user, I am also in favour of option 2. Much cleaner indeed.

However, I can't help but think about the `CellML Annotation` and `CellML Text` views in OpenCOR. In those views, we need to know what connections exist in a given model. So, how would we go about extracting such information using libCellML?

**Comment by agarny** [comment]
Ok, just remembered that the `CellML Text` view uses the DOM. The `CellML Annotation` view uses the CellML API to get everything it needs, but it could equally have used the DOM too.

In other words, I am happy with option 2, no (more) questions asked. :)

**Comment by jonc125** [comment]
Out of curiosity, why would the annotation view need to know about connections as a entities in their own right, rather than variable equivalences?

**Comment by agarny** [comment]
> Out of curiosity, why would the annotation view need to know about connections as a entities in their own right, rather than variable equivalences?

I wondered the same, but annotation experts told me that we ought to be able to annotate anything in a CellML file. This is not 100% the case at the moment (with regards to the `CellML Annotation` view), but it's certainly more than what I had originally planned.

**Comment by mtcooling** [comment]
+1 to option (2), and I personally like the
equivalence-network-that-may-or-may-not-mean-connections paradigm.

Testing - the assumption there seems to be that libcellML is used to build
the test cases. If so, that to me an additional reason not to go that way -
there is no reason why libcellml should be used to build all test cases and
actually doing so may lead to situations where two bugs in the library
cancel each other out.

2c,

**Comment by mtcooling** [comment]
...or even mean a copy...

Without a description of the semantics in the API, I would, as a user
familiar with CellML, have expected a) adding equivalence to variables that
don't exist and b) adding the same variable to two components, to both be
nonsensical. That's just some feedback if you like. Of course one could
define it another way but I think it would be worth really defining as JC
seems to imply.

**Comment by mtcooling** [comment]
> and I personally like the
> equivalence-network-that-may-or-may-not-mean-connections paradigm

possible fly in the ointment for this though might be on the requirement to
preserve relative position of cellml elements and whitespace - might be a
bit inelegant to do for connections if they aren't represented as things...

**Comment by dladd** [comment]
Thanks all- this is very helpful. Setting equivalence on variables (2) definitely sounds like the way to go. I'll leave my original statement favouring (1) in place for posterity but I think this is unanimous. I'd just suggest we change the method name from "isEquivalentTo" to "setEquivalentTo"- e.g., (2.2)

``` c++
    ...
    // If v2 is not already in mEquivalentVariables on v1, add it
    v1.setEquivalentTo(v2); 
```

Since the "is" prefix on methods appears to be associated with Boolean return values (e.g., `isImport()`).

Re:

> I would, as a user familiar with CellML, have expected a) adding equivalence to variables that don't exist and b) adding the same variable to two components, to both be nonsensical.

That's fair enough- if others agree we could throw an exception if (a) the equivalent variable does not exist  and (b) the variable passed to `addVariable()` already has a parent component.

Re:

> possible fly in the ointment for this though might be on the requirement to preserve relative position of cellml elements and whitespace

I believe the current thinking on this (see [discussion here](https://github.com/cellml/libcellml/pull/80#discussion_r59843887)) is to carry on with semantically equivalent serialisations and not worrying about whitespace until we hit the parts of the roadmap that require a particular serialisation. Good to keep in mind though.

**Comment by mtcooling** [comment]
> I believe the current thinking on this (see discussion here
> https://github.com/cellml/libcellml/pull/80#discussion_r59843887) is to
> carry on with semantically equivalent serialisations and not worrying about
> whitespace until we hit the parts of the roadmap that require a particular
> serialisation.

This comment in that discussion

"....., we just need to the tools to get the same meaning from the same
document, for this we only need semantically equivalent serialisation."

is incorrect.

I think leaving it until later will either lead to a) not meeting that
requirement or b) only meeting it with a lot of rework, facing the very
challenges that are being avoided this time around. I would strongly
recommend not leaving these decisions until 'later' - they won't get any
easier. It might feel like progress but it isn't.

**Comment by mtcooling** [comment]
Re:

if others agree we could throw an exception if (a) the equivalent variable
does not exist and (b) the variable passed to addVariable() already has a
parent component.

Well, for a) at least, possibly you want to allow the in-memory version to
be invalid in that way, especially to support this from the 'current
thinking' (http://libcellml.readthedocs.org/en/latest/current_thinking.html
):
 Validation is going to be quite separate (you are free to make invalid
CellML models).

Which presumably means you may also want to read in invalid models prior to
manipulation or roadmap milestone 4 (validation) etc.

**Comment by agarny** [comment]
@mtcooling, I must say that I find your comments difficult to follow. Can't you have everything in one comment? Also, if you want to quote someone (which looks like you might be doing at least once), then you want to prepend that other person's comment with `>`, as @dladd has done just above and I am doing below.

Anyway, back to business:

>  I'd just suggest we change the method name from "isEquivalentTo" to "setEquivalentTo"

+1

> That's fair enough- if others agree we could throw an exception if (a) the equivalent variable does not exist  and (b) the variable passed to `addVariable()` already has a parent component.

+1

**Comment by jonc125** [comment]
> I think leaving it until later will either lead to a) not meeting that requirement or b) only meeting it with a lot of rework, facing the very challenges that are being avoided this time around. I would strongly recommend not leaving these decisions until 'later' - they won't get any easier. It might feel like progress but it isn't.

I'd agree with this in general, but I'm not sure it's the case here. Are there any future use cases for the API which require maintaining the specific syntax of serialisation, not just semantics?  It strikes me that something like a CellML editor which wants to offer a text view is probably going to need to work at the DOM level anyway, like in OpenCor. And it's editors where you most want to retain syntax, to avoid obscuring changes in a VCS history. As I understand it, the goal for the new libCellML has always been to work at the semantic level.

**Comment by mtcooling** [comment]
There have always been (at least) two schools of thought on that.

For libcellml, there is this requirement in the Requirements doc
https://docs.google.com/document/d/1qMpltGGk19RgFAgkgnG8xZVKyI0Q-ZatcxV7VB_ccKc/edit?usp=sharing

"Preserve the order of elements, and whitespace where possible"

Realistically, I'd say it was up to the people building it to decide what
they are going to do, as long as the CellML Board and the community accepts
it.

Perhaps the whitespace aspect shouldn't be a requirement at all? It seems
to be causing a bit of concern (I've raised it here but it was being
discussed before I looked into this today), and actually isn't explictly
mentioned in the Roadmap as far as I can see from a quick skim.

One way to cover all bases might be to propose that it isn't a requirement
and put that to the community to see if anyone minds any more?

**Comment by agarny** [comment]
> "Preserve the order of elements, and whitespace where possible"

Good point @mtcooling. I believe I was one of the people who asked for this back then (at least when it comes to the order of elements) and that was a direct result of a conversation I once had with Jonna Terkildsen (many years ago indeed). Indeed, back then, Jonna told me that she sometimes edited the CellML 'by hand' and therefore used to put her CellML elements in a certain order, which once edited in COR (at the time) meant that the order was then lost.

> One way to cover all bases might be to propose that it isn't a requirement and put that to the community to see if anyone minds any more?

I guess it could be done.

**Comment by jonc125** [comment]
In terms of order of elements, it's straightforward for the library to use a consistent ordering when writing out, e.g. by always sorting (e.g. connections ordered by component & variable names, components ordered by name, etc), and/or storing objects in ordered data structures, so provided only libCellML writes a file element order will be preserved (and indeed whitespace too!).

The issues arise where something else is editing files, as Alan notes. We could add an order attribute to most objects; it's only connections where this gets trickier, but it's not insurmountable (e.g. keep a separate ordered list of variable pairs when reading the file, and keep the same order for existing connections when writing). But if you go down this path you do need to start thinking about attribute ordering and other aspects of canonicalisation... which I think is more trouble than it's worth.

So yes, a poll of interested parties might be best, although hopefully most of them are looking at this repo from time to time :)

**Comment by mtcooling** [comment]
> I must say that I find your comments difficult to follow.

sorry :)

> Can't you have everything in one comment?

....no but I'll try to be more concise..... :p

> Also, if you want to quote someone

Thanks, yeah I thought I had actually, but I used email to write them and it clipped the markdown

**Comment by nickerso** [comment]
>  it's only connections where this gets trickier

its probably a similar issue with encapsulation, which similarly have no actual representation in the libCellML object model.

For myself, it is pretty clear that core libCellML is dealing purely with the semantic representation of CellML models and currently we have no plans to even be reading or writing files directly. I'm thinking that whatever layer goes on top of this core to actual parse files or write them will contain the logic to keep formatting, ordering, etc. consistent when required.

**Comment by dladd** [comment]
Thanks all for the discussion. For further details on the plan to implement connections, please see #85 . To summarise the main points:
- Variable equivalences will be assigned by the user with an `addEquivalence()` operator.
- Equivalences are reciprocal (`v1.addEquivalence(v2)` is the same as `v2.addEquivalence(v1)` and will add "equivalent variables" to each variable object)
- Under the hood, connections are assembled as a set of unique equivalence pairs to be built when needed (e.g., at serialisation). We are calling a unique equivalence pair a `VariableMap` but this is not a feature that will be exposed to the public/users.

One remaining point that @nickerso brought up is whether or not to serialise incomplete connections. For example, if we had a similar setup to the original post but without `v2` added to a component:

``` c++
    libcellml::Model m;
    libcellml::ComponentPtr comp1 = std::make_shared<libcellml::Component>();
    libcellml::ComponentPtr comp2 = std::make_shared<libcellml::Component>();
    libcellml::VariablePtr v1 = std::make_shared<libcellml::Variable>();
    libcellml::VariablePtr v2 = std::make_shared<libcellml::Variable>();

    comp1->setName("component1");
    comp2->setName("component2");
    v1->setName("variable1");
    v2->setName("variable2");

    v1->addEquivalence(v2);
    comp1->addVariable(v1);
    m.addComponent(comp1);
    m.addComponent(comp2);
    m.serialise(libcellml::FORMAT_XML);
```

we could generate an incomplete connection:

``` XML
      ...
      <connection>
        <map_components component_1=\"component1\"/>
        <map_variables variable_1=\"variable1\" variable_2=\"variable2\"/>
      </connection>
    </model>
```

or no connection. I'm in favour of serialising an incomplete connection as I think it gives a better indication of why the expected generated connection is invalid and also think the approach is consistent with previous practice.

If there are no objections to any of the above, I'll close this issue as we move on with the implementation.

**Comment by mtcooling** [comment]
> I'm in favour of serialising an incomplete connection

My 2c: it makes sense to me to be able to serialize invalid or incomplete
CellML. Only being able to save valid CellML models in a previous tool was
a bit irritating :p.

Does the semantic model have a bucket to put the unparseable / incomplete
constructions in, especially when round-tripping with a model that contains
incomplete or invalid constructions? I think they should be preserved even
if they don't make sense. Or is it handled some other way perhaps outside
of the 'core' ?

**Comment by dladd** [comment]
> Does the semantic model have a bucket to put the unparseable / incomplete constructions in...

I would think this would need to be aware of the separate tool (TBD) that deals with validation to identify if a construction was unparseable / incomplete. Or at least be something to consider at later "Load" or "Validate" steps. Maybe this could be part of another discussion issue fleshing out more of the downstream goals / use-cases?

**Comment by agarny** [comment]
> My 2c: it makes sense to me to be able to serialize invalid or incomplete CellML. Only being able to save valid CellML models in a previous tool was a bit irritating :p.

Hmm, I wonder what other tool it might be... :)

> Does the semantic model have a bucket to put the unparseable / incomplete constructions in...

I would say that it is outside of the 'core'.
