### ISSUE TITLE
Using PREFIX_UNIT to indicate an undefined prefix

### ISSUE THREAD

**Issue by dladd** [cellml/libcellml#86]
Currently, unit prefixes are set by default to the [PREFIX_UNIT enumerator](https://github.com/cellml/libcellml/blob/develop/src/api/libcellml/enumerations.h#L51) as a tidy way to indicate that no prefix has been set.

However, it has been suggested that this may not be strictly correct, since a base unit by definition does not have a prefix and therefore may not belong in the PREFIXES enum.  An alternative proposal is to remove `PREFIX_UNIT` and add a `mHasPrefix` Boolean attribute to `Unit` to indicate whether a prefix has been set.

To vote, use a thumbs-up for keeping `PREFIX_UNIT`, a thumbs-down for `mHasPrefix`, or leave a comment for other proposals (or general discussion).

**Comment by nickerso** [comment]
Just to clarify that the actual default value for a unit prefix is the real value `0.0`, not an undefined prefix name string. Following the other discussions regarding `interface=none`, when the prefix has this value it should not be serialised, but in all other cases the prefix should be serialised. To me, this means that if the prefix enum has a value, it should be serialised. Hence my thumbs-down, although perhaps really should be `mHasPrefixEnum` or `mHasPrefixName`.

**Comment by hsorby** [comment]
> Just to clarify that the actual default value for a unit prefix is the real value 0.0

From the spec. libcellml needs to output or validate according to the spec. but isn't tied directly to it.

I would prefer `mPrefixEnumSet` for class attribute.

I would have preferred to have this incorporated in the enum but sadly the people who make definitions down at SI didn't define `unit` or an equivalent, very inconsiderate!

**Comment by agarny** [comment]
I am a bit confused. If we were to have `mHasPrefix` (or whatever name we would end up with) and get rid of `PREFIX_UNIT`, a base unit would still have the attributes `mPrefixInt` and `mPrefixEnum` (like any other unit). So, what value would those attributes have?

Talking of the `mPrefixInt` and `mPrefixEnum` attributes, I had never realised that the prefix information of a unit is stored either as an `int` or an `enum`. Why not simply have a `mPrefix` attribute as an `int` (and convert an `enum` to an `int` whenever necessary)?

**Comment by jonc125** [comment]
Indeed, I hadn't spotted that. Or even use a `union`?

**Comment by hsorby** [comment]
Just as a note that `int` should really be a `double` or `float` it's a mistake that it is an `int`

**Comment by dladd** [comment]
To recap where we are on this:

@agarny brought up a good point re: `mPrefixEnum` still needing a default and/or base unit value if we get rid of `PREFIX_UNIT`. We could just pick a default, for instance `PREFIX_YOTTA`. This won't functionally matter, since we'd be testing whether to use enumerators with `mPrefixEnumSet` but it might arguably look odd to someone looking at `struct Unit`.

Re: 

> Why not simply have a mPrefix attribute as an int (and convert an enum to an int whenever necessary)?

from the Spec:

> If the unit element does not have a prefix attribute information item, the prefix term SHALL have value 0.0. **If the prefix attribute information item has a value which is a real number string, then the prefix term SHALL have the corresponding numerical value**. Otherwise, the prefix attribute information item MUST have a value taken from the ‘Name’ column of the Prefix values table, and the prefix term SHALL have the value taken from the ‘Value’ column of the same row.

So, as @hsorby pointed out, we also need to change `mPrefixInt` to `mPrefixDouble` (or `mPrefixFloat`) and there is a distinction we need to make between this and a 'Name'-type prefix. 

Using a `union` is an interesting idea and could work since an `mPrefix` `union` will now be either a real number or `enum/int`. However, most of what I've read so far on `union`s has advised to only use them in instances where they save memory and to avoid them for type conversion.

**Comment by jonc125** [comment]
We could just store a `double` and convert to/from the string form at serialisation/parsing if the value was suitable, but that seems like more work than necessary.  I think the cleanest approach might be to use [boost::variant](http://www.boost.org/doc/libs/release/doc/html/variant.html) - a C++ alternative to `union`.

**Comment by agarny** [comment]
> We could just store a double and convert to/from the string form at serialisation/parsing if the value was suitable, but that seems like more work than necessary.

FWIW, this is what COR does (except that it stores a string instead).

> I think the cleanest approach might be to use boost::variant - a C++ alternative to union.

I don't think we (at least, I) want libCellML to rely on Boost.

**Comment by hsorby** [comment]
I certainly don't want libCellML to rely on Boost.

**Comment by dladd** [comment]
Re:

> > We could just store a double and convert to/from the string form at serialisation/parsing if the value was suitable, but that seems like more work than necessary.
> 
> FWIW, this is what COR does (except that it stores a string instead).

In this case, how might a user output the prefix as (for example) "-3.0" rather than "milli"? Unless you just mean output the real value as a string and not converting to the SI prefix names? 

I think it sounds like we are converging on a  three-attribute approach with `mPrefixDouble`, `mPrefixEnum`, `mPrefixEnumSet` ?

One last thing to consider is that changing to `mPrefixDouble` from `mPrefixInt` might make the ordering of arguments in the [current signatures](https://github.com/cellml/libcellml/blob/develop/src/units.cpp#L160) for `addUnit()` slightly confusing. If we keep the current behaviour, arguments to `addUnit()` will set: 
- (string, double) --> (name, exponent) 
- (string, double, double) --> (name, prefix, exponent) 
- (string, prefixEnumerator) --> (name, prefix) 

But I'm happy to keep this convention if others like it.

**Comment by agarny** [comment]
> In this case, how might a user output the prefix as (for example) "-3.0" rather than "milli"? Unless you just mean output the real value as a string and not converting to the SI prefix names? 

In COR, the prefix (the same for the exponent, multiplier and offset, in fact), is stored as a string. If we need the value of the prefix, then a conversion is done. This means checking the string against the different prefix names (e.g. `milli`) and returning the corresponding prefix value. If the string doesn't match any known prefix name, then it's assumed to be a prefix value and the string is simply converted to a double value.

**Comment by nickerso** [comment]
The COR approach doesn't seem too bad to me. Perhaps simply storing all the attributes as strings which can be easily serialised when required is the way to go. `libcellml::Units` could then perhaps provide convenience functions to convert words to numbers when required for dealing with math/unit conversion.

**Comment by dladd** [comment]
I think there is consensus here to move to a more OpenCOR-like treatment of `Unit`, with all `struct Unit` members (`mUnits`, `mPrefix`, `mExponent`, `mMultiplier`, and `mOffset`) as strings. The original issue from this thread would then be solved by adding the appropriate string to `mPrefix` based on whether the signature of `addUnit()` contains a PREFIXES enumerator or a `double`.

I would also suggest changing `Unit::mUnits` above to ~~`Unit::mUnitName`~~ `Unit::mName` to avoid confusion with the `Units::mUnits` collective attribute

**Comment by nickerso** [comment]
Which would remove `PREFIX_UNIT` completely, right?

**Comment by dladd** [comment]
Correct, @nickerso. The default value for `mPrefix` will be "0.0" so we would no longer need `PREFIX_UNIT`.

**Comment by dladd** [comment]
I think it might also be quite useful for a user to be able to specify the prefix directly as a string i.e.,

``` c++
u->addUnit(libcellml::STANDARD_UNIT_AMPERE, "micro");
```

instead of:

``` c++
u->addUnit(libcellml::STANDARD_UNIT_AMPERE, libcellml::PREFIX_MICRO);
```

We could have a `std::map<std::string, PREFIXES> stringToPrefix` to check if the supplied string is an admissible prefix. And maybe replace the switch-based `prefixToString` with a similar `std::map<PREFIXES, std::string> prefixToString`?

For a working example of how this might work, see https://github.com/dladd/libcellml/commit/4ca22a62d748f94b35da3fbe2b97ccd85f6e254e . (I don't want to put a pull request in on an unapproved feature) :)

**Comment by nickerso** [comment]
Looking at the comments, I'd suggest making that pull request :) Seems like the way to go to resolve this particular issue.
