### ISSUE TITLE
Provide PyPI distribution for Python3.9/Linux

### ISSUE THREAD

**Issue by jonrkarr** [cellml/libcellml#860]
The new library looks helpful. We'd be interested to integrate it into a library for working with SED-ML, including validating SED-ML files that describes simulations of CellML models. From your documentation, this should be easy for us to do.

Could you provide a distribution for Python 3.9/Linux? Currently there's Python 3.7 and 3.8 for Linux and 3.9 for Mac and Windows.

**Comment by hsorby** [comment]
Yes, I think this should be something we can do. It will take a little bit of work because the ManyLinux platform is not super easy to use like Windows and macOS.

**Comment by jonrkarr** [comment]
Thanks! Could you let me know when its available on PyPI?

Once its available, we should be able to quickly use it to provide validation for CellML + SED-ML + COMBINE.

**Comment by hsorby** [comment]
I'll try and set off a build today.  I first have to remember how :(

**Comment by hsorby** [comment]
I have uploaded a version to PyPi now.  If you try `pip install libcellml` you should get a working version of `0.2.0.dev21`.  I have tested the build on Ubuntu 20.04 with python 3.8 and that worked.  I don't have python 3.9 to test so I'll just hope that it works.

**Comment by agarny** [comment]
I have just tried it on macOS using Python 3.9.5 and it all seems fine (read: `import libcellml; libcellml.version()` works fine). 🥳

**Comment by jonrkarr** [comment]
I installed it into 3.9.4 on Ubtuntu. It seems to work fine. Thanks!
