### ISSUE TITLE
Simplifying the rough object model diagram

### ISSUE THREAD

**Issue by dladd** [cellml/libcellml#87]
As the object model is expanded with new features (for example see the file changes in #85 ), it is becoming somewhat unwieldy to view as an extensive list of all overloaded functions and private members. It has been suggested that this diagram would better serve as a birds-eye overview (hence the "rough" in the title) of the public-facing API.

For explicit details on all available functions and features (public and private) and full class diagrams we would instead refer to the generated Doxygen documentation. This would provide more granularity, be less prone to errors from transcription & unincorporated changes, and generally be a more direct reflection of the code in its current state.

To vote, use a thumbs-up for a simplified diagram, a thumbs-down for an explicit-as-possible diagram, or leave a comment for other proposals (or general discussion).

**Comment by hsorby** [comment]
I do think it should be an overview of **all** objects, perhaps we colour objects that are not seen/manipulated through the API in orange.

**Comment by jonc125** [comment]
I guess it depends on whether the diagram is for our benefit as we develop the API, or for eventual users. If the former, I agree with @hsorby; if the latter then it should only contain publicly accessible objects.

**Comment by dladd** [comment]
I think there is consensus here around a simplified diagram of all objects, with colour-coding used to indicate public vs. private. We may want to revisit dropping privately accessible objects in future user-specific documentation.
