### ISSUE TITLE
Improve Importers ability to handle base directory

### ISSUE THREAD

**Issue by hsorby** [cellml/libcellml#872]
Currently the `Importer` base directory must end in a trailing slash.  The documentation on `resolveImports` does not mention this fact.  Either the documentation needs to be updated or fix the code to detect trailing slash and add one if there is not one present.

**Comment by agarny** [comment]
I would definitely fix the code. After all, both `cd /my/path` and `cd /my/path/` work, and that's what people are used to.

**Comment by nickerso** [comment]
duplicate of #592 ?

**Comment by agarny** [comment]
> duplicate of #592 ?

Indeed.
