### ISSUE TITLE
Object Model for Use Cases 1.i - 1.iii

### ISSUE THREAD

**Issue by hsorby** [cellml/libcellml#9]
This issue is for discussion around the object model that we should implement to at least meet the needs of Use Cases 1.i - 1.iii

**Comment by jonc125** [comment]
When it comes to supporting Maths, is there any chance of extracting relevant parts from libSBML, or at least collaborating? Most of the COMBINE standards need to handle mathematics defined in XML, and it'd be nice if we didn't have to either implement it ourselves (like the CellML API) or rely on libSBML (like libSEDML).

**Comment by nickerso** [comment]
I agree that a common MathML implementation across the COMBINE projects would be useful. And I know that people have expressed an interest in making use of the libSBML MathML support outside of libSBML previously. I would imagine that we would need to do the work to extract the MathML bits from libSBML. There would also be a fair amount of work required to extend the libSBML implementation to support the use of MathML in the way that we use it in CellML (for example, there is no concept in [lib]SBML for expressing an ODE in pure MathML). At HARMONY there was some discussion on an upcoming proposal for extending the range of MathML allowed in SBML (and hence to be supported by libSBML), but I'm not too sure how that will go. But this approach is certainly something that will be considered and investigated.

**Comment by nickerso** [comment]
fixed in #10
