### ISSUE TITLE
Funding acknowledgement

### ISSUE THREAD

**Issue by nickerso** [cellml/libcellml#90]
We need to be sure to include a funding acknowledgement section in the documentation and track all the funding received to support libCellML development. Perhaps even on the front page of the website with logos and links?

**Comment by agarny** [comment]
+1 on having such an acknowledgement in the documentation.

As for the website, well... what website? For the CellML API, I am aware of https://www.cellml.org/tools/api and http://cellml-api.sourceforge.net/, but do we have anything for libCellML per se? (Incidentally, I can't say that I like having something hosted on SourceForge.)

**Comment by nickerso** [comment]
> As for the website, well... what website? 

Well, currently its just http://libcellml.readthedocs.org :) no plans that I'm aware of to make a separate website, although we should really make sure the links from cellml.org are in place.

**Comment by agarny** [comment]
Ok, then +1 on updating cellml.org with the right link to http://libcellml.readthedocs.org/ and having the front page of the libCellML website with logos and links.

**Comment by nickerso** [comment]
just to point out that readthedocs have today changed everything to readthedocs.io, so the website will now be http://libcellml.readthedocs.io - although http://libcellml.readthedocs.org will redirect for the foreseeable future.

**Comment by dladd** [comment]
I've now added this in pull #91 . You can find the [buildbot test page here](http://autotest.bioeng.auckland.ac.nz/libcellml-buildbot/7035f42beaf3f6586d2196c518f5e8f40e5fe079/dox/index.html).
