### ISSUE TITLE
CMake: mark `CCACHE_EXE` as advanced

### ISSUE THREAD

**Issue by agarny** [cellml/libcellml#920]
When using a tool like `ccmake`, we only want to see the options that are directly related to libCellML. All the other options should be marked as advanced. We do this for all those other options except for `CCACHE_EXE`. So, we should mark `CCACHE_EXE` as advanced, so that by default we only see libCellML-related options.

**Comment by nickerso** [comment]
good to have a description as to what the issue is to help those of us who don't know why this needs to be fixed...

**Comment by agarny** [comment]
Fair point. Just added a description.
