### ISSUE TITLE
Disable Clang-Tidy by default

### ISSUE THREAD

**Issue by agarny** [cellml/libcellml#923]
Right now, if you have Clang-Tidy installed on your system then our build system will find it and set `LIBCELLML_CLANG_TIDY` to `ON`. However, to build libCellML with Clang-Tidy is very slow. So, it would be good to have it disabled by default.

**Comment by hsorby** [comment]
We will need to modify the CI as this will have an affect there.  This will need to be done before this can be merged in otherwise the clang tidy check will no longer function.

**Comment by agarny** [comment]
Fair enough. Looking forward to the CI being updated then. :)

**Comment by nickerso** [comment]
Seems like #347 was fixed but incorrectly set the default to on :)

**Comment by agarny** [comment]
Oopsie indeed!

**Comment by hsorby** [comment]
I have updated the CI. This one can be dealt with now.  We should check afterwards that the CI is indeed working of course and not just take my word for it.

**Comment by agarny** [comment]
If I compare an [old build](https://autotest.bioeng.auckland.ac.nz/buildbot/libcellml/#/builders/9/builds/1285/steps/5/logs/stdio) with a [new build](https://autotest.bioeng.auckland.ac.nz/buildbot/libcellml/#/builders/9/builds/1287/steps/5/logs/stdio), I can see that you now pass `-DCLANG_TIDY=TRUE`, so that looks good to me. (Not sure we can further test things without "upsetting" Clang-Tidy. Might give it a try!)

**Comment by agarny** [comment]
Testing Clang-Tidy in our CI machine through ee94ffb.

**Comment by agarny** [comment]
Otherwise, I noticed that our Clang-Tidy checks are somewhat weak (nowadays?). For instance:
```c++
ModelPtr otherParent = std::dynamic_pointer_cast<Model>(units->parent());
```
should be replaced with:
```c++
auto otherParent = std::dynamic_pointer_cast<Model>(units->parent());
```
but now, both are allowed.

Same with:
```c++
if (x != nullptr)...
```
and
```c++
if (x) ...
```
Both are allowed...!?

**Comment by agarny** [comment]
Ok, Clang-Tidy is properly set on our CI machine. 🥳
