### ISSUE TITLE
Generator: further refinements to the generated C code

### ISSUE THREAD

**Issue by agarny** [cellml/libcellml#938]
- [x] For an algebraic model, we don't need to define the `VariableInfo` structure (this was an oversight on my part in #901).
- [x] In C, to cast the output of `malloc()` is redundant (see [here](https://en.wikipedia.org/wiki/C_dynamic_memory_allocation#Type_safety)). To cast would normally allow our generated C code to be compilable by a C++ compiler, but then again any decent C++ compiler would complain our use of `malloc()`/`free()`. So, we may as well stick to the C standard.

**Comment by nickerso** [comment]
I'm not completely convinced about removing the casting of `malloc()`. Have we tested that our traditional LLVM-based dynamic compilation of the generated code is happy with that?

**Comment by agarny** [comment]
I tried it in OpenCOR. I normally treat warnings as errors and neither
```c
double * createVariablesArray()
{
    return (double *) malloc(3*sizeof(double));
}
```
nor
```c
double * createVariablesArray()
{
    return malloc(3*sizeof(double));
}
```
can be compiled. However, if I don't treat warnings as errors, then both  can be compiled just fine.

So, yes, it's all fine and the suggested change means that the code respect the C standard even more.
