### ISSUE TITLE
CMake: `coverage_branches` target needed?

### ISSUE THREAD

**Issue by agarny** [cellml/libcellml#955]
Is the `coverage_branches` target needed? It looks like we don't use it in our CI tests?

**Comment by hsorby** [comment]
It isn't needed as such but branch information is useful in understanding code coverage.

**Comment by agarny** [comment]
So, we don't make use of it in our CI tests, but we keep that CMake target in case people want to get a bit more information? I guess there is nothing wrong with that *per se*, so closing.
