### ISSUE TITLE
CMake: need the `coverage` package to be present for our Python coverage

### ISSUE THREAD

**Issue by agarny** [cellml/libcellml#957]
For our Python coverage to be available, we don't only need the `exclude-until-coverage-plugin` Python package, but also the `coverage` one.

**Comment by hsorby** [comment]
The `exclude-until-coverage-plugin` requires `coverage` so we do only need `exclude-until-coverage-plugin`.

**Comment by agarny** [comment]
Damn, I should have put a bit more context as I can't imagine (then again, who knows?!) creating this issue if there wasn't a need for it... but granted, I have just did `pip install exclude-until-coverage-plugin` on a vanilla Python virtual environment and it also installed `coverage`, so... closing... 🙄🙂
