### ISSUE TITLE
CMake: allow zlib to be found using ZLIB_ROOT

### ISSUE THREAD

**Issue by agarny** [cellml/libcellml#975]
If we want to tell CMake where to look for `zlib`, we can pass `ZLIB_ROOT` to it. However, this results in the following CMake warning:
```
CMake Warning (dev) at cmake/environmentchecks.cmake:147 (find_package):
  Policy CMP0074 is not set: find_package uses <PackageName>_ROOT variables.
  Run "cmake --help-policy CMP0074" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  CMake variable ZLIB_ROOT is set to:

    /Users/Alan/libOpenCOR/build/zlib

  For compatibility, CMake is ignoring the variable.
Call Stack (most recent call first):
  CMakeLists.txt:40 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.
```

**Comment by nickerso** [comment]
you shouldn't be using `ZLIB_ROOT` right? isn't it `ZLIB_DIR` ? and in general I don't even set it as it is picked up in the config dependencies for libXml2...

**Comment by agarny** [comment]
Apparently, you can (see [here](https://github.com/Kitware/CMake/blob/master/Modules/FindZLIB.cmake#L51-L55)). Different libraries can be found in different ways with CMake (!!). For `libxml2`, you can help CMake to find it by passing `LIBXML2_INCLUDE_DIR` and `LIBXML2_LIBRARY` to it (see [here](https://github.com/Kitware/CMake/blob/master/Modules/FindLibXml2.cmake#L44-L52)).

The reason I need this is that for `libOpenCOR`, I want to use "my" copy of the dependencies.

**Comment by agarny** [comment]
FTR, I appreciate that one might prefer to use the `XxxConfig.cmake` to configure `Xxx`, but such a file is not always available (e.g., it's not for the [`zlib` implementation](https://github.com/zlib-ng/zlib-ng) that I use in libOpenCOR). In fact, even if there was to be such a file, I couldn't use it since I build `libCellML` using `ExternalProject_Add()`. So, all I can do is to pass it some CMake arguments and this is where `ZLIB_ROOT` comes in as being very handy.
